In [1]:
import pandas as pd
from pathlib import Path
import gc # memory management

import optuna
from catboost import CatBoostClassifier, cv, Pool
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import balanced_accuracy_score

C:\miniforge3\envs\machine-learning\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## preprocessing

In [2]:
DATA_DIR = Path("../../data/kaggle-irrigation")
SEED = 42

In [3]:
train = pd.read_csv(DATA_DIR / "train.csv", index_col="id")
train.head()

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
id,,,,,,,,,,,,,,,,,,,,
0,Loamy,4.92,32.58,1.01,3.05,15.01,50.61,725.99,5.90,16.79,Sugarcane,Sowing,Zaid,Drip,Rainwater,0.82,No,112.16,East,Low
1,Clay,7.08,56.61,0.44,2.00,22.92,67.86,985.66,6.98,3.39,Wheat,Vegetative,Kharif,Rainfed,River,5.27,Yes,47.16,South,Low
2,Clay,5.69,27.71,0.81,2.83,26.97,92.22,2201.70,6.05,3.85,Rice,Vegetative,Kharif,Sprinkler,Reservoir,8.24,Yes,110.38,North,Low
3,Sandy,5.65,13.32,1.33,0.87,13.32,61.57,1357.33,9.12,2.31,Wheat,Flowering,Kharif,Canal,River,8.32,Yes,53.85,South,Medium
4,Clay,7.96,59.14,0.38,0.96,20.22,91.11,1538.20,6.95,13.94,Wheat,Sowing,Rabi,Canal,River,7.37,No,93.19,South,Low

In [4]:
X = train.drop(columns="Irrigation_Need")
y = train["Irrigation_Need"]

# encode y
le = LabelEncoder()
y_encoded = le.fit_transform(y)

CAT_COLS = X.select_dtypes(include="object").columns.tolist()
cat_indices = [X.columns.tolist().index(c) for c in CAT_COLS]

C:\Users\Austin Muelrath\AppData\Local\Temp\ipykernel_15868\4134195525.py:8: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  CAT_COLS = X.select_dtypes(include="object").columns.tolist()

In [5]:
# split data
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.4, random_state=SEED, shuffle=True, stratify=y_encoded)

## base model

In [6]:
base_cb = CatBoostClassifier(random_state=SEED, cat_features=cat_indices, task_type="GPU")
base_cb.fit(X_train, y_train)

Learning rate set to 0.217817
0:	learn: 0.8554826	total: 20.5ms	remaining: 20.5s
1:	learn: 0.6071780	total: 32.5ms	remaining: 16.2s
2:	learn: 0.4598465	total: 42.8ms	remaining: 14.2s
3:	learn: 0.3609824	total: 53.5ms	remaining: 13.3s
4:	learn: 0.2906790	total: 63.6ms	remaining: 12.7s
5:	learn: 0.2390376	total: 75.5ms	remaining: 12.5s
6:	learn: 0.2004592	total: 86.4ms	remaining: 12.3s
7:	learn: 0.1711257	total: 97.1ms	remaining: 12s
8:	learn: 0.1490620	total: 109ms	remaining: 12s
9:	learn: 0.1314561	total: 119ms	remaining: 11.8s
10:	learn: 0.1183631	total: 130ms	remaining: 11.7s
11:	learn: 0.1074331	total: 141ms	remaining: 11.6s
12:	learn: 0.0996048	total: 151ms	remaining: 11.4s
13:	learn: 0.0930560	total: 160ms	remaining: 11.3s
14:	learn: 0.0875832	total: 171ms	remaining: 11.2s
15:	learn: 0.0831945	total: 180ms	remaining: 11.1s
16:	learn: 0.0797613	total: 189ms	remaining: 10.9s
17:	learn: 0.0771953	total: 199ms	remaining: 10.8s
18:	learn: 0.0748936	total: 209ms	remaining: 10.8s
19:	learn: 0.0730419	total: 218ms	remaining: 10.7s
20:	learn: 0.0713643	total: 228ms	remaining: 10.6s
21:	learn: 0.0703728	total: 238ms	remaining: 10.6s
22:	learn: 0.0695503	total: 247ms	remaining: 10.5s
23:	learn: 0.0688307	total: 256ms	remaining: 10.4s
24:	learn: 0.0682181	total: 266ms	remaining: 10.4s
25:	learn: 0.0678198	total: 275ms	remaining: 10.3s
26:	learn: 0.0676170	total: 285ms	remaining: 10.3s
27:	learn: 0.0671238	total: 294ms	remaining: 10.2s
28:	learn: 0.0668529	total: 305ms	remaining: 10.2s
29:	learn: 0.0664971	total: 315ms	remaining: 10.2s
30:	learn: 0.0662736	total: 324ms	remaining: 10.1s
31:	learn: 0.0660523	total: 334ms	remaining: 10.1s
32:	learn: 0.0659452	total: 343ms	remaining: 10s
33:	learn: 0.0658056	total: 353ms	remaining: 10s
34:	learn: 0.0655660	total: 362ms	remaining: 9.98s
35:	learn: 0.0655081	total: 370ms	remaining: 9.92s
36:	learn: 0.0652506	total: 380ms	remaining: 9.88s
37:	learn: 0.0651430	total: 388ms	remaining: 9.83s
38:	learn: 0.0650913	total: 397ms	remaining: 9.78s
39:	learn: 0.0649925	total: 406ms	remaining: 9.75s
40:	learn: 0.0649378	total: 415ms	remaining: 9.7s
41:	learn: 0.0648703	total: 423ms	remaining: 9.65s
42:	learn: 0.0648103	total: 432ms	remaining: 9.61s
43:	learn: 0.0645690	total: 440ms	remaining: 9.57s
44:	learn: 0.0644847	total: 448ms	remaining: 9.51s
45:	learn: 0.0644100	total: 461ms	remaining: 9.57s
46:	learn: 0.0643340	total: 473ms	remaining: 9.6s
47:	learn: 0.0642780	total: 485ms	remaining: 9.61s
48:	learn: 0.0641787	total: 494ms	remaining: 9.59s
49:	learn: 0.0641263	total: 504ms	remaining: 9.57s
50:	learn: 0.0640505	total: 514ms	remaining: 9.56s
51:	learn: 0.0640133	total: 524ms	remaining: 9.56s
52:	learn: 0.0639609	total: 533ms	remaining: 9.52s
53:	learn: 0.0638875	total: 541ms	remaining: 9.48s
54:	learn: 0.0637553	total: 549ms	remaining: 9.44s
55:	learn: 0.0636638	total: 558ms	remaining: 9.4s
56:	learn: 0.0636424	total: 566ms	remaining: 9.36s
57:	learn: 0.0636150	total: 574ms	remaining: 9.32s
58:	learn: 0.0635866	total: 582ms	remaining: 9.28s
59:	learn: 0.0635526	total: 590ms	remaining: 9.24s
60:	learn: 0.0635004	total: 598ms	remaining: 9.21s
61:	learn: 0.0634530	total: 607ms	remaining: 9.18s
62:	learn: 0.0633969	total: 615ms	remaining: 9.15s
63:	learn: 0.0633311	total: 624ms	remaining: 9.13s
64:	learn: 0.0632950	total: 633ms	remaining: 9.1s
65:	learn: 0.0632413	total: 641ms	remaining: 9.07s
66:	learn: 0.0631897	total: 649ms	remaining: 9.04s
67:	learn: 0.0631714	total: 659ms	remaining: 9.03s
68:	learn: 0.0631433	total: 668ms	remaining: 9.01s
69:	learn: 0.0631271	total: 676ms	remaining: 8.98s
70:	learn: 0.0631077	total: 684ms	remaining: 8.95s
71:	learn: 0.0630011	total: 693ms	remaining: 8.93s
72:	learn: 0.0629794	total: 701ms	remaining: 8.89s
73:	learn: 0.0629500	total: 708ms	remaining: 8.86s
74:	learn: 0.0629173	total: 716ms	remaining: 8.83s
75:	learn: 0.0628865	total: 725ms	remaining: 8.81s
76:	learn: 0.0627979	total: 733ms	remaining: 8.78s
77:	learn: 0.0627006	total: 742ms	remaining: 8.77s
78:	learn: 0.0626750	total: 750ms	remaining: 8.74s
79:	learn: 0.0626306	total: 759ms	remaining: 8.72s
80:	learn: 0.0626219	total: 766ms	remaining: 8.69s
81:	learn: 0.0625771	total: 774ms	remaining: 8.67s
82:	learn: 0.0625425	total: 783ms	remaining: 8.65s
83:	learn: 0.0624632	total: 792ms	remaining: 8.64s
84:	learn: 0.0624283	total: 801ms	remaining: 8.62s
85:	learn: 0.0624129	total: 808ms	remaining: 8.59s
86:	learn: 0.0623615	total: 817ms	remaining: 8.57s
87:	learn: 0.0623358	total: 825ms	remaining: 8.55s
88:	learn: 0.0623221	total: 833ms	remaining: 8.53s
89:	learn: 0.0622788	total: 842ms	remaining: 8.52s
90:	learn: 0.0622587	total: 850ms	remaining: 8.49s
91:	learn: 0.0622391	total: 859ms	remaining: 8.48s
92:	learn: 0.0622076	total: 868ms	remaining: 8.46s
93:	learn: 0.0621878	total: 876ms	remaining: 8.44s
94:	learn: 0.0621544	total: 885ms	remaining: 8.43s
95:	learn: 0.0621427	total: 894ms	remaining: 8.41s
96:	learn: 0.0621292	total: 902ms	remaining: 8.39s
97:	learn: 0.0620651	total: 911ms	remaining: 8.38s
98:	learn: 0.0620276	total: 919ms	remaining: 8.36s
99:	learn: 0.0619807	total: 928ms	remaining: 8.35s
100:	learn: 0.0619804	total: 936ms	remaining: 8.33s
101:	learn: 0.0619220	total: 945ms	remaining: 8.32s
102:	learn: 0.0618894	total: 953ms	remaining: 8.3s
103:	learn: 0.0618578	total: 962ms	remaining: 8.29s
104:	learn: 0.0617424	total: 971ms	remaining: 8.28s
105:	learn: 0.0617269	total: 979ms	remaining: 8.26s
106:	learn: 0.0616882	total: 988ms	remaining: 8.25s
107:	learn: 0.0615920	total: 996ms	remaining: 8.23s
108:	learn: 0.0615653	total: 1s	remaining: 8.21s
109:	learn: 0.0615415	total: 1.01s	remaining: 8.2s
110:	learn: 0.0614968	total: 1.02s	remaining: 8.2s
111:	learn: 0.0614874	total: 1.03s	remaining: 8.19s
112:	learn: 0.0614661	total: 1.04s	remaining: 8.17s
113:	learn: 0.0614259	total: 1.05s	remaining: 8.16s
114:	learn: 0.0613989	total: 1.06s	remaining: 8.16s
115:	learn: 0.0613636	total: 1.07s	remaining: 8.15s
116:	learn: 0.0613213	total: 1.08s	remaining: 8.13s
117:	learn: 0.0613085	total: 1.09s	remaining: 8.13s
118:	learn: 0.0613080	total: 1.09s	remaining: 8.11s
119:	learn: 0.0612757	total: 1.1s	remaining: 8.1s
120:	learn: 0.0612451	total: 1.11s	remaining: 8.09s
121:	learn: 0.0612036	total: 1.12s	remaining: 8.08s
122:	learn: 0.0611850	total: 1.13s	remaining: 8.07s
123:	learn: 0.0611631	total: 1.14s	remaining: 8.05s
124:	learn: 0.0611252	total: 1.15s	remaining: 8.05s
125:	learn: 0.0611130	total: 1.16s	remaining: 8.03s
126:	learn: 0.0610501	total: 1.17s	remaining: 8.03s
127:	learn: 0.0610415	total: 1.18s	remaining: 8.01s
128:	learn: 0.0610188	total: 1.19s	remaining: 8.01s
129:	learn: 0.0609694	total: 1.19s	remaining: 7.99s
130:	learn: 0.0609557	total: 1.2s	remaining: 7.98s
131:	learn: 0.0609146	total: 1.21s	remaining: 7.96s
132:	learn: 0.0609054	total: 1.22s	remaining: 7.95s
133:	learn: 0.0608826	total: 1.23s	remaining: 7.94s
134:	learn: 0.0608555	total: 1.24s	remaining: 7.93s
135:	learn: 0.0608454	total: 1.25s	remaining: 7.91s
136:	learn: 0.0608188	total: 1.25s	remaining: 7.9s
137:	learn: 0.0608006	total: 1.26s	remaining: 7.88s
138:	learn: 0.0607747	total: 1.27s	remaining: 7.87s
139:	learn: 0.0607236	total: 1.28s	remaining: 7.86s
140:	learn: 0.0606706	total: 1.29s	remaining: 7.85s
141:	learn: 0.0606269	total: 1.3s	remaining: 7.83s
142:	learn: 0.0605825	total: 1.3s	remaining: 7.82s
143:	learn: 0.0605397	total: 1.31s	remaining: 7.8s
144:	learn: 0.0604841	total: 1.32s	remaining: 7.79s
145:	learn: 0.0604021	total: 1.33s	remaining: 7.78s
146:	learn: 0.0603836	total: 1.34s	remaining: 7.77s
147:	learn: 0.0603534	total: 1.35s	remaining: 7.76s
148:	learn: 0.0603142	total: 1.35s	remaining: 7.74s
149:	learn: 0.0602555	total: 1.36s	remaining: 7.73s
150:	learn: 0.0602282	total: 1.37s	remaining: 7.72s
151:	learn: 0.0601917	total: 1.38s	remaining: 7.71s
152:	learn: 0.0601750	total: 1.39s	remaining: 7.7s
153:	learn: 0.0601229	total: 1.4s	remaining: 7.69s
154:	learn: 0.0601044	total: 1.41s	remaining: 7.67s
155:	learn: 0.0600855	total: 1.42s	remaining: 7.67s
156:	learn: 0.0600515	total: 1.43s	remaining: 7.66s
157:	learn: 0.0600078	total: 1.44s	remaining: 7.65s
158:	learn: 0.0599885	total: 1.44s	remaining: 7.64s
159:	learn: 0.0599338	total: 1.45s	remaining: 7.62s
160:	learn: 0.0599104	total: 1.46s	remaining: 7.63s
161:	learn: 0.0598866	total: 1.47s	remaining: 7.62s
162:	learn: 0.0598750	total: 1.48s	remaining: 7.61s
163:	learn: 0.0598631	total: 1.49s	remaining: 7.6s
164:	learn: 0.0598352	total: 1.5s	remaining: 7.58s
165:	learn: 0.0598241	total: 1.51s	remaining: 7.57s
166:	learn: 0.0597912	total: 1.52s	remaining: 7.57s
167:	learn: 0.0597858	total: 1.53s	remaining: 7.56s
168:	learn: 0.0597737	total: 1.53s	remaining: 7.54s
169:	learn: 0.0597599	total: 1.54s	remaining: 7.54s
170:	learn: 0.0597277	total: 1.55s	remaining: 7.53s
171:	learn: 0.0596992	total: 1.56s	remaining: 7.52s
172:	learn: 0.0596827	total: 1.57s	remaining: 7.51s
173:	learn: 0.0596730	total: 1.58s	remaining: 7.5s
174:	learn: 0.0596353	total: 1.59s	remaining: 7.49s
175:	learn: 0.0596256	total: 1.6s	remaining: 7.48s
176:	learn: 0.0595894	total: 1.6s	remaining: 7.47s
177:	learn: 0.0595530	total: 1.61s	remaining: 7.46s
178:	learn: 0.0595268	total: 1.62s	remaining: 7.45s
179:	learn: 0.0594961	total: 1.63s	remaining: 7.43s
180:	learn: 0.0594714	total: 1.64s	remaining: 7.42s
181:	learn: 0.0594517	total: 1.65s	remaining: 7.41s
182:	learn: 0.0594264	total: 1.66s	remaining: 7.41s
183:	learn: 0.0594104	total: 1.67s	remaining: 7.4s
184:	learn: 0.0593770	total: 1.68s	remaining: 7.39s
185:	learn: 0.0593591	total: 1.69s	remaining: 7.38s
186:	learn: 0.0593158	total: 1.69s	remaining: 7.37s
187:	learn: 0.0592527	total: 1.7s	remaining: 7.36s
188:	learn: 0.0592214	total: 1.71s	remaining: 7.35s
189:	learn: 0.0591986	total: 1.72s	remaining: 7.34s
190:	learn: 0.0591604	total: 1.73s	remaining: 7.33s
191:	learn: 0.0591482	total: 1.74s	remaining: 7.31s
192:	learn: 0.0591306	total: 1.75s	remaining: 7.3s
193:	learn: 0.0590822	total: 1.75s	remaining: 7.29s
194:	learn: 0.0590732	total: 1.76s	remaining: 7.28s
195:	learn: 0.0590311	total: 1.77s	remaining: 7.27s
196:	learn: 0.0590196	total: 1.78s	remaining: 7.26s
197:	learn: 0.0589887	total: 1.79s	remaining: 7.25s
198:	learn: 0.0589751	total: 1.8s	remaining: 7.24s
199:	learn: 0.0589472	total: 1.81s	remaining: 7.24s
200:	learn: 0.0589171	total: 1.82s	remaining: 7.22s
201:	learn: 0.0588957	total: 1.82s	remaining: 7.21s
202:	learn: 0.0588745	total: 1.83s	remaining: 7.2s
203:	learn: 0.0588234	total: 1.84s	remaining: 7.19s
204:	learn: 0.0587489	total: 1.85s	remaining: 7.18s
205:	learn: 0.0587290	total: 1.86s	remaining: 7.17s
206:	learn: 0.0587066	total: 1.87s	remaining: 7.16s
207:	learn: 0.0586845	total: 1.88s	remaining: 7.15s
208:	learn: 0.0586621	total: 1.89s	remaining: 7.14s
209:	learn: 0.0586449	total: 1.9s	remaining: 7.13s
210:	learn: 0.0586216	total: 1.91s	remaining: 7.13s
211:	learn: 0.0585986	total: 1.92s	remaining: 7.12s
212:	learn: 0.0585706	total: 1.92s	remaining: 7.11s
213:	learn: 0.0585384	total: 1.93s	remaining: 7.1s
214:	learn: 0.0585162	total: 1.94s	remaining: 7.09s
215:	learn: 0.0585084	total: 1.95s	remaining: 7.08s
216:	learn: 0.0584596	total: 1.96s	remaining: 7.07s
217:	learn: 0.0584177	total: 1.97s	remaining: 7.06s
218:	learn: 0.0583550	total: 1.98s	remaining: 7.05s
219:	learn: 0.0583234	total: 1.98s	remaining: 7.04s
220:	learn: 0.0583107	total: 1.99s	remaining: 7.03s
221:	learn: 0.0582541	total: 2s	remaining: 7.02s
222:	learn: 0.0582132	total: 2.01s	remaining: 7.02s
223:	learn: 0.0582050	total: 2.02s	remaining: 7.01s
224:	learn: 0.0581832	total: 2.03s	remaining: 7s
225:	learn: 0.0581301	total: 2.04s	remaining: 7s
226:	learn: 0.0580984	total: 2.05s	remaining: 6.99s
227:	learn: 0.0580860	total: 2.06s	remaining: 6.98s
228:	learn: 0.0580691	total: 2.07s	remaining: 6.97s
229:	learn: 0.0580417	total: 2.08s	remaining: 6.96s
230:	learn: 0.0580253	total: 2.09s	remaining: 6.95s
231:	learn: 0.0579972	total: 2.1s	remaining: 6.94s
232:	learn: 0.0579684	total: 2.11s	remaining: 6.93s
233:	learn: 0.0579049	total: 2.12s	remaining: 6.93s
234:	learn: 0.0578993	total: 2.12s	remaining: 6.91s
235:	learn: 0.0578853	total: 2.13s	remaining: 6.9s
236:	learn: 0.0578412	total: 2.14s	remaining: 6.89s
237:	learn: 0.0578188	total: 2.15s	remaining: 6.88s
238:	learn: 0.0577981	total: 2.16s	remaining: 6.87s
239:	learn: 0.0577619	total: 2.17s	remaining: 6.86s
240:	learn: 0.0577465	total: 2.17s	remaining: 6.85s
241:	learn: 0.0577322	total: 2.18s	remaining: 6.83s
242:	learn: 0.0577144	total: 2.19s	remaining: 6.83s
243:	learn: 0.0576871	total: 2.2s	remaining: 6.82s
244:	learn: 0.0576583	total: 2.21s	remaining: 6.82s
245:	learn: 0.0576212	total: 2.22s	remaining: 6.81s
246:	learn: 0.0575809	total: 2.23s	remaining: 6.8s
247:	learn: 0.0575493	total: 2.24s	remaining: 6.79s
248:	learn: 0.0575187	total: 2.25s	remaining: 6.78s
249:	learn: 0.0574934	total: 2.26s	remaining: 6.77s
250:	learn: 0.0574665	total: 2.27s	remaining: 6.76s
251:	learn: 0.0574577	total: 2.27s	remaining: 6.75s
252:	learn: 0.0574449	total: 2.28s	remaining: 6.74s
253:	learn: 0.0574069	total: 2.29s	remaining: 6.74s
254:	learn: 0.0573859	total: 2.3s	remaining: 6.73s
255:	learn: 0.0573749	total: 2.31s	remaining: 6.72s
256:	learn: 0.0573606	total: 2.32s	remaining: 6.71s
257:	learn: 0.0573256	total: 2.33s	remaining: 6.7s
258:	learn: 0.0572978	total: 2.34s	remaining: 6.69s
259:	learn: 0.0572824	total: 2.35s	remaining: 6.68s
260:	learn: 0.0572142	total: 2.36s	remaining: 6.67s
261:	learn: 0.0571776	total: 2.36s	remaining: 6.66s
262:	learn: 0.0571429	total: 2.37s	remaining: 6.65s
263:	learn: 0.0571177	total: 2.38s	remaining: 6.64s
264:	learn: 0.0570846	total: 2.39s	remaining: 6.63s
265:	learn: 0.0570742	total: 2.4s	remaining: 6.63s
266:	learn: 0.0570671	total: 2.41s	remaining: 6.62s
267:	learn: 0.0570404	total: 2.42s	remaining: 6.61s
268:	learn: 0.0569815	total: 2.43s	remaining: 6.6s
269:	learn: 0.0569469	total: 2.44s	remaining: 6.59s
270:	learn: 0.0569022	total: 2.45s	remaining: 6.59s
271:	learn: 0.0568461	total: 2.46s	remaining: 6.58s
272:	learn: 0.0568286	total: 2.47s	remaining: 6.57s
273:	learn: 0.0568004	total: 2.48s	remaining: 6.56s
274:	learn: 0.0567767	total: 2.48s	remaining: 6.55s
275:	learn: 0.0567647	total: 2.49s	remaining: 6.54s
276:	learn: 0.0567424	total: 2.5s	remaining: 6.54s
277:	learn: 0.0567283	total: 2.51s	remaining: 6.52s
278:	learn: 0.0567032	total: 2.52s	remaining: 6.52s
279:	learn: 0.0566641	total: 2.53s	remaining: 6.51s
280:	learn: 0.0566440	total: 2.54s	remaining: 6.5s
281:	learn: 0.0566227	total: 2.55s	remaining: 6.49s
282:	learn: 0.0565979	total: 2.56s	remaining: 6.47s
283:	learn: 0.0565834	total: 2.56s	remaining: 6.47s
284:	learn: 0.0565341	total: 2.57s	remaining: 6.46s
285:	learn: 0.0564837	total: 2.58s	remaining: 6.45s
286:	learn: 0.0564555	total: 2.59s	remaining: 6.44s
287:	learn: 0.0564478	total: 2.6s	remaining: 6.43s
288:	learn: 0.0564136	total: 2.61s	remaining: 6.42s
289:	learn: 0.0563902	total: 2.62s	remaining: 6.41s
290:	learn: 0.0563724	total: 2.63s	remaining: 6.4s
291:	learn: 0.0563419	total: 2.64s	remaining: 6.39s
292:	learn: 0.0563257	total: 2.65s	remaining: 6.38s
293:	learn: 0.0562855	total: 2.65s	remaining: 6.38s
294:	learn: 0.0562744	total: 2.66s	remaining: 6.37s
295:	learn: 0.0562548	total: 2.67s	remaining: 6.36s
296:	learn: 0.0562031	total: 2.68s	remaining: 6.35s
297:	learn: 0.0561899	total: 2.69s	remaining: 6.34s
298:	learn: 0.0561775	total: 2.7s	remaining: 6.33s
299:	learn: 0.0561401	total: 2.71s	remaining: 6.32s
300:	learn: 0.0561275	total: 2.72s	remaining: 6.31s
301:	learn: 0.0561202	total: 2.72s	remaining: 6.3s
302:	learn: 0.0560993	total: 2.73s	remaining: 6.29s
303:	learn: 0.0560952	total: 2.74s	remaining: 6.28s
304:	learn: 0.0560697	total: 2.75s	remaining: 6.27s
305:	learn: 0.0560609	total: 2.76s	remaining: 6.26s
306:	learn: 0.0560119	total: 2.77s	remaining: 6.25s
307:	learn: 0.0559874	total: 2.77s	remaining: 6.24s
308:	learn: 0.0559410	total: 2.78s	remaining: 6.23s
309:	learn: 0.0559275	total: 2.79s	remaining: 6.22s
310:	learn: 0.0559114	total: 2.8s	remaining: 6.21s
311:	learn: 0.0559012	total: 2.81s	remaining: 6.2s
312:	learn: 0.0558764	total: 2.82s	remaining: 6.19s
313:	learn: 0.0558646	total: 2.83s	remaining: 6.18s
314:	learn: 0.0558168	total: 2.84s	remaining: 6.17s
315:	learn: 0.0558042	total: 2.85s	remaining: 6.17s
316:	learn: 0.0557745	total: 2.86s	remaining: 6.17s
317:	learn: 0.0557442	total: 2.87s	remaining: 6.16s
318:	learn: 0.0557167	total: 2.88s	remaining: 6.15s
319:	learn: 0.0556875	total: 2.89s	remaining: 6.14s
320:	learn: 0.0556731	total: 2.9s	remaining: 6.13s
321:	learn: 0.0556425	total: 2.91s	remaining: 6.12s
322:	learn: 0.0556171	total: 2.92s	remaining: 6.11s
323:	learn: 0.0556038	total: 2.92s	remaining: 6.1s
324:	learn: 0.0555904	total: 2.93s	remaining: 6.09s
325:	learn: 0.0555773	total: 2.94s	remaining: 6.08s
326:	learn: 0.0555634	total: 2.95s	remaining: 6.08s
327:	learn: 0.0555544	total: 2.96s	remaining: 6.07s
328:	learn: 0.0555392	total: 2.97s	remaining: 6.06s
329:	learn: 0.0555209	total: 2.98s	remaining: 6.05s
330:	learn: 0.0554986	total: 2.99s	remaining: 6.04s
331:	learn: 0.0554875	total: 3s	remaining: 6.03s
332:	learn: 0.0554594	total: 3.01s	remaining: 6.02s
333:	learn: 0.0554279	total: 3.02s	remaining: 6.02s
334:	learn: 0.0554136	total: 3.03s	remaining: 6.01s
335:	learn: 0.0553972	total: 3.04s	remaining: 6s
336:	learn: 0.0553816	total: 3.05s	remaining: 6s
337:	learn: 0.0553610	total: 3.06s	remaining: 5.99s
338:	learn: 0.0553324	total: 3.07s	remaining: 5.98s
339:	learn: 0.0553168	total: 3.08s	remaining: 5.97s
340:	learn: 0.0553013	total: 3.08s	remaining: 5.96s
341:	learn: 0.0552630	total: 3.09s	remaining: 5.95s
342:	learn: 0.0552459	total: 3.1s	remaining: 5.94s
343:	learn: 0.0552395	total: 3.11s	remaining: 5.93s
344:	learn: 0.0552060	total: 3.12s	remaining: 5.92s
345:	learn: 0.0551682	total: 3.13s	remaining: 5.91s
346:	learn: 0.0551529	total: 3.14s	remaining: 5.9s
347:	learn: 0.0551267	total: 3.15s	remaining: 5.89s
348:	learn: 0.0551152	total: 3.15s	remaining: 5.88s
349:	learn: 0.0550822	total: 3.16s	remaining: 5.88s
350:	learn: 0.0550688	total: 3.17s	remaining: 5.86s
351:	learn: 0.0550286	total: 3.18s	remaining: 5.85s
352:	learn: 0.0550161	total: 3.19s	remaining: 5.84s
353:	learn: 0.0549741	total: 3.2s	remaining: 5.83s
354:	learn: 0.0549267	total: 3.21s	remaining: 5.83s
355:	learn: 0.0548894	total: 3.21s	remaining: 5.82s
356:	learn: 0.0548683	total: 3.23s	remaining: 5.81s
357:	learn: 0.0548498	total: 3.23s	remaining: 5.8s
358:	learn: 0.0548347	total: 3.24s	remaining: 5.79s
359:	learn: 0.0548187	total: 3.25s	remaining: 5.78s
360:	learn: 0.0547875	total: 3.26s	remaining: 5.78s
361:	learn: 0.0547729	total: 3.27s	remaining: 5.77s
362:	learn: 0.0547478	total: 3.28s	remaining: 5.76s
363:	learn: 0.0547303	total: 3.29s	remaining: 5.75s
364:	learn: 0.0547058	total: 3.3s	remaining: 5.74s
365:	learn: 0.0546788	total: 3.31s	remaining: 5.73s
366:	learn: 0.0546646	total: 3.32s	remaining: 5.72s
367:	learn: 0.0546559	total: 3.33s	remaining: 5.71s
368:	learn: 0.0546449	total: 3.33s	remaining: 5.7s
369:	learn: 0.0546300	total: 3.34s	remaining: 5.69s
370:	learn: 0.0546190	total: 3.35s	remaining: 5.68s
371:	learn: 0.0546066	total: 3.36s	remaining: 5.67s
372:	learn: 0.0545703	total: 3.37s	remaining: 5.66s
373:	learn: 0.0545513	total: 3.38s	remaining: 5.66s
374:	learn: 0.0545480	total: 3.39s	remaining: 5.65s
375:	learn: 0.0545274	total: 3.4s	remaining: 5.64s
376:	learn: 0.0545004	total: 3.41s	remaining: 5.63s
377:	learn: 0.0544846	total: 3.42s	remaining: 5.63s
378:	learn: 0.0544714	total: 3.43s	remaining: 5.62s
379:	learn: 0.0544586	total: 3.44s	remaining: 5.61s
380:	learn: 0.0544410	total: 3.45s	remaining: 5.6s
381:	learn: 0.0544139	total: 3.46s	remaining: 5.6s
382:	learn: 0.0543849	total: 3.47s	remaining: 5.59s
383:	learn: 0.0543539	total: 3.48s	remaining: 5.58s
384:	learn: 0.0543121	total: 3.49s	remaining: 5.57s
385:	learn: 0.0542674	total: 3.5s	remaining: 5.57s
386:	learn: 0.0542502	total: 3.51s	remaining: 5.56s

In [7]:
y_preds_base = base_cb.predict(X_test)
balanced_accuracy_score(y_test, y_preds_base)

0.9605813522518641

## finetuning

In [8]:
def objective(trial):
    iterations = trial.suggest_int("iterations", 400, 1_000)
    learning_rate = trial.suggest_float("learning_rate", 0.02, 0.09)
    l2_leaf_reg = trial.suggest_float("l2_leaf_reg", 3, 4)
    bootstrap_type = trial.suggest_categorical("bootstrap_type", ["Bernoulli"])
    max_depth = trial.suggest_int("max_depth", 1, 16) # can only go up to 16 with gpu

    cb_optuna = CatBoostClassifier(
        random_seed=SEED,
        task_type="GPU",
        cat_features=cat_indices,
        iterations=iterations,
        learning_rate=learning_rate,
        l2_leaf_reg=l2_leaf_reg,
        bootstrap_type=bootstrap_type,
        max_depth=max_depth,
    )

    try:
        cb_optuna.fit(X_train, y_train)
        y_preds = cb_optuna.predict(X_test)
        score = balanced_accuracy_score(y_test, y_preds)
    finally:
        del cb_optuna
        gc.collect()

    return score

In [9]:
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=5)

[I 2026-04-16 17:37:09,048] A new study created in memory with name: no-name-13a67fef-6ec7-4d8a-b51b-7ccf1786fd9a

0:	learn: 1.0302626	total: 7.33ms	remaining: 3.37s
1:	learn: 0.9727181	total: 12.7ms	remaining: 2.91s
2:	learn: 0.9242421	total: 17.8ms	remaining: 2.71s
3:	learn: 0.8821757	total: 22.4ms	remaining: 2.56s
4:	learn: 0.8453204	total: 27.1ms	remaining: 2.47s
5:	learn: 0.8131637	total: 31.6ms	remaining: 2.39s
6:	learn: 0.7844608	total: 37.3ms	remaining: 2.41s
7:	learn: 0.7417585	total: 42.2ms	remaining: 2.38s
8:	learn: 0.7046870	total: 47ms	remaining: 2.35s
9:	learn: 0.6722373	total: 51.8ms	remaining: 2.33s
10:	learn: 0.6439020	total: 57.2ms	remaining: 2.33s
11:	learn: 0.6181560	total: 62.2ms	remaining: 2.32s
12:	learn: 0.5960448	total: 68.1ms	remaining: 2.34s
13:	learn: 0.5762307	total: 73.5ms	remaining: 2.34s
14:	learn: 0.5579186	total: 78.5ms	remaining: 2.33s
15:	learn: 0.5401247	total: 83.5ms	remaining: 2.32s
16:	learn: 0.5254411	total: 88.3ms	remaining: 2.3s
17:	learn: 0.5120648	total: 93.2ms	remaining: 2.29s
18:	learn: 0.4993215	total: 98.7ms	remaining: 2.29s
19:	learn: 0.4860104	total: 104ms	remaining: 2.29s
20:	learn: 0.4756438	total: 109ms	remaining: 2.27s
21:	learn: 0.4643552	total: 113ms	remaining: 2.25s
22:	learn: 0.4549334	total: 118ms	remaining: 2.24s
23:	learn: 0.4449757	total: 122ms	remaining: 2.23s
24:	learn: 0.4365747	total: 127ms	remaining: 2.21s
25:	learn: 0.4275667	total: 132ms	remaining: 2.2s
26:	learn: 0.4196472	total: 138ms	remaining: 2.21s
27:	learn: 0.4114717	total: 142ms	remaining: 2.19s
28:	learn: 0.4045264	total: 147ms	remaining: 2.19s
29:	learn: 0.3974117	total: 153ms	remaining: 2.19s
30:	learn: 0.3898943	total: 158ms	remaining: 2.19s
31:	learn: 0.3832706	total: 163ms	remaining: 2.18s
32:	learn: 0.3755699	total: 168ms	remaining: 2.17s
33:	learn: 0.3699572	total: 174ms	remaining: 2.17s
34:	learn: 0.3643628	total: 179ms	remaining: 2.18s
35:	learn: 0.3582641	total: 185ms	remaining: 2.18s
36:	learn: 0.3531502	total: 190ms	remaining: 2.18s
37:	learn: 0.3474379	total: 195ms	remaining: 2.17s
38:	learn: 0.3423035	total: 201ms	remaining: 2.17s
39:	learn: 0.3370037	total: 206ms	remaining: 2.16s
40:	learn: 0.3320432	total: 212ms	remaining: 2.16s
41:	learn: 0.3278171	total: 217ms	remaining: 2.16s
42:	learn: 0.3230515	total: 222ms	remaining: 2.15s
43:	learn: 0.3186194	total: 228ms	remaining: 2.16s
44:	learn: 0.3131499	total: 235ms	remaining: 2.16s
45:	learn: 0.3089862	total: 241ms	remaining: 2.17s
46:	learn: 0.3051410	total: 247ms	remaining: 2.17s
47:	learn: 0.3011193	total: 252ms	remaining: 2.16s
48:	learn: 0.2977860	total: 258ms	remaining: 2.16s
49:	learn: 0.2940538	total: 264ms	remaining: 2.17s
50:	learn: 0.2907647	total: 270ms	remaining: 2.16s
51:	learn: 0.2874583	total: 274ms	remaining: 2.15s
52:	learn: 0.2838095	total: 279ms	remaining: 2.14s
53:	learn: 0.2803507	total: 284ms	remaining: 2.13s
54:	learn: 0.2772093	total: 289ms	remaining: 2.13s
55:	learn: 0.2738307	total: 293ms	remaining: 2.12s
56:	learn: 0.2712291	total: 299ms	remaining: 2.11s
57:	learn: 0.2686758	total: 304ms	remaining: 2.1s
58:	learn: 0.2658971	total: 309ms	remaining: 2.1s
59:	learn: 0.2629276	total: 314ms	remaining: 2.09s
60:	learn: 0.2605957	total: 320ms	remaining: 2.09s
61:	learn: 0.2578299	total: 326ms	remaining: 2.09s
62:	learn: 0.2549759	total: 333ms	remaining: 2.1s
63:	learn: 0.2523873	total: 339ms	remaining: 2.09s
64:	learn: 0.2503406	total: 344ms	remaining: 2.09s
65:	learn: 0.2478751	total: 350ms	remaining: 2.09s
66:	learn: 0.2454641	total: 355ms	remaining: 2.08s
67:	learn: 0.2429442	total: 359ms	remaining: 2.07s
68:	learn: 0.2406539	total: 365ms	remaining: 2.07s
69:	learn: 0.2381905	total: 370ms	remaining: 2.06s
70:	learn: 0.2359382	total: 375ms	remaining: 2.06s
71:	learn: 0.2342018	total: 380ms	remaining: 2.05s
72:	learn: 0.2321110	total: 385ms	remaining: 2.04s
73:	learn: 0.2298467	total: 391ms	remaining: 2.04s
74:	learn: 0.2277900	total: 396ms	remaining: 2.04s
75:	learn: 0.2256813	total: 401ms	remaining: 2.03s
76:	learn: 0.2236439	total: 407ms	remaining: 2.02s
77:	learn: 0.2217908	total: 412ms	remaining: 2.02s
78:	learn: 0.2201408	total: 417ms	remaining: 2.01s
79:	learn: 0.2183167	total: 422ms	remaining: 2s
80:	learn: 0.2168863	total: 427ms	remaining: 2s
81:	learn: 0.2151036	total: 432ms	remaining: 1.99s
82:	learn: 0.2133893	total: 437ms	remaining: 1.99s
83:	learn: 0.2119367	total: 442ms	remaining: 1.98s
84:	learn: 0.2102649	total: 447ms	remaining: 1.97s
85:	learn: 0.2086331	total: 452ms	remaining: 1.97s
86:	learn: 0.2069243	total: 457ms	remaining: 1.96s
87:	learn: 0.2053919	total: 462ms	remaining: 1.95s
88:	learn: 0.2040321	total: 467ms	remaining: 1.95s
89:	learn: 0.2025147	total: 472ms	remaining: 1.94s
90:	learn: 0.2009648	total: 477ms	remaining: 1.93s
91:	learn: 0.1995394	total: 482ms	remaining: 1.93s
92:	learn: 0.1983652	total: 486ms	remaining: 1.92s
93:	learn: 0.1968442	total: 492ms	remaining: 1.91s
94:	learn: 0.1957364	total: 497ms	remaining: 1.91s
95:	learn: 0.1943302	total: 502ms	remaining: 1.9s
96:	learn: 0.1931559	total: 507ms	remaining: 1.9s
97:	learn: 0.1917434	total: 512ms	remaining: 1.89s
98:	learn: 0.1905239	total: 517ms	remaining: 1.89s
99:	learn: 0.1892067	total: 522ms	remaining: 1.88s
100:	learn: 0.1878618	total: 528ms	remaining: 1.88s
101:	learn: 0.1866234	total: 533ms	remaining: 1.87s
102:	learn: 0.1856221	total: 538ms	remaining: 1.86s
103:	learn: 0.1843958	total: 543ms	remaining: 1.86s
104:	learn: 0.1831428	total: 548ms	remaining: 1.85s
105:	learn: 0.1819705	total: 554ms	remaining: 1.85s
106:	learn: 0.1808784	total: 560ms	remaining: 1.85s
107:	learn: 0.1797183	total: 565ms	remaining: 1.84s
108:	learn: 0.1787722	total: 569ms	remaining: 1.83s
109:	learn: 0.1775999	total: 575ms	remaining: 1.83s
110:	learn: 0.1765044	total: 581ms	remaining: 1.83s
111:	learn: 0.1756205	total: 586ms	remaining: 1.82s
112:	learn: 0.1745965	total: 591ms	remaining: 1.81s
113:	learn: 0.1736117	total: 596ms	remaining: 1.81s
114:	learn: 0.1725864	total: 601ms	remaining: 1.8s
115:	learn: 0.1717488	total: 606ms	remaining: 1.8s
116:	learn: 0.1706871	total: 611ms	remaining: 1.79s
117:	learn: 0.1697147	total: 615ms	remaining: 1.78s
118:	learn: 0.1689305	total: 620ms	remaining: 1.78s
119:	learn: 0.1680949	total: 626ms	remaining: 1.77s
120:	learn: 0.1671056	total: 631ms	remaining: 1.77s
121:	learn: 0.1661988	total: 636ms	remaining: 1.76s
122:	learn: 0.1654422	total: 641ms	remaining: 1.76s
123:	learn: 0.1645475	total: 646ms	remaining: 1.75s
124:	learn: 0.1636036	total: 651ms	remaining: 1.75s
125:	learn: 0.1626266	total: 657ms	remaining: 1.74s
126:	learn: 0.1619484	total: 663ms	remaining: 1.74s
127:	learn: 0.1610502	total: 669ms	remaining: 1.73s
128:	learn: 0.1602175	total: 673ms	remaining: 1.73s
129:	learn: 0.1593737	total: 679ms	remaining: 1.72s
130:	learn: 0.1586841	total: 685ms	remaining: 1.72s
131:	learn: 0.1578719	total: 690ms	remaining: 1.72s
132:	learn: 0.1572471	total: 697ms	remaining: 1.71s
133:	learn: 0.1564577	total: 702ms	remaining: 1.71s
134:	learn: 0.1557572	total: 708ms	remaining: 1.7s
135:	learn: 0.1549913	total: 713ms	remaining: 1.7s
136:	learn: 0.1544094	total: 718ms	remaining: 1.69s
137:	learn: 0.1535747	total: 724ms	remaining: 1.69s
138:	learn: 0.1528500	total: 729ms	remaining: 1.68s
139:	learn: 0.1521210	total: 733ms	remaining: 1.68s
140:	learn: 0.1514000	total: 738ms	remaining: 1.67s
141:	learn: 0.1508155	total: 743ms	remaining: 1.66s
142:	learn: 0.1501244	total: 748ms	remaining: 1.66s
143:	learn: 0.1494621	total: 753ms	remaining: 1.65s
144:	learn: 0.1487791	total: 758ms	remaining: 1.65s
145:	learn: 0.1482345	total: 763ms	remaining: 1.64s
146:	learn: 0.1474599	total: 768ms	remaining: 1.63s
147:	learn: 0.1468024	total: 772ms	remaining: 1.63s
148:	learn: 0.1462817	total: 777ms	remaining: 1.62s
149:	learn: 0.1457368	total: 782ms	remaining: 1.61s
150:	learn: 0.1450767	total: 788ms	remaining: 1.61s
151:	learn: 0.1445277	total: 793ms	remaining: 1.61s
152:	learn: 0.1439027	total: 798ms	remaining: 1.6s
153:	learn: 0.1433108	total: 803ms	remaining: 1.59s
154:	learn: 0.1426762	total: 808ms	remaining: 1.59s
155:	learn: 0.1422151	total: 812ms	remaining: 1.58s
156:	learn: 0.1416258	total: 817ms	remaining: 1.58s
157:	learn: 0.1410561	total: 823ms	remaining: 1.57s
158:	learn: 0.1404592	total: 827ms	remaining: 1.57s
159:	learn: 0.1400140	total: 832ms	remaining: 1.56s
160:	learn: 0.1394605	total: 837ms	remaining: 1.55s
161:	learn: 0.1388521	total: 842ms	remaining: 1.55s
162:	learn: 0.1384306	total: 847ms	remaining: 1.54s
163:	learn: 0.1378948	total: 852ms	remaining: 1.54s
164:	learn: 0.1373605	total: 858ms	remaining: 1.53s
165:	learn: 0.1368261	total: 863ms	remaining: 1.53s
166:	learn: 0.1363192	total: 868ms	remaining: 1.52s
167:	learn: 0.1357977	total: 873ms	remaining: 1.52s
168:	learn: 0.1353873	total: 877ms	remaining: 1.51s
169:	learn: 0.1348697	total: 882ms	remaining: 1.5s
170:	learn: 0.1343882	total: 887ms	remaining: 1.5s
171:	learn: 0.1338891	total: 892ms	remaining: 1.49s
172:	learn: 0.1334801	total: 897ms	remaining: 1.49s
173:	learn: 0.1331228	total: 902ms	remaining: 1.48s
174:	learn: 0.1326347	total: 907ms	remaining: 1.48s
175:	learn: 0.1320587	total: 911ms	remaining: 1.47s
176:	learn: 0.1317003	total: 916ms	remaining: 1.46s
177:	learn: 0.1311897	total: 921ms	remaining: 1.46s
178:	learn: 0.1307491	total: 926ms	remaining: 1.45s
179:	learn: 0.1302738	total: 931ms	remaining: 1.45s
180:	learn: 0.1298495	total: 936ms	remaining: 1.44s
181:	learn: 0.1293932	total: 941ms	remaining: 1.44s
182:	learn: 0.1290516	total: 945ms	remaining: 1.43s
183:	learn: 0.1286120	total: 950ms	remaining: 1.43s
184:	learn: 0.1281988	total: 955ms	remaining: 1.42s
185:	learn: 0.1277632	total: 960ms	remaining: 1.41s
186:	learn: 0.1274666	total: 965ms	remaining: 1.41s
187:	learn: 0.1270405	total: 970ms	remaining: 1.4s
188:	learn: 0.1266363	total: 975ms	remaining: 1.4s
189:	learn: 0.1262231	total: 980ms	remaining: 1.39s
190:	learn: 0.1259176	total: 985ms	remaining: 1.39s
191:	learn: 0.1254806	total: 990ms	remaining: 1.38s
192:	learn: 0.1250855	total: 995ms	remaining: 1.38s
193:	learn: 0.1247039	total: 1000ms	remaining: 1.37s
194:	learn: 0.1243032	total: 1s	remaining: 1.36s
195:	learn: 0.1239318	total: 1.01s	remaining: 1.36s
196:	learn: 0.1235308	total: 1.01s	remaining: 1.35s
197:	learn: 0.1231865	total: 1.02s	remaining: 1.35s
198:	learn: 0.1228247	total: 1.02s	remaining: 1.34s
199:	learn: 0.1225356	total: 1.03s	remaining: 1.34s
200:	learn: 0.1221462	total: 1.03s	remaining: 1.33s
201:	learn: 0.1217628	total: 1.04s	remaining: 1.33s
202:	learn: 0.1214273	total: 1.04s	remaining: 1.32s
203:	learn: 0.1210321	total: 1.05s	remaining: 1.31s
204:	learn: 0.1206956	total: 1.05s	remaining: 1.31s
205:	learn: 0.1203332	total: 1.06s	remaining: 1.3s
206:	learn: 0.1200152	total: 1.06s	remaining: 1.3s
207:	learn: 0.1196345	total: 1.07s	remaining: 1.29s
208:	learn: 0.1193770	total: 1.07s	remaining: 1.29s
209:	learn: 0.1190317	total: 1.08s	remaining: 1.28s
210:	learn: 0.1187177	total: 1.08s	remaining: 1.28s
211:	learn: 0.1183589	total: 1.09s	remaining: 1.27s
212:	learn: 0.1180453	total: 1.09s	remaining: 1.27s
213:	learn: 0.1177237	total: 1.1s	remaining: 1.26s
214:	learn: 0.1174801	total: 1.1s	remaining: 1.26s
215:	learn: 0.1171388	total: 1.11s	remaining: 1.25s
216:	learn: 0.1168324	total: 1.11s	remaining: 1.25s
217:	learn: 0.1165246	total: 1.12s	remaining: 1.24s
218:	learn: 0.1163133	total: 1.12s	remaining: 1.24s
219:	learn: 0.1159948	total: 1.13s	remaining: 1.23s
220:	learn: 0.1157484	total: 1.13s	remaining: 1.23s
221:	learn: 0.1153236	total: 1.14s	remaining: 1.22s
222:	learn: 0.1150119	total: 1.14s	remaining: 1.22s
223:	learn: 0.1147799	total: 1.15s	remaining: 1.21s
224:	learn: 0.1144532	total: 1.16s	remaining: 1.21s
225:	learn: 0.1141986	total: 1.16s	remaining: 1.2s
226:	learn: 0.1138990	total: 1.17s	remaining: 1.2s
227:	learn: 0.1136282	total: 1.17s	remaining: 1.19s
228:	learn: 0.1133097	total: 1.18s	remaining: 1.19s
229:	learn: 0.1130428	total: 1.19s	remaining: 1.19s
230:	learn: 0.1127589	total: 1.19s	remaining: 1.18s
231:	learn: 0.1125459	total: 1.2s	remaining: 1.18s
232:	learn: 0.1122443	total: 1.2s	remaining: 1.17s
233:	learn: 0.1119831	total: 1.21s	remaining: 1.16s
234:	learn: 0.1117108	total: 1.21s	remaining: 1.16s
235:	learn: 0.1115082	total: 1.22s	remaining: 1.15s
236:	learn: 0.1112200	total: 1.22s	remaining: 1.15s
237:	learn: 0.1109488	total: 1.22s	remaining: 1.14s
238:	learn: 0.1106988	total: 1.23s	remaining: 1.14s
239:	learn: 0.1104351	total: 1.23s	remaining: 1.13s
240:	learn: 0.1101890	total: 1.24s	remaining: 1.13s
241:	learn: 0.1099371	total: 1.25s	remaining: 1.12s
242:	learn: 0.1096880	total: 1.25s	remaining: 1.12s
243:	learn: 0.1094170	total: 1.25s	remaining: 1.11s
244:	learn: 0.1091765	total: 1.26s	remaining: 1.11s
245:	learn: 0.1089314	total: 1.27s	remaining: 1.1s
246:	learn: 0.1087400	total: 1.27s	remaining: 1.09s
247:	learn: 0.1083887	total: 1.27s	remaining: 1.09s
248:	learn: 0.1081622	total: 1.28s	remaining: 1.09s
249:	learn: 0.1078943	total: 1.29s	remaining: 1.08s
250:	learn: 0.1077305	total: 1.29s	remaining: 1.07s
251:	learn: 0.1075011	total: 1.3s	remaining: 1.07s
252:	learn: 0.1072839	total: 1.3s	remaining: 1.06s
253:	learn: 0.1070415	total: 1.3s	remaining: 1.06s
254:	learn: 0.1068755	total: 1.31s	remaining: 1.05s
255:	learn: 0.1066262	total: 1.31s	remaining: 1.05s
256:	learn: 0.1064122	total: 1.32s	remaining: 1.04s
257:	learn: 0.1061798	total: 1.32s	remaining: 1.04s
258:	learn: 0.1060167	total: 1.33s	remaining: 1.03s
259:	learn: 0.1057755	total: 1.33s	remaining: 1.03s
260:	learn: 0.1055369	total: 1.34s	remaining: 1.02s
261:	learn: 0.1053220	total: 1.34s	remaining: 1.02s
262:	learn: 0.1049977	total: 1.35s	remaining: 1.01s
263:	learn: 0.1047612	total: 1.35s	remaining: 1s
264:	learn: 0.1045513	total: 1.36s	remaining: 1s
265:	learn: 0.1043297	total: 1.36s	remaining: 996ms
266:	learn: 0.1041735	total: 1.37s	remaining: 991ms
267:	learn: 0.1039630	total: 1.37s	remaining: 985ms
268:	learn: 0.1037582	total: 1.38s	remaining: 979ms
269:	learn: 0.1035462	total: 1.38s	remaining: 974ms
270:	learn: 0.1033919	total: 1.39s	remaining: 969ms
271:	learn: 0.1032242	total: 1.39s	remaining: 963ms
272:	learn: 0.1030100	total: 1.4s	remaining: 958ms
273:	learn: 0.1028632	total: 1.4s	remaining: 953ms
274:	learn: 0.1026561	total: 1.41s	remaining: 948ms
275:	learn: 0.1024645	total: 1.41s	remaining: 942ms
276:	learn: 0.1022601	total: 1.42s	remaining: 937ms
277:	learn: 0.1021163	total: 1.42s	remaining: 932ms
278:	learn: 0.1019273	total: 1.43s	remaining: 927ms
279:	learn: 0.1017861	total: 1.43s	remaining: 921ms
280:	learn: 0.1015650	total: 1.44s	remaining: 916ms
281:	learn: 0.1013922	total: 1.44s	remaining: 911ms
282:	learn: 0.1012547	total: 1.45s	remaining: 906ms
283:	learn: 0.1010650	total: 1.45s	remaining: 900ms
284:	learn: 0.1008786	total: 1.46s	remaining: 895ms
285:	learn: 0.1005985	total: 1.46s	remaining: 890ms
286:	learn: 0.1004096	total: 1.47s	remaining: 885ms
287:	learn: 0.1002706	total: 1.47s	remaining: 880ms
288:	learn: 0.1001058	total: 1.48s	remaining: 875ms
289:	learn: 0.0999209	total: 1.48s	remaining: 869ms
290:	learn: 0.0997915	total: 1.49s	remaining: 864ms
291:	learn: 0.0996106	total: 1.49s	remaining: 859ms
292:	learn: 0.0994827	total: 1.5s	remaining: 854ms
293:	learn: 0.0992919	total: 1.5s	remaining: 849ms
294:	learn: 0.0991679	total: 1.51s	remaining: 844ms
295:	learn: 0.0989946	total: 1.51s	remaining: 838ms
296:	learn: 0.0988323	total: 1.52s	remaining: 833ms
297:	learn: 0.0986504	total: 1.52s	remaining: 828ms
298:	learn: 0.0985249	total: 1.53s	remaining: 822ms
299:	learn: 0.0983597	total: 1.53s	remaining: 817ms
300:	learn: 0.0982373	total: 1.54s	remaining: 813ms
301:	learn: 0.0979858	total: 1.54s	remaining: 808ms
302:	learn: 0.0976274	total: 1.55s	remaining: 803ms
303:	learn: 0.0973534	total: 1.55s	remaining: 797ms
304:	learn: 0.0971285	total: 1.56s	remaining: 792ms
305:	learn: 0.0969657	total: 1.56s	remaining: 787ms
306:	learn: 0.0968441	total: 1.57s	remaining: 782ms
307:	learn: 0.0966823	total: 1.57s	remaining: 777ms
308:	learn: 0.0965347	total: 1.58s	remaining: 771ms
309:	learn: 0.0963557	total: 1.58s	remaining: 766ms
310:	learn: 0.0962475	total: 1.59s	remaining: 761ms
311:	learn: 0.0960885	total: 1.59s	remaining: 756ms
312:	learn: 0.0959845	total: 1.6s	remaining: 751ms
313:	learn: 0.0958292	total: 1.6s	remaining: 746ms
314:	learn: 0.0956846	total: 1.61s	remaining: 741ms
315:	learn: 0.0955336	total: 1.61s	remaining: 735ms
316:	learn: 0.0954263	total: 1.62s	remaining: 730ms
317:	learn: 0.0952707	total: 1.62s	remaining: 725ms
318:	learn: 0.0951236	total: 1.63s	remaining: 720ms
319:	learn: 0.0949931	total: 1.64s	remaining: 715ms
320:	learn: 0.0948557	total: 1.64s	remaining: 710ms
321:	learn: 0.0947048	total: 1.65s	remaining: 706ms
322:	learn: 0.0945614	total: 1.65s	remaining: 701ms
323:	learn: 0.0944205	total: 1.66s	remaining: 697ms
324:	learn: 0.0943195	total: 1.66s	remaining: 692ms
325:	learn: 0.0940870	total: 1.67s	remaining: 687ms
326:	learn: 0.0939493	total: 1.68s	remaining: 682ms
327:	learn: 0.0938461	total: 1.68s	remaining: 677ms
328:	learn: 0.0937517	total: 1.69s	remaining: 672ms
329:	learn: 0.0936092	total: 1.69s	remaining: 667ms
330:	learn: 0.0934842	total: 1.7s	remaining: 662ms
331:	learn: 0.0933432	total: 1.7s	remaining: 657ms
332:	learn: 0.0932162	total: 1.71s	remaining: 652ms
333:	learn: 0.0930761	total: 1.72s	remaining: 647ms
334:	learn: 0.0929830	total: 1.72s	remaining: 642ms
335:	learn: 0.0928483	total: 1.73s	remaining: 637ms
336:	learn: 0.0927230	total: 1.73s	remaining: 632ms
337:	learn: 0.0925879	total: 1.74s	remaining: 628ms
338:	learn: 0.0924984	total: 1.74s	remaining: 622ms
339:	learn: 0.0923690	total: 1.75s	remaining: 617ms
340:	learn: 0.0922548	total: 1.75s	remaining: 612ms
341:	learn: 0.0920567	total: 1.76s	remaining: 607ms
342:	learn: 0.0919639	total: 1.77s	remaining: 603ms
343:	learn: 0.0918458	total: 1.77s	remaining: 598ms
344:	learn: 0.0917583	total: 1.78s	remaining: 593ms
345:	learn: 0.0916311	total: 1.78s	remaining: 588ms
346:	learn: 0.0915489	total: 1.79s	remaining: 582ms
347:	learn: 0.0914160	total: 1.79s	remaining: 577ms
348:	learn: 0.0913267	total: 1.8s	remaining: 572ms
349:	learn: 0.0911435	total: 1.8s	remaining: 567ms
350:	learn: 0.0910171	total: 1.81s	remaining: 562ms
351:	learn: 0.0909318	total: 1.81s	remaining: 557ms
352:	learn: 0.0908125	total: 1.82s	remaining: 552ms
353:	learn: 0.0906953	total: 1.83s	remaining: 547ms
354:	learn: 0.0905735	total: 1.83s	remaining: 542ms
355:	learn: 0.0904921	total: 1.84s	remaining: 537ms
356:	learn: 0.0903794	total: 1.84s	remaining: 532ms
357:	learn: 0.0902651	total: 1.85s	remaining: 527ms
358:	learn: 0.0901481	total: 1.85s	remaining: 522ms
359:	learn: 0.0900620	total: 1.86s	remaining: 517ms
360:	learn: 0.0899867	total: 1.87s	remaining: 512ms
361:	learn: 0.0898711	total: 1.87s	remaining: 507ms
362:	learn: 0.0897077	total: 1.88s	remaining: 502ms
363:	learn: 0.0896337	total: 1.88s	remaining: 497ms
364:	learn: 0.0895128	total: 1.89s	remaining: 492ms
365:	learn: 0.0894083	total: 1.9s	remaining: 487ms
366:	learn: 0.0893121	total: 1.9s	remaining: 482ms
367:	learn: 0.0892305	total: 1.91s	remaining: 476ms
368:	learn: 0.0891186	total: 1.91s	remaining: 471ms
369:	learn: 0.0890124	total: 1.92s	remaining: 466ms
370:	learn: 0.0888631	total: 1.92s	remaining: 461ms
371:	learn: 0.0886139	total: 1.93s	remaining: 456ms
372:	learn: 0.0884721	total: 1.93s	remaining: 451ms
373:	learn: 0.0883704	total: 1.94s	remaining: 446ms
374:	learn: 0.0882977	total: 1.94s	remaining: 441ms
375:	learn: 0.0881915	total: 1.95s	remaining: 436ms
376:	learn: 0.0880922	total: 1.96s	remaining: 431ms
377:	learn: 0.0879932	total: 1.96s	remaining: 426ms
378:	learn: 0.0879223	total: 1.97s	remaining: 421ms
379:	learn: 0.0878236	total: 1.97s	remaining: 415ms
380:	learn: 0.0876919	total: 1.98s	remaining: 410ms
381:	learn: 0.0876213	total: 1.98s	remaining: 405ms
382:	learn: 0.0875076	total: 1.99s	remaining: 400ms
383:	learn: 0.0874382	total: 1.99s	remaining: 395ms
384:	learn: 0.0873359	total: 2s	remaining: 389ms
385:	learn: 0.0872707	total: 2s	remaining: 384ms
386:	learn: 0.0871667	total: 2.01s	remaining: 379ms

[I 2026-04-16 17:37:14,090] Trial 0 finished with value: 0.9579421778839013 and parameters: {'iterations': 460, 'learning_rate': 0.07595143939489676, 'l2_leaf_reg': 3.1113289161102196, 'bootstrap_type': 'Bernoulli', 'max_depth': 2}. Best is trial 0 with value: 0.9579421778839013.

0:	learn: 1.0818736	total: 6.66ms	remaining: 3.28s
1:	learn: 1.0659404	total: 12.4ms	remaining: 3.04s
2:	learn: 1.0507607	total: 17.9ms	remaining: 2.92s
3:	learn: 1.0362805	total: 23.4ms	remaining: 2.87s
4:	learn: 1.0224555	total: 29.6ms	remaining: 2.89s
5:	learn: 1.0092439	total: 34.9ms	remaining: 2.83s
6:	learn: 0.9966069	total: 40.4ms	remaining: 2.8s
7:	learn: 0.9845114	total: 45.7ms	remaining: 2.77s
8:	learn: 0.9729230	total: 51.7ms	remaining: 2.78s
9:	learn: 0.9618124	total: 57.4ms	remaining: 2.77s
10:	learn: 0.9511558	total: 64.3ms	remaining: 2.82s
11:	learn: 0.9409249	total: 69.8ms	remaining: 2.8s
12:	learn: 0.9310997	total: 77.1ms	remaining: 2.85s
13:	learn: 0.9216552	total: 81.6ms	remaining: 2.79s
14:	learn: 0.9125751	total: 88.6ms	remaining: 2.82s
15:	learn: 0.9038376	total: 94.5ms	remaining: 2.82s
16:	learn: 0.8954270	total: 100ms	remaining: 2.81s
17:	learn: 0.8873275	total: 107ms	remaining: 2.82s
18:	learn: 0.8795250	total: 113ms	remaining: 2.81s
19:	learn: 0.8720024	total: 118ms	remaining: 2.79s
20:	learn: 0.8647493	total: 124ms	remaining: 2.79s
21:	learn: 0.8577531	total: 130ms	remaining: 2.79s
22:	learn: 0.8510003	total: 136ms	remaining: 2.79s
23:	learn: 0.8401739	total: 142ms	remaining: 2.78s
24:	learn: 0.8298067	total: 149ms	remaining: 2.78s
25:	learn: 0.8198711	total: 154ms	remaining: 2.77s
26:	learn: 0.8103442	total: 161ms	remaining: 2.77s
27:	learn: 0.8012030	total: 167ms	remaining: 2.77s
28:	learn: 0.7924285	total: 173ms	remaining: 2.77s
29:	learn: 0.7840015	total: 180ms	remaining: 2.77s
30:	learn: 0.7759040	total: 185ms	remaining: 2.75s
31:	learn: 0.7681218	total: 190ms	remaining: 2.73s
32:	learn: 0.7606368	total: 195ms	remaining: 2.71s
33:	learn: 0.7534377	total: 200ms	remaining: 2.7s
34:	learn: 0.7465080	total: 205ms	remaining: 2.68s
35:	learn: 0.7398371	total: 211ms	remaining: 2.67s
36:	learn: 0.7334130	total: 217ms	remaining: 2.67s
37:	learn: 0.7272248	total: 222ms	remaining: 2.66s
38:	learn: 0.7212611	total: 227ms	remaining: 2.64s
39:	learn: 0.7155131	total: 233ms	remaining: 2.63s
40:	learn: 0.7099703	total: 238ms	remaining: 2.62s
41:	learn: 0.7046251	total: 243ms	remaining: 2.61s
42:	learn: 0.6994683	total: 249ms	remaining: 2.6s
43:	learn: 0.6944917	total: 254ms	remaining: 2.59s
44:	learn: 0.6896903	total: 260ms	remaining: 2.58s
45:	learn: 0.6850536	total: 265ms	remaining: 2.57s
46:	learn: 0.6805778	total: 271ms	remaining: 2.57s
47:	learn: 0.6762535	total: 276ms	remaining: 2.56s
48:	learn: 0.6720776	total: 282ms	remaining: 2.55s
49:	learn: 0.6680424	total: 287ms	remaining: 2.55s
50:	learn: 0.6641443	total: 293ms	remaining: 2.54s
51:	learn: 0.6603760	total: 298ms	remaining: 2.53s
52:	learn: 0.6565339	total: 303ms	remaining: 2.52s
53:	learn: 0.6529401	total: 309ms	remaining: 2.51s
54:	learn: 0.6492660	total: 314ms	remaining: 2.5s
55:	learn: 0.6458375	total: 319ms	remaining: 2.49s
56:	learn: 0.6423206	total: 323ms	remaining: 2.47s
57:	learn: 0.6390482	total: 328ms	remaining: 2.46s
58:	learn: 0.6356814	total: 333ms	remaining: 2.45s
59:	learn: 0.6325547	total: 338ms	remaining: 2.44s
60:	learn: 0.6293302	total: 342ms	remaining: 2.42s
61:	learn: 0.6263439	total: 346ms	remaining: 2.41s
62:	learn: 0.6232526	total: 351ms	remaining: 2.4s
63:	learn: 0.6203976	total: 356ms	remaining: 2.38s
64:	learn: 0.6173958	total: 360ms	remaining: 2.37s
65:	learn: 0.6144396	total: 365ms	remaining: 2.36s
66:	learn: 0.6115506	total: 369ms	remaining: 2.35s
67:	learn: 0.6087285	total: 374ms	remaining: 2.33s
68:	learn: 0.6059466	total: 378ms	remaining: 2.32s
69:	learn: 0.6033666	total: 383ms	remaining: 2.31s
70:	learn: 0.6006607	total: 387ms	remaining: 2.3s
71:	learn: 0.5980352	total: 392ms	remaining: 2.29s
72:	learn: 0.5954449	total: 396ms	remaining: 2.28s
73:	learn: 0.5930379	total: 404ms	remaining: 2.29s
74:	learn: 0.5905637	total: 409ms	remaining: 2.28s
75:	learn: 0.5881214	total: 414ms	remaining: 2.27s
76:	learn: 0.5856344	total: 419ms	remaining: 2.26s
77:	learn: 0.5833845	total: 424ms	remaining: 2.26s
78:	learn: 0.5810745	total: 429ms	remaining: 2.25s
79:	learn: 0.5787926	total: 435ms	remaining: 2.24s
80:	learn: 0.5764466	total: 440ms	remaining: 2.24s
81:	learn: 0.5743383	total: 445ms	remaining: 2.23s
82:	learn: 0.5721777	total: 451ms	remaining: 2.23s
83:	learn: 0.5700418	total: 456ms	remaining: 2.22s
84:	learn: 0.5678216	total: 462ms	remaining: 2.22s
85:	learn: 0.5658412	total: 467ms	remaining: 2.21s
86:	learn: 0.5638172	total: 472ms	remaining: 2.2s
87:	learn: 0.5618130	total: 478ms	remaining: 2.2s
88:	learn: 0.5597074	total: 483ms	remaining: 2.19s
89:	learn: 0.5578445	total: 488ms	remaining: 2.19s
90:	learn: 0.5559426	total: 494ms	remaining: 2.18s
91:	learn: 0.5540580	total: 500ms	remaining: 2.18s
92:	learn: 0.5520559	total: 505ms	remaining: 2.17s
93:	learn: 0.5502977	total: 511ms	remaining: 2.17s
94:	learn: 0.5483705	total: 517ms	remaining: 2.16s
95:	learn: 0.5465973	total: 522ms	remaining: 2.16s
96:	learn: 0.5448372	total: 528ms	remaining: 2.16s
97:	learn: 0.5429432	total: 534ms	remaining: 2.15s
98:	learn: 0.5412964	total: 539ms	remaining: 2.14s
99:	learn: 0.5394791	total: 544ms	remaining: 2.14s
100:	learn: 0.5378204	total: 550ms	remaining: 2.13s
101:	learn: 0.5361708	total: 555ms	remaining: 2.13s
102:	learn: 0.5344346	total: 561ms	remaining: 2.12s
103:	learn: 0.5328912	total: 566ms	remaining: 2.12s
104:	learn: 0.5311078	total: 571ms	remaining: 2.11s
105:	learn: 0.5295512	total: 577ms	remaining: 2.1s
106:	learn: 0.5279991	total: 582ms	remaining: 2.1s
107:	learn: 0.5263543	total: 588ms	remaining: 2.09s
108:	learn: 0.5248962	total: 593ms	remaining: 2.09s
109:	learn: 0.5231942	total: 599ms	remaining: 2.08s
110:	learn: 0.5217282	total: 604ms	remaining: 2.08s
111:	learn: 0.5202644	total: 609ms	remaining: 2.07s
112:	learn: 0.5186996	total: 615ms	remaining: 2.07s
113:	learn: 0.5173175	total: 621ms	remaining: 2.06s
114:	learn: 0.5156874	total: 626ms	remaining: 2.06s
115:	learn: 0.5143019	total: 631ms	remaining: 2.05s
116:	learn: 0.5129173	total: 637ms	remaining: 2.05s
117:	learn: 0.5114396	total: 642ms	remaining: 2.04s
118:	learn: 0.5101246	total: 647ms	remaining: 2.03s
119:	learn: 0.5085583	total: 652ms	remaining: 2.03s
120:	learn: 0.5072458	total: 658ms	remaining: 2.02s
121:	learn: 0.5059313	total: 664ms	remaining: 2.02s
122:	learn: 0.5045020	total: 669ms	remaining: 2.01s
123:	learn: 0.5032462	total: 675ms	remaining: 2.01s
124:	learn: 0.5017384	total: 680ms	remaining: 2s
125:	learn: 0.5004913	total: 685ms	remaining: 2s
126:	learn: 0.4992388	total: 690ms	remaining: 1.99s
127:	learn: 0.4980329	total: 695ms	remaining: 1.98s
128:	learn: 0.4966626	total: 700ms	remaining: 1.98s
129:	learn: 0.4952065	total: 706ms	remaining: 1.97s
130:	learn: 0.4940175	total: 711ms	remaining: 1.96s
131:	learn: 0.4928221	total: 716ms	remaining: 1.96s
132:	learn: 0.4916645	total: 721ms	remaining: 1.95s
133:	learn: 0.4903633	total: 725ms	remaining: 1.94s
134:	learn: 0.4889539	total: 731ms	remaining: 1.94s
135:	learn: 0.4878190	total: 736ms	remaining: 1.93s
136:	learn: 0.4866750	total: 742ms	remaining: 1.93s
137:	learn: 0.4855599	total: 747ms	remaining: 1.92s
138:	learn: 0.4842890	total: 752ms	remaining: 1.92s
139:	learn: 0.4829220	total: 757ms	remaining: 1.91s
140:	learn: 0.4818350	total: 763ms	remaining: 1.9s
141:	learn: 0.4807380	total: 768ms	remaining: 1.9s
142:	learn: 0.4796617	total: 774ms	remaining: 1.89s
143:	learn: 0.4784338	total: 779ms	remaining: 1.89s
144:	learn: 0.4771068	total: 784ms	remaining: 1.88s
145:	learn: 0.4760637	total: 790ms	remaining: 1.88s
146:	learn: 0.4750083	total: 795ms	remaining: 1.87s
147:	learn: 0.4739663	total: 801ms	remaining: 1.87s
148:	learn: 0.4727984	total: 806ms	remaining: 1.86s
149:	learn: 0.4715072	total: 812ms	remaining: 1.85s
150:	learn: 0.4705044	total: 817ms	remaining: 1.85s
151:	learn: 0.4694928	total: 823ms	remaining: 1.85s
152:	learn: 0.4684767	total: 829ms	remaining: 1.84s
153:	learn: 0.4672168	total: 834ms	remaining: 1.83s
154:	learn: 0.4660646	total: 839ms	remaining: 1.83s
155:	learn: 0.4650829	total: 845ms	remaining: 1.82s
156:	learn: 0.4641162	total: 850ms	remaining: 1.82s
157:	learn: 0.4631336	total: 856ms	remaining: 1.81s
158:	learn: 0.4619061	total: 862ms	remaining: 1.81s
159:	learn: 0.4607888	total: 867ms	remaining: 1.8s
160:	learn: 0.4598342	total: 872ms	remaining: 1.8s
161:	learn: 0.4589001	total: 878ms	remaining: 1.79s
162:	learn: 0.4579513	total: 883ms	remaining: 1.79s
163:	learn: 0.4567536	total: 889ms	remaining: 1.78s
164:	learn: 0.4556898	total: 894ms	remaining: 1.78s
165:	learn: 0.4547588	total: 900ms	remaining: 1.77s
166:	learn: 0.4538567	total: 906ms	remaining: 1.77s
167:	learn: 0.4529377	total: 911ms	remaining: 1.76s
168:	learn: 0.4517686	total: 917ms	remaining: 1.76s
169:	learn: 0.4508610	total: 922ms	remaining: 1.75s
170:	learn: 0.4498020	total: 927ms	remaining: 1.75s
171:	learn: 0.4489289	total: 933ms	remaining: 1.74s
172:	learn: 0.4480391	total: 938ms	remaining: 1.74s
173:	learn: 0.4468953	total: 943ms	remaining: 1.73s
174:	learn: 0.4460093	total: 948ms	remaining: 1.72s
175:	learn: 0.4449807	total: 953ms	remaining: 1.72s
176:	learn: 0.4441346	total: 958ms	remaining: 1.71s
177:	learn: 0.4430179	total: 963ms	remaining: 1.7s
178:	learn: 0.4421520	total: 968ms	remaining: 1.7s
179:	learn: 0.4412851	total: 972ms	remaining: 1.69s
180:	learn: 0.4403059	total: 976ms	remaining: 1.68s
181:	learn: 0.4392151	total: 981ms	remaining: 1.68s
182:	learn: 0.4383919	total: 986ms	remaining: 1.67s
183:	learn: 0.4375445	total: 991ms	remaining: 1.66s
184:	learn: 0.4367013	total: 995ms	remaining: 1.66s
185:	learn: 0.4357258	total: 1000ms	remaining: 1.65s
186:	learn: 0.4346583	total: 1s	remaining: 1.64s
187:	learn: 0.4338299	total: 1.01s	remaining: 1.64s
188:	learn: 0.4330279	total: 1.01s	remaining: 1.63s
189:	learn: 0.4322077	total: 1.02s	remaining: 1.62s
190:	learn: 0.4312588	total: 1.02s	remaining: 1.61s
191:	learn: 0.4302130	total: 1.02s	remaining: 1.61s
192:	learn: 0.4294005	total: 1.03s	remaining: 1.6s
193:	learn: 0.4286218	total: 1.03s	remaining: 1.59s
194:	learn: 0.4278242	total: 1.04s	remaining: 1.59s
195:	learn: 0.4268011	total: 1.04s	remaining: 1.58s
196:	learn: 0.4260048	total: 1.05s	remaining: 1.58s
197:	learn: 0.4250968	total: 1.06s	remaining: 1.57s
198:	learn: 0.4243393	total: 1.06s	remaining: 1.57s
199:	learn: 0.4235640	total: 1.07s	remaining: 1.56s
200:	learn: 0.4225600	total: 1.07s	remaining: 1.56s
201:	learn: 0.4217791	total: 1.08s	remaining: 1.55s
202:	learn: 0.4208712	total: 1.08s	remaining: 1.54s
203:	learn: 0.4201347	total: 1.09s	remaining: 1.54s
204:	learn: 0.4193800	total: 1.09s	remaining: 1.53s
205:	learn: 0.4184220	total: 1.1s	remaining: 1.53s
206:	learn: 0.4176551	total: 1.1s	remaining: 1.52s
207:	learn: 0.4167700	total: 1.11s	remaining: 1.52s
208:	learn: 0.4160534	total: 1.11s	remaining: 1.51s
209:	learn: 0.4150899	total: 1.12s	remaining: 1.51s
210:	learn: 0.4143378	total: 1.12s	remaining: 1.5s
211:	learn: 0.4135970	total: 1.13s	remaining: 1.5s
212:	learn: 0.4127578	total: 1.14s	remaining: 1.5s
213:	learn: 0.4118154	total: 1.14s	remaining: 1.49s
214:	learn: 0.4110768	total: 1.15s	remaining: 1.48s
215:	learn: 0.4103732	total: 1.15s	remaining: 1.48s
216:	learn: 0.4096502	total: 1.16s	remaining: 1.47s
217:	learn: 0.4088090	total: 1.16s	remaining: 1.47s
218:	learn: 0.4079111	total: 1.17s	remaining: 1.46s
219:	learn: 0.4071855	total: 1.17s	remaining: 1.46s
220:	learn: 0.4064998	total: 1.18s	remaining: 1.45s
221:	learn: 0.4057961	total: 1.18s	remaining: 1.44s
222:	learn: 0.4048887	total: 1.19s	remaining: 1.44s
223:	learn: 0.4041765	total: 1.19s	remaining: 1.43s
224:	learn: 0.4033494	total: 1.2s	remaining: 1.42s
225:	learn: 0.4026821	total: 1.2s	remaining: 1.42s
226:	learn: 0.4019954	total: 1.21s	remaining: 1.41s
227:	learn: 0.4011052	total: 1.21s	remaining: 1.41s
228:	learn: 0.4004032	total: 1.22s	remaining: 1.4s
229:	learn: 0.3995978	total: 1.22s	remaining: 1.39s
230:	learn: 0.3989466	total: 1.23s	remaining: 1.39s
231:	learn: 0.3982657	total: 1.23s	remaining: 1.39s
232:	learn: 0.3973858	total: 1.24s	remaining: 1.38s
233:	learn: 0.3967104	total: 1.24s	remaining: 1.38s
234:	learn: 0.3959477	total: 1.25s	remaining: 1.37s
235:	learn: 0.3952788	total: 1.25s	remaining: 1.36s
236:	learn: 0.3944444	total: 1.26s	remaining: 1.36s
237:	learn: 0.3938048	total: 1.26s	remaining: 1.35s
238:	learn: 0.3931461	total: 1.27s	remaining: 1.35s
239:	learn: 0.3923786	total: 1.27s	remaining: 1.34s
240:	learn: 0.3917192	total: 1.28s	remaining: 1.34s
241:	learn: 0.3908721	total: 1.28s	remaining: 1.33s
242:	learn: 0.3902475	total: 1.29s	remaining: 1.33s
243:	learn: 0.3896057	total: 1.29s	remaining: 1.32s
244:	learn: 0.3889574	total: 1.3s	remaining: 1.32s
245:	learn: 0.3881267	total: 1.31s	remaining: 1.31s
246:	learn: 0.3873725	total: 1.31s	remaining: 1.31s
247:	learn: 0.3867640	total: 1.32s	remaining: 1.3s
248:	learn: 0.3861367	total: 1.32s	remaining: 1.3s
249:	learn: 0.3854981	total: 1.33s	remaining: 1.29s
250:	learn: 0.3846821	total: 1.33s	remaining: 1.29s
251:	learn: 0.3839702	total: 1.34s	remaining: 1.28s
252:	learn: 0.3833767	total: 1.34s	remaining: 1.27s
253:	learn: 0.3827487	total: 1.35s	remaining: 1.27s
254:	learn: 0.3819763	total: 1.35s	remaining: 1.26s
255:	learn: 0.3813583	total: 1.36s	remaining: 1.26s
256:	learn: 0.3806402	total: 1.37s	remaining: 1.25s
257:	learn: 0.3800231	total: 1.37s	remaining: 1.25s
258:	learn: 0.3792380	total: 1.38s	remaining: 1.25s
259:	learn: 0.3786526	total: 1.38s	remaining: 1.24s
260:	learn: 0.3780500	total: 1.39s	remaining: 1.23s
261:	learn: 0.3773492	total: 1.39s	remaining: 1.23s
262:	learn: 0.3767403	total: 1.4s	remaining: 1.22s
263:	learn: 0.3759683	total: 1.41s	remaining: 1.22s
264:	learn: 0.3753978	total: 1.41s	remaining: 1.21s
265:	learn: 0.3748094	total: 1.42s	remaining: 1.21s
266:	learn: 0.3742104	total: 1.42s	remaining: 1.2s
267:	learn: 0.3734807	total: 1.43s	remaining: 1.2s
268:	learn: 0.3728149	total: 1.43s	remaining: 1.19s
269:	learn: 0.3715921	total: 1.44s	remaining: 1.19s
270:	learn: 0.3710354	total: 1.44s	remaining: 1.18s
271:	learn: 0.3704463	total: 1.45s	remaining: 1.18s
272:	learn: 0.3698698	total: 1.45s	remaining: 1.17s
273:	learn: 0.3691264	total: 1.46s	remaining: 1.17s
274:	learn: 0.3684553	total: 1.46s	remaining: 1.16s
275:	learn: 0.3678750	total: 1.47s	remaining: 1.16s
276:	learn: 0.3673289	total: 1.48s	remaining: 1.15s
277:	learn: 0.3666001	total: 1.48s	remaining: 1.15s
278:	learn: 0.3660353	total: 1.49s	remaining: 1.14s
279:	learn: 0.3649595	total: 1.49s	remaining: 1.13s
280:	learn: 0.3643058	total: 1.5s	remaining: 1.13s
281:	learn: 0.3637332	total: 1.5s	remaining: 1.12s
282:	learn: 0.3630472	total: 1.51s	remaining: 1.12s
283:	learn: 0.3625113	total: 1.51s	remaining: 1.11s
284:	learn: 0.3619597	total: 1.52s	remaining: 1.11s
285:	learn: 0.3613968	total: 1.52s	remaining: 1.1s
286:	learn: 0.3607555	total: 1.53s	remaining: 1.1s
287:	learn: 0.3600530	total: 1.53s	remaining: 1.09s
288:	learn: 0.3590959	total: 1.54s	remaining: 1.09s
289:	learn: 0.3585735	total: 1.54s	remaining: 1.08s
290:	learn: 0.3580190	total: 1.55s	remaining: 1.07s
291:	learn: 0.3574783	total: 1.55s	remaining: 1.07s
292:	learn: 0.3567900	total: 1.56s	remaining: 1.06s
293:	learn: 0.3561860	total: 1.56s	remaining: 1.06s
294:	learn: 0.3556404	total: 1.57s	remaining: 1.05s
295:	learn: 0.3551271	total: 1.57s	remaining: 1.05s
296:	learn: 0.3544521	total: 1.58s	remaining: 1.04s
297:	learn: 0.3539218	total: 1.58s	remaining: 1.04s
298:	learn: 0.3533089	total: 1.59s	remaining: 1.03s
299:	learn: 0.3527696	total: 1.59s	remaining: 1.03s
300:	learn: 0.3519105	total: 1.6s	remaining: 1.02s
301:	learn: 0.3514101	total: 1.6s	remaining: 1.01s
302:	learn: 0.3507734	total: 1.61s	remaining: 1.01s
303:	learn: 0.3502557	total: 1.61s	remaining: 1s
304:	learn: 0.3497244	total: 1.62s	remaining: 997ms
305:	learn: 0.3491252	total: 1.62s	remaining: 991ms
306:	learn: 0.3484735	total: 1.63s	remaining: 985ms
307:	learn: 0.3479809	total: 1.63s	remaining: 979ms
308:	learn: 0.3474588	total: 1.64s	remaining: 974ms
309:	learn: 0.3469511	total: 1.64s	remaining: 968ms
310:	learn: 0.3463881	total: 1.65s	remaining: 963ms
311:	learn: 0.3457459	total: 1.65s	remaining: 957ms
312:	learn: 0.3449696	total: 1.65s	remaining: 951ms
313:	learn: 0.3444551	total: 1.66s	remaining: 945ms
314:	learn: 0.3439724	total: 1.66s	remaining: 940ms
315:	learn: 0.3434764	total: 1.67s	remaining: 935ms
316:	learn: 0.3428466	total: 1.67s	remaining: 929ms
317:	learn: 0.3422734	total: 1.68s	remaining: 924ms
318:	learn: 0.3417640	total: 1.68s	remaining: 919ms
319:	learn: 0.3412923	total: 1.69s	remaining: 913ms
320:	learn: 0.3406999	total: 1.69s	remaining: 908ms
321:	learn: 0.3402141	total: 1.7s	remaining: 903ms
322:	learn: 0.3397127	total: 1.71s	remaining: 897ms
323:	learn: 0.3391502	total: 1.71s	remaining: 892ms
324:	learn: 0.3384408	total: 1.71s	remaining: 886ms
325:	learn: 0.3378337	total: 1.72s	remaining: 882ms
326:	learn: 0.3373702	total: 1.73s	remaining: 877ms
327:	learn: 0.3368764	total: 1.73s	remaining: 872ms
328:	learn: 0.3363988	total: 1.74s	remaining: 867ms
329:	learn: 0.3358723	total: 1.74s	remaining: 862ms
330:	learn: 0.3352742	total: 1.75s	remaining: 856ms
331:	learn: 0.3347871	total: 1.75s	remaining: 851ms
332:	learn: 0.3343317	total: 1.76s	remaining: 845ms
333:	learn: 0.3338661	total: 1.76s	remaining: 840ms
334:	learn: 0.3333038	total: 1.77s	remaining: 835ms
335:	learn: 0.3327661	total: 1.77s	remaining: 829ms
336:	learn: 0.3322843	total: 1.78s	remaining: 824ms
337:	learn: 0.3316331	total: 1.78s	remaining: 819ms
338:	learn: 0.3311887	total: 1.79s	remaining: 813ms
339:	learn: 0.3306110	total: 1.79s	remaining: 807ms
340:	learn: 0.3301521	total: 1.8s	remaining: 802ms
341:	learn: 0.3296778	total: 1.8s	remaining: 796ms
342:	learn: 0.3291505	total: 1.81s	remaining: 790ms
343:	learn: 0.3285829	total: 1.81s	remaining: 784ms
344:	learn: 0.3281453	total: 1.81s	remaining: 779ms
345:	learn: 0.3276777	total: 1.82s	remaining: 773ms
346:	learn: 0.3272277	total: 1.82s	remaining: 768ms
347:	learn: 0.3267339	total: 1.83s	remaining: 762ms
348:	learn: 0.3261311	total: 1.83s	remaining: 757ms
349:	learn: 0.3255982	total: 1.84s	remaining: 751ms
350:	learn: 0.3251370	total: 1.84s	remaining: 745ms
351:	learn: 0.3247079	total: 1.85s	remaining: 740ms
352:	learn: 0.3242694	total: 1.85s	remaining: 734ms
353:	learn: 0.3237185	total: 1.85s	remaining: 728ms
354:	learn: 0.3232139	total: 1.86s	remaining: 723ms
355:	learn: 0.3227572	total: 1.86s	remaining: 717ms
356:	learn: 0.3223374	total: 1.87s	remaining: 713ms
357:	learn: 0.3217956	total: 1.88s	remaining: 707ms
358:	learn: 0.3213479	total: 1.88s	remaining: 702ms
359:	learn: 0.3209133	total: 1.89s	remaining: 697ms
360:	learn: 0.3204177	total: 1.89s	remaining: 692ms
361:	learn: 0.3198583	total: 1.9s	remaining: 686ms
362:	learn: 0.3194480	total: 1.9s	remaining: 681ms
363:	learn: 0.3189145	total: 1.91s	remaining: 676ms
364:	learn: 0.3184705	total: 1.91s	remaining: 671ms
365:	learn: 0.3180476	total: 1.92s	remaining: 665ms
366:	learn: 0.3175640	total: 1.92s	remaining: 660ms
367:	learn: 0.3170652	total: 1.93s	remaining: 655ms
368:	learn: 0.3166277	total: 1.93s	remaining: 649ms
369:	learn: 0.3162223	total: 1.94s	remaining: 644ms
370:	learn: 0.3158071	total: 1.94s	remaining: 639ms
371:	learn: 0.3152902	total: 1.95s	remaining: 634ms
372:	learn: 0.3148583	total: 1.95s	remaining: 628ms
373:	learn: 0.3144023	total: 1.96s	remaining: 623ms
374:	learn: 0.3138801	total: 1.96s	remaining: 618ms
375:	learn: 0.3134826	total: 1.97s	remaining: 613ms
376:	learn: 0.3129753	total: 1.97s	remaining: 607ms
377:	learn: 0.3125493	total: 1.98s	remaining: 602ms
378:	learn: 0.3121401	total: 1.98s	remaining: 596ms
379:	learn: 0.3116738	total: 1.99s	remaining: 591ms
380:	learn: 0.3112859	total: 1.99s	remaining: 585ms
381:	learn: 0.3108107	total: 2s	remaining: 580ms
382:	learn: 0.3103885	total: 2s	remaining: 575ms
383:	learn: 0.3099893	total: 2s	remaining: 569ms
384:	learn: 0.3095343	total: 2.01s	remaining: 564ms
385:	learn: 0.3090410	total: 2.01s	remaining: 558ms
386:	learn: 0.3086240	total: 2.02s	remaining: 553ms

[I 2026-04-16 17:37:19,414] Trial 1 finished with value: 0.7029220462986405 and parameters: {'iterations': 493, 'learning_rate': 0.02028575941899529, 'l2_leaf_reg': 3.702797715892871, 'bootstrap_type': 'Bernoulli', 'max_depth': 1}. Best is trial 0 with value: 0.9579421778839013.

0:	learn: 1.0504177	total: 40ms	remaining: 39.3s
1:	learn: 1.0070082	total: 76.1ms	remaining: 37.4s
2:	learn: 0.9676368	total: 113ms	remaining: 36.8s
3:	learn: 0.9316421	total: 147ms	remaining: 36s
4:	learn: 0.8762251	total: 184ms	remaining: 36s
5:	learn: 0.8260821	total: 219ms	remaining: 35.6s
6:	learn: 0.7803232	total: 255ms	remaining: 35.5s
7:	learn: 0.7384864	total: 293ms	remaining: 35.8s
8:	learn: 0.6999648	total: 332ms	remaining: 36s
9:	learn: 0.6644742	total: 372ms	remaining: 36.2s
10:	learn: 0.6316209	total: 411ms	remaining: 36.3s
11:	learn: 0.6010836	total: 452ms	remaining: 36.6s
12:	learn: 0.5727115	total: 491ms	remaining: 36.7s
13:	learn: 0.5462496	total: 533ms	remaining: 36.9s
14:	learn: 0.5215231	total: 573ms	remaining: 37s
15:	learn: 0.4983423	total: 611ms	remaining: 36.9s
16:	learn: 0.4766051	total: 646ms	remaining: 36.7s
17:	learn: 0.4562255	total: 680ms	remaining: 36.5s
18:	learn: 0.4370633	total: 714ms	remaining: 36.3s
19:	learn: 0.4190027	total: 755ms	remaining: 36.4s
20:	learn: 0.4019952	total: 794ms	remaining: 36.4s
21:	learn: 0.3859475	total: 832ms	remaining: 36.4s
22:	learn: 0.3707614	total: 868ms	remaining: 36.2s
23:	learn: 0.3564513	total: 908ms	remaining: 36.3s
24:	learn: 0.3428872	total: 946ms	remaining: 36.3s
25:	learn: 0.3300327	total: 984ms	remaining: 36.2s
26:	learn: 0.3178845	total: 1.02s	remaining: 36.2s
27:	learn: 0.3063443	total: 1.06s	remaining: 36.1s
28:	learn: 0.2954287	total: 1.09s	remaining: 36s
29:	learn: 0.2850307	total: 1.13s	remaining: 35.9s
30:	learn: 0.2751729	total: 1.17s	remaining: 35.9s
31:	learn: 0.2657623	total: 1.2s	remaining: 35.8s
32:	learn: 0.2568694	total: 1.24s	remaining: 35.8s
33:	learn: 0.2483739	total: 1.28s	remaining: 35.8s
34:	learn: 0.2402912	total: 1.32s	remaining: 35.8s
35:	learn: 0.2326266	total: 1.36s	remaining: 35.9s
36:	learn: 0.2252867	total: 1.4s	remaining: 35.9s
37:	learn: 0.2183144	total: 1.44s	remaining: 36s
38:	learn: 0.2116386	total: 1.48s	remaining: 35.9s
39:	learn: 0.2053170	total: 1.52s	remaining: 36s
40:	learn: 0.1992755	total: 1.56s	remaining: 35.9s
41:	learn: 0.1934937	total: 1.6s	remaining: 35.8s
42:	learn: 0.1879455	total: 1.63s	remaining: 35.7s
43:	learn: 0.1826570	total: 1.67s	remaining: 35.7s
44:	learn: 0.1776262	total: 1.71s	remaining: 35.6s
45:	learn: 0.1728051	total: 1.74s	remaining: 35.5s
46:	learn: 0.1682010	total: 1.78s	remaining: 35.5s
47:	learn: 0.1638525	total: 1.82s	remaining: 35.4s
48:	learn: 0.1596497	total: 1.85s	remaining: 35.3s
49:	learn: 0.1556141	total: 1.89s	remaining: 35.3s
50:	learn: 0.1517865	total: 1.93s	remaining: 35.2s
51:	learn: 0.1481073	total: 1.96s	remaining: 35.1s
52:	learn: 0.1446079	total: 2s	remaining: 35.1s
53:	learn: 0.1412423	total: 2.04s	remaining: 35.1s
54:	learn: 0.1380293	total: 2.07s	remaining: 35s
55:	learn: 0.1349554	total: 2.11s	remaining: 35s
56:	learn: 0.1320211	total: 2.15s	remaining: 35s
57:	learn: 0.1292576	total: 2.19s	remaining: 35s
58:	learn: 0.1265614	total: 2.23s	remaining: 35s
59:	learn: 0.1240116	total: 2.28s	remaining: 35.1s
60:	learn: 0.1215724	total: 2.32s	remaining: 35.2s
61:	learn: 0.1192028	total: 2.37s	remaining: 35.2s
62:	learn: 0.1169717	total: 2.41s	remaining: 35.2s
63:	learn: 0.1148271	total: 2.45s	remaining: 35.2s
64:	learn: 0.1127554	total: 2.49s	remaining: 35.2s
65:	learn: 0.1107845	total: 2.53s	remaining: 35.2s
66:	learn: 0.1088856	total: 2.57s	remaining: 35.2s
67:	learn: 0.1070815	total: 2.61s	remaining: 35.2s
68:	learn: 0.1053517	total: 2.65s	remaining: 35.2s
69:	learn: 0.1036800	total: 2.69s	remaining: 35.2s
70:	learn: 0.1020806	total: 2.73s	remaining: 35.1s
71:	learn: 0.1005508	total: 2.77s	remaining: 35.1s
72:	learn: 0.0990828	total: 2.81s	remaining: 35.1s
73:	learn: 0.0976641	total: 2.85s	remaining: 35.1s
74:	learn: 0.0963201	total: 2.89s	remaining: 35s
75:	learn: 0.0950161	total: 2.93s	remaining: 35s
76:	learn: 0.0937471	total: 2.96s	remaining: 34.9s
77:	learn: 0.0925659	total: 3.01s	remaining: 35s
78:	learn: 0.0914181	total: 3.05s	remaining: 35s
79:	learn: 0.0903252	total: 3.09s	remaining: 34.9s
80:	learn: 0.0892638	total: 3.13s	remaining: 34.9s
81:	learn: 0.0882671	total: 3.18s	remaining: 34.9s
82:	learn: 0.0872906	total: 3.21s	remaining: 34.9s
83:	learn: 0.0863542	total: 3.26s	remaining: 34.9s
84:	learn: 0.0854609	total: 3.3s	remaining: 34.9s
85:	learn: 0.0846069	total: 3.34s	remaining: 34.9s
86:	learn: 0.0837764	total: 3.38s	remaining: 34.8s
87:	learn: 0.0830060	total: 3.42s	remaining: 34.8s
88:	learn: 0.0822518	total: 3.46s	remaining: 34.8s
89:	learn: 0.0815227	total: 3.5s	remaining: 34.8s
90:	learn: 0.0808208	total: 3.55s	remaining: 34.8s
91:	learn: 0.0801350	total: 3.58s	remaining: 34.8s
92:	learn: 0.0794864	total: 3.62s	remaining: 34.7s
93:	learn: 0.0788717	total: 3.67s	remaining: 34.7s
94:	learn: 0.0782637	total: 3.71s	remaining: 34.7s
95:	learn: 0.0776814	total: 3.75s	remaining: 34.7s
96:	learn: 0.0771400	total: 3.79s	remaining: 34.7s
97:	learn: 0.0766016	total: 3.83s	remaining: 34.7s
98:	learn: 0.0760845	total: 3.87s	remaining: 34.6s
99:	learn: 0.0756102	total: 3.92s	remaining: 34.6s
100:	learn: 0.0751270	total: 3.96s	remaining: 34.6s
101:	learn: 0.0746789	total: 4s	remaining: 34.6s
102:	learn: 0.0742507	total: 4.06s	remaining: 34.7s
103:	learn: 0.0738272	total: 4.1s	remaining: 34.7s
104:	learn: 0.0734231	total: 4.14s	remaining: 34.6s
105:	learn: 0.0730306	total: 4.18s	remaining: 34.6s
106:	learn: 0.0726527	total: 4.22s	remaining: 34.6s
107:	learn: 0.0722966	total: 4.26s	remaining: 34.6s
108:	learn: 0.0719458	total: 4.3s	remaining: 34.6s
109:	learn: 0.0716048	total: 4.34s	remaining: 34.5s
110:	learn: 0.0712773	total: 4.39s	remaining: 34.5s
111:	learn: 0.0709825	total: 4.43s	remaining: 34.5s
112:	learn: 0.0706601	total: 4.47s	remaining: 34.4s
113:	learn: 0.0703948	total: 4.5s	remaining: 34.4s
114:	learn: 0.0701134	total: 4.55s	remaining: 34.4s
115:	learn: 0.0698364	total: 4.59s	remaining: 34.3s
116:	learn: 0.0695912	total: 4.63s	remaining: 34.3s
117:	learn: 0.0693382	total: 4.67s	remaining: 34.3s
118:	learn: 0.0690904	total: 4.71s	remaining: 34.2s
119:	learn: 0.0688433	total: 4.74s	remaining: 34.2s
120:	learn: 0.0686268	total: 4.79s	remaining: 34.1s
121:	learn: 0.0684220	total: 4.82s	remaining: 34.1s
122:	learn: 0.0682378	total: 4.87s	remaining: 34.1s
123:	learn: 0.0680420	total: 4.91s	remaining: 34.1s
124:	learn: 0.0678546	total: 4.95s	remaining: 34s
125:	learn: 0.0676778	total: 4.98s	remaining: 33.9s
126:	learn: 0.0675079	total: 5.03s	remaining: 33.9s
127:	learn: 0.0673364	total: 5.07s	remaining: 33.9s
128:	learn: 0.0671749	total: 5.11s	remaining: 33.9s
129:	learn: 0.0670042	total: 5.15s	remaining: 33.8s
130:	learn: 0.0668465	total: 5.19s	remaining: 33.8s
131:	learn: 0.0666945	total: 5.23s	remaining: 33.7s
132:	learn: 0.0665648	total: 5.26s	remaining: 33.7s
133:	learn: 0.0664244	total: 5.31s	remaining: 33.7s
134:	learn: 0.0662869	total: 5.35s	remaining: 33.7s
135:	learn: 0.0661552	total: 5.39s	remaining: 33.6s
136:	learn: 0.0660153	total: 5.43s	remaining: 33.6s
137:	learn: 0.0658887	total: 5.46s	remaining: 33.5s
138:	learn: 0.0657666	total: 5.51s	remaining: 33.5s
139:	learn: 0.0656535	total: 5.55s	remaining: 33.5s
140:	learn: 0.0655352	total: 5.59s	remaining: 33.4s
141:	learn: 0.0654162	total: 5.63s	remaining: 33.4s
142:	learn: 0.0652973	total: 5.67s	remaining: 33.4s
143:	learn: 0.0651673	total: 5.71s	remaining: 33.3s
144:	learn: 0.0650636	total: 5.74s	remaining: 33.2s
145:	learn: 0.0649638	total: 5.78s	remaining: 33.2s
146:	learn: 0.0648513	total: 5.82s	remaining: 33.1s
147:	learn: 0.0647475	total: 5.86s	remaining: 33.1s
148:	learn: 0.0646557	total: 5.9s	remaining: 33.1s
149:	learn: 0.0645364	total: 5.94s	remaining: 33s
150:	learn: 0.0644419	total: 5.97s	remaining: 33s
151:	learn: 0.0643569	total: 6.01s	remaining: 32.9s
152:	learn: 0.0642662	total: 6.05s	remaining: 32.9s
153:	learn: 0.0641558	total: 6.08s	remaining: 32.8s
154:	learn: 0.0640558	total: 6.13s	remaining: 32.8s
155:	learn: 0.0639678	total: 6.17s	remaining: 32.7s
156:	learn: 0.0638599	total: 6.21s	remaining: 32.7s
157:	learn: 0.0637762	total: 6.25s	remaining: 32.7s
158:	learn: 0.0636837	total: 6.29s	remaining: 32.6s
159:	learn: 0.0636121	total: 6.33s	remaining: 32.6s
160:	learn: 0.0635428	total: 6.37s	remaining: 32.5s
161:	learn: 0.0634567	total: 6.41s	remaining: 32.5s
162:	learn: 0.0633889	total: 6.44s	remaining: 32.4s
163:	learn: 0.0633234	total: 6.48s	remaining: 32.4s
164:	learn: 0.0632555	total: 6.51s	remaining: 32.3s
165:	learn: 0.0632006	total: 6.55s	remaining: 32.3s
166:	learn: 0.0631279	total: 6.59s	remaining: 32.2s
167:	learn: 0.0630764	total: 6.62s	remaining: 32.2s
168:	learn: 0.0630216	total: 6.66s	remaining: 32.1s
169:	learn: 0.0629558	total: 6.7s	remaining: 32.1s
170:	learn: 0.0628863	total: 6.74s	remaining: 32s
171:	learn: 0.0628170	total: 6.77s	remaining: 32s
172:	learn: 0.0627469	total: 6.8s	remaining: 31.9s
173:	learn: 0.0626929	total: 6.84s	remaining: 31.8s
174:	learn: 0.0626527	total: 6.87s	remaining: 31.8s
175:	learn: 0.0625876	total: 6.9s	remaining: 31.7s
176:	learn: 0.0625340	total: 6.94s	remaining: 31.6s
177:	learn: 0.0624815	total: 6.98s	remaining: 31.6s
178:	learn: 0.0624368	total: 7.02s	remaining: 31.6s
179:	learn: 0.0623903	total: 7.05s	remaining: 31.5s
180:	learn: 0.0623549	total: 7.09s	remaining: 31.4s
181:	learn: 0.0622994	total: 7.13s	remaining: 31.4s
182:	learn: 0.0622418	total: 7.16s	remaining: 31.4s
183:	learn: 0.0622010	total: 7.21s	remaining: 31.3s
184:	learn: 0.0621553	total: 7.25s	remaining: 31.3s
185:	learn: 0.0621532	total: 7.28s	remaining: 31.2s
186:	learn: 0.0621514	total: 7.3s	remaining: 31.1s
187:	learn: 0.0621498	total: 7.33s	remaining: 31s
188:	learn: 0.0621098	total: 7.36s	remaining: 31s
189:	learn: 0.0621084	total: 7.39s	remaining: 30.9s
190:	learn: 0.0621071	total: 7.41s	remaining: 30.8s
191:	learn: 0.0621059	total: 7.44s	remaining: 30.7s
192:	learn: 0.0621048	total: 7.47s	remaining: 30.6s
193:	learn: 0.0620582	total: 7.5s	remaining: 30.6s
194:	learn: 0.0620111	total: 7.54s	remaining: 30.5s
195:	learn: 0.0619439	total: 7.58s	remaining: 30.5s
196:	learn: 0.0619429	total: 7.6s	remaining: 30.4s
197:	learn: 0.0619421	total: 7.63s	remaining: 30.3s
198:	learn: 0.0619413	total: 7.66s	remaining: 30.2s
199:	learn: 0.0618989	total: 7.69s	remaining: 30.2s
200:	learn: 0.0618980	total: 7.73s	remaining: 30.1s
201:	learn: 0.0618973	total: 7.76s	remaining: 30s
202:	learn: 0.0618585	total: 7.79s	remaining: 30s
203:	learn: 0.0618099	total: 7.83s	remaining: 29.9s
204:	learn: 0.0617734	total: 7.87s	remaining: 29.9s
205:	learn: 0.0617729	total: 7.89s	remaining: 29.8s
206:	learn: 0.0617724	total: 7.92s	remaining: 29.7s
207:	learn: 0.0617718	total: 7.95s	remaining: 29.7s
208:	learn: 0.0617373	total: 7.98s	remaining: 29.6s
209:	learn: 0.0616877	total: 8.03s	remaining: 29.6s
210:	learn: 0.0616873	total: 8.05s	remaining: 29.5s
211:	learn: 0.0616869	total: 8.08s	remaining: 29.4s
212:	learn: 0.0616864	total: 8.11s	remaining: 29.4s
213:	learn: 0.0616861	total: 8.14s	remaining: 29.3s
214:	learn: 0.0616480	total: 8.17s	remaining: 29.2s
215:	learn: 0.0616156	total: 8.21s	remaining: 29.2s
216:	learn: 0.0615573	total: 8.24s	remaining: 29.1s
217:	learn: 0.0615571	total: 8.24s	remaining: 29s
218:	learn: 0.0615568	total: 8.27s	remaining: 28.9s
219:	learn: 0.0615565	total: 8.3s	remaining: 28.8s
220:	learn: 0.0615562	total: 8.32s	remaining: 28.7s
221:	learn: 0.0615561	total: 8.33s	remaining: 28.6s
222:	learn: 0.0615558	total: 8.36s	remaining: 28.5s
223:	learn: 0.0615555	total: 8.38s	remaining: 28.4s
224:	learn: 0.0615551	total: 8.4s	remaining: 28.4s
225:	learn: 0.0615550	total: 8.43s	remaining: 28.3s
226:	learn: 0.0615547	total: 8.45s	remaining: 28.2s
227:	learn: 0.0615269	total: 8.49s	remaining: 28.1s
228:	learn: 0.0615267	total: 8.52s	remaining: 28.1s
229:	learn: 0.0614671	total: 8.55s	remaining: 28s
230:	learn: 0.0614214	total: 8.59s	remaining: 28s
231:	learn: 0.0614214	total: 8.59s	remaining: 27.8s
232:	learn: 0.0613807	total: 8.62s	remaining: 27.8s
233:	learn: 0.0613804	total: 8.65s	remaining: 27.7s
234:	learn: 0.0613802	total: 8.68s	remaining: 27.7s
235:	learn: 0.0613542	total: 8.71s	remaining: 27.6s
236:	learn: 0.0613229	total: 8.75s	remaining: 27.6s
237:	learn: 0.0612736	total: 8.79s	remaining: 27.6s
238:	learn: 0.0612414	total: 8.83s	remaining: 27.5s
239:	learn: 0.0612413	total: 8.85s	remaining: 27.4s
240:	learn: 0.0611957	total: 8.88s	remaining: 27.4s
241:	learn: 0.0611637	total: 8.92s	remaining: 27.4s
242:	learn: 0.0611635	total: 8.95s	remaining: 27.3s
243:	learn: 0.0611635	total: 8.95s	remaining: 27.2s
244:	learn: 0.0611038	total: 8.99s	remaining: 27.1s
245:	learn: 0.0610726	total: 9.03s	remaining: 27.1s
246:	learn: 0.0610724	total: 9.06s	remaining: 27s
247:	learn: 0.0610722	total: 9.08s	remaining: 27s
248:	learn: 0.0610410	total: 9.11s	remaining: 26.9s
249:	learn: 0.0610409	total: 9.14s	remaining: 26.8s
250:	learn: 0.0610408	total: 9.17s	remaining: 26.8s
251:	learn: 0.0610405	total: 9.19s	remaining: 26.7s
252:	learn: 0.0610405	total: 9.22s	remaining: 26.6s
253:	learn: 0.0610403	total: 9.25s	remaining: 26.6s
254:	learn: 0.0610401	total: 9.27s	remaining: 26.5s
255:	learn: 0.0610400	total: 9.29s	remaining: 26.4s
256:	learn: 0.0610398	total: 9.32s	remaining: 26.4s
257:	learn: 0.0609950	total: 9.36s	remaining: 26.3s
258:	learn: 0.0609696	total: 9.39s	remaining: 26.3s
259:	learn: 0.0609694	total: 9.42s	remaining: 26.2s
260:	learn: 0.0609694	total: 9.45s	remaining: 26.2s
261:	learn: 0.0609692	total: 9.48s	remaining: 26.1s
262:	learn: 0.0609693	total: 9.48s	remaining: 26s
263:	learn: 0.0609691	total: 9.5s	remaining: 25.9s
264:	learn: 0.0609265	total: 9.54s	remaining: 25.9s
265:	learn: 0.0608868	total: 9.58s	remaining: 25.9s
266:	learn: 0.0608867	total: 9.6s	remaining: 25.8s
267:	learn: 0.0608463	total: 9.64s	remaining: 25.8s
268:	learn: 0.0608461	total: 9.67s	remaining: 25.7s
269:	learn: 0.0608053	total: 9.7s	remaining: 25.7s
270:	learn: 0.0607653	total: 9.74s	remaining: 25.6s
271:	learn: 0.0607650	total: 9.76s	remaining: 25.6s
272:	learn: 0.0607418	total: 9.8s	remaining: 25.5s
273:	learn: 0.0607031	total: 9.83s	remaining: 25.5s
274:	learn: 0.0607030	total: 9.86s	remaining: 25.4s
275:	learn: 0.0606609	total: 9.89s	remaining: 25.4s
276:	learn: 0.0606234	total: 9.93s	remaining: 25.4s
277:	learn: 0.0605871	total: 9.97s	remaining: 25.3s
278:	learn: 0.0605490	total: 10s	remaining: 25.3s
279:	learn: 0.0605118	total: 10s	remaining: 25.2s
280:	learn: 0.0605118	total: 10.1s	remaining: 25.2s
281:	learn: 0.0604887	total: 10.1s	remaining: 25.2s
282:	learn: 0.0604554	total: 10.1s	remaining: 25.1s
283:	learn: 0.0604175	total: 10.2s	remaining: 25.1s
284:	learn: 0.0604168	total: 10.2s	remaining: 25s
285:	learn: 0.0604167	total: 10.2s	remaining: 25s
286:	learn: 0.0604165	total: 10.3s	remaining: 24.9s
287:	learn: 0.0604164	total: 10.3s	remaining: 24.9s
288:	learn: 0.0604163	total: 10.3s	remaining: 24.8s
289:	learn: 0.0604156	total: 10.3s	remaining: 24.7s
290:	learn: 0.0604149	total: 10.4s	remaining: 24.7s
291:	learn: 0.0604148	total: 10.4s	remaining: 24.6s
292:	learn: 0.0604147	total: 10.4s	remaining: 24.6s
293:	learn: 0.0604142	total: 10.4s	remaining: 24.5s
294:	learn: 0.0604140	total: 10.5s	remaining: 24.5s
295:	learn: 0.0604139	total: 10.5s	remaining: 24.4s
296:	learn: 0.0604139	total: 10.5s	remaining: 24.3s
297:	learn: 0.0604138	total: 10.6s	remaining: 24.3s
298:	learn: 0.0604131	total: 10.6s	remaining: 24.2s
299:	learn: 0.0604126	total: 10.6s	remaining: 24.2s
300:	learn: 0.0604125	total: 10.6s	remaining: 24.1s
301:	learn: 0.0604120	total: 10.7s	remaining: 24.1s
302:	learn: 0.0604115	total: 10.7s	remaining: 24s
303:	learn: 0.0604110	total: 10.7s	remaining: 24s
304:	learn: 0.0604106	total: 10.7s	remaining: 23.9s
305:	learn: 0.0604104	total: 10.8s	remaining: 23.8s
306:	learn: 0.0604100	total: 10.8s	remaining: 23.8s
307:	learn: 0.0604096	total: 10.8s	remaining: 23.7s
308:	learn: 0.0604095	total: 10.8s	remaining: 23.7s
309:	learn: 0.0604094	total: 10.9s	remaining: 23.6s
310:	learn: 0.0604090	total: 10.9s	remaining: 23.6s
311:	learn: 0.0604089	total: 10.9s	remaining: 23.5s
312:	learn: 0.0604086	total: 10.9s	remaining: 23.5s
313:	learn: 0.0604084	total: 11s	remaining: 23.4s
314:	learn: 0.0604080	total: 11s	remaining: 23.4s
315:	learn: 0.0604079	total: 11s	remaining: 23.3s
316:	learn: 0.0604078	total: 11.1s	remaining: 23.3s
317:	learn: 0.0604074	total: 11.1s	remaining: 23.2s
318:	learn: 0.0604073	total: 11.1s	remaining: 23.2s
319:	learn: 0.0604070	total: 11.1s	remaining: 23.1s
320:	learn: 0.0604069	total: 11.2s	remaining: 23.1s
321:	learn: 0.0604067	total: 11.2s	remaining: 23s
322:	learn: 0.0604066	total: 11.2s	remaining: 23s
323:	learn: 0.0604065	total: 11.3s	remaining: 22.9s
324:	learn: 0.0604064	total: 11.3s	remaining: 22.9s
325:	learn: 0.0604063	total: 11.3s	remaining: 22.8s
326:	learn: 0.0604061	total: 11.3s	remaining: 22.8s
327:	learn: 0.0604060	total: 11.4s	remaining: 22.7s
328:	learn: 0.0604059	total: 11.4s	remaining: 22.7s
329:	learn: 0.0604057	total: 11.4s	remaining: 22.6s
330:	learn: 0.0604057	total: 11.4s	remaining: 22.6s
331:	learn: 0.0604055	total: 11.5s	remaining: 22.5s
332:	learn: 0.0604054	total: 11.5s	remaining: 22.5s
333:	learn: 0.0604053	total: 11.5s	remaining: 22.4s
334:	learn: 0.0604051	total: 11.6s	remaining: 22.4s
335:	learn: 0.0604051	total: 11.6s	remaining: 22.3s
336:	learn: 0.0604050	total: 11.6s	remaining: 22.3s
337:	learn: 0.0604048	total: 11.6s	remaining: 22.2s
338:	learn: 0.0604047	total: 11.7s	remaining: 22.2s
339:	learn: 0.0604046	total: 11.7s	remaining: 22.1s
340:	learn: 0.0604044	total: 11.7s	remaining: 22.1s
341:	learn: 0.0604043	total: 11.7s	remaining: 22s
342:	learn: 0.0604042	total: 11.8s	remaining: 22s
343:	learn: 0.0604042	total: 11.8s	remaining: 21.9s
344:	learn: 0.0604041	total: 11.8s	remaining: 21.9s
345:	learn: 0.0604039	total: 11.8s	remaining: 21.8s
346:	learn: 0.0604039	total: 11.9s	remaining: 21.8s
347:	learn: 0.0604038	total: 11.9s	remaining: 21.7s
348:	learn: 0.0604036	total: 11.9s	remaining: 21.7s
349:	learn: 0.0604035	total: 11.9s	remaining: 21.6s
350:	learn: 0.0604034	total: 12s	remaining: 21.6s
351:	learn: 0.0604033	total: 12s	remaining: 21.5s
352:	learn: 0.0604032	total: 12s	remaining: 21.5s
353:	learn: 0.0604031	total: 12s	remaining: 21.4s
354:	learn: 0.0604031	total: 12.1s	remaining: 21.4s
355:	learn: 0.0604030	total: 12.1s	remaining: 21.3s
356:	learn: 0.0604029	total: 12.1s	remaining: 21.3s
357:	learn: 0.0604029	total: 12.2s	remaining: 21.3s
358:	learn: 0.0604028	total: 12.2s	remaining: 21.2s
359:	learn: 0.0604027	total: 12.2s	remaining: 21.2s
360:	learn: 0.0604027	total: 12.2s	remaining: 21.1s
361:	learn: 0.0604026	total: 12.3s	remaining: 21.1s
362:	learn: 0.0604025	total: 12.3s	remaining: 21s
363:	learn: 0.0604024	total: 12.3s	remaining: 21s
364:	learn: 0.0604023	total: 12.3s	remaining: 20.9s
365:	learn: 0.0604022	total: 12.4s	remaining: 20.9s
366:	learn: 0.0604021	total: 12.4s	remaining: 20.8s
367:	learn: 0.0604019	total: 12.4s	remaining: 20.8s
368:	learn: 0.0604019	total: 12.4s	remaining: 20.7s
369:	learn: 0.0604018	total: 12.5s	remaining: 20.7s
370:	learn: 0.0604018	total: 12.5s	remaining: 20.6s
371:	learn: 0.0604017	total: 12.5s	remaining: 20.6s
372:	learn: 0.0604016	total: 12.5s	remaining: 20.5s
373:	learn: 0.0604015	total: 12.6s	remaining: 20.5s
374:	learn: 0.0604015	total: 12.6s	remaining: 20.5s
375:	learn: 0.0604014	total: 12.6s	remaining: 20.4s
376:	learn: 0.0604013	total: 12.6s	remaining: 20.4s
377:	learn: 0.0604012	total: 12.7s	remaining: 20.3s
378:	learn: 0.0604011	total: 12.7s	remaining: 20.3s
379:	learn: 0.0604010	total: 12.7s	remaining: 20.2s
380:	learn: 0.0604009	total: 12.8s	remaining: 20.2s
381:	learn: 0.0604009	total: 12.8s	remaining: 20.1s
382:	learn: 0.0604008	total: 12.8s	remaining: 20.1s
383:	learn: 0.0604007	total: 12.8s	remaining: 20s
384:	learn: 0.0604007	total: 12.9s	remaining: 20s
385:	learn: 0.0604006	total: 12.9s	remaining: 20s
386:	learn: 0.0604006	total: 12.9s	remaining: 19.9s
387:	learn: 0.0604005	total: 12.9s	remaining: 19.9s
388:	learn: 0.0604004	total: 13s	remaining: 19.8s

[I 2026-04-16 17:37:53,520] Trial 2 finished with value: 0.9588830362022006 and parameters: {'iterations': 984, 'learning_rate': 0.03877222174318945, 'l2_leaf_reg': 3.7335578701850767, 'bootstrap_type': 'Bernoulli', 'max_depth': 10}. Best is trial 2 with value: 0.9588830362022006.

0:	learn: 1.0019559	total: 16.9ms	remaining: 9.9s
1:	learn: 0.9239830	total: 32.3ms	remaining: 9.45s
2:	learn: 0.8137886	total: 48.1ms	remaining: 9.37s
3:	learn: 0.7236749	total: 63.7ms	remaining: 9.28s
4:	learn: 0.6484466	total: 79.4ms	remaining: 9.24s
5:	learn: 0.5845236	total: 94.8ms	remaining: 9.18s
6:	learn: 0.5296121	total: 110ms	remaining: 9.13s
7:	learn: 0.4819288	total: 128ms	remaining: 9.26s
8:	learn: 0.4401904	total: 145ms	remaining: 9.29s
9:	learn: 0.4034460	total: 160ms	remaining: 9.22s
10:	learn: 0.3709543	total: 176ms	remaining: 9.21s
11:	learn: 0.3420493	total: 192ms	remaining: 9.21s
12:	learn: 0.3162769	total: 208ms	remaining: 9.19s
13:	learn: 0.2931920	total: 224ms	remaining: 9.18s
14:	learn: 0.2724831	total: 245ms	remaining: 9.33s
15:	learn: 0.2538230	total: 263ms	remaining: 9.38s
16:	learn: 0.2370004	total: 281ms	remaining: 9.42s
17:	learn: 0.2218368	total: 299ms	remaining: 9.45s
18:	learn: 0.2080787	total: 314ms	remaining: 9.39s
19:	learn: 0.1956741	total: 329ms	remaining: 9.33s
20:	learn: 0.1843486	total: 342ms	remaining: 9.22s
21:	learn: 0.1740618	total: 356ms	remaining: 9.14s
22:	learn: 0.1647657	total: 370ms	remaining: 9.07s
23:	learn: 0.1562449	total: 384ms	remaining: 9s
24:	learn: 0.1485201	total: 398ms	remaining: 8.95s
25:	learn: 0.1414623	total: 415ms	remaining: 8.96s
26:	learn: 0.1349982	total: 430ms	remaining: 8.92s
27:	learn: 0.1291602	total: 445ms	remaining: 8.88s
28:	learn: 0.1237624	total: 460ms	remaining: 8.85s
29:	learn: 0.1188323	total: 475ms	remaining: 8.82s
30:	learn: 0.1143710	total: 491ms	remaining: 8.8s
31:	learn: 0.1102488	total: 506ms	remaining: 8.77s
32:	learn: 0.1064841	total: 522ms	remaining: 8.77s
33:	learn: 0.1030799	total: 538ms	remaining: 8.74s
34:	learn: 0.0999262	total: 554ms	remaining: 8.73s
35:	learn: 0.0970796	total: 569ms	remaining: 8.7s
36:	learn: 0.0944360	total: 584ms	remaining: 8.68s
37:	learn: 0.0920141	total: 597ms	remaining: 8.63s
38:	learn: 0.0897816	total: 610ms	remaining: 8.57s
39:	learn: 0.0877742	total: 624ms	remaining: 8.53s
40:	learn: 0.0859033	total: 638ms	remaining: 8.49s
41:	learn: 0.0841667	total: 651ms	remaining: 8.45s
42:	learn: 0.0825940	total: 667ms	remaining: 8.44s
43:	learn: 0.0811336	total: 682ms	remaining: 8.42s
44:	learn: 0.0798382	total: 697ms	remaining: 8.4s
45:	learn: 0.0786121	total: 714ms	remaining: 8.39s
46:	learn: 0.0774936	total: 728ms	remaining: 8.37s
47:	learn: 0.0764542	total: 743ms	remaining: 8.35s
48:	learn: 0.0755167	total: 758ms	remaining: 8.32s
49:	learn: 0.0746489	total: 773ms	remaining: 8.3s
50:	learn: 0.0738653	total: 788ms	remaining: 8.29s
51:	learn: 0.0731292	total: 803ms	remaining: 8.26s
52:	learn: 0.0725247	total: 816ms	remaining: 8.22s
53:	learn: 0.0719096	total: 829ms	remaining: 8.19s
54:	learn: 0.0714369	total: 842ms	remaining: 8.14s
55:	learn: 0.0708796	total: 856ms	remaining: 8.11s
56:	learn: 0.0703693	total: 869ms	remaining: 8.08s
57:	learn: 0.0699463	total: 881ms	remaining: 8.04s
58:	learn: 0.0696251	total: 893ms	remaining: 7.99s
59:	learn: 0.0692709	total: 910ms	remaining: 7.99s
60:	learn: 0.0688971	total: 926ms	remaining: 7.98s
61:	learn: 0.0685812	total: 940ms	remaining: 7.96s
62:	learn: 0.0682839	total: 955ms	remaining: 7.94s
63:	learn: 0.0680407	total: 968ms	remaining: 7.91s
64:	learn: 0.0677553	total: 984ms	remaining: 7.91s
65:	learn: 0.0675575	total: 998ms	remaining: 7.88s
66:	learn: 0.0673267	total: 1.01s	remaining: 7.85s
67:	learn: 0.0671718	total: 1.02s	remaining: 7.81s
68:	learn: 0.0669962	total: 1.03s	remaining: 7.77s
69:	learn: 0.0668046	total: 1.05s	remaining: 7.73s
70:	learn: 0.0666375	total: 1.06s	remaining: 7.69s
71:	learn: 0.0664649	total: 1.07s	remaining: 7.66s
72:	learn: 0.0663406	total: 1.08s	remaining: 7.62s
73:	learn: 0.0661555	total: 1.09s	remaining: 7.59s
74:	learn: 0.0660549	total: 1.11s	remaining: 7.56s
75:	learn: 0.0659267	total: 1.12s	remaining: 7.55s
76:	learn: 0.0658105	total: 1.14s	remaining: 7.55s
77:	learn: 0.0656789	total: 1.15s	remaining: 7.53s
78:	learn: 0.0655769	total: 1.17s	remaining: 7.51s
79:	learn: 0.0655064	total: 1.18s	remaining: 7.48s
80:	learn: 0.0654127	total: 1.19s	remaining: 7.46s
81:	learn: 0.0653309	total: 1.21s	remaining: 7.44s
82:	learn: 0.0652743	total: 1.22s	remaining: 7.42s
83:	learn: 0.0651766	total: 1.23s	remaining: 7.39s
84:	learn: 0.0651258	total: 1.25s	remaining: 7.36s
85:	learn: 0.0650647	total: 1.26s	remaining: 7.33s
86:	learn: 0.0649620	total: 1.27s	remaining: 7.3s
87:	learn: 0.0649142	total: 1.28s	remaining: 7.26s
88:	learn: 0.0648513	total: 1.29s	remaining: 7.25s
89:	learn: 0.0647792	total: 1.31s	remaining: 7.22s
90:	learn: 0.0646970	total: 1.32s	remaining: 7.19s
91:	learn: 0.0646500	total: 1.33s	remaining: 7.16s
92:	learn: 0.0646490	total: 1.34s	remaining: 7.13s
93:	learn: 0.0646459	total: 1.35s	remaining: 7.1s
94:	learn: 0.0646433	total: 1.37s	remaining: 7.08s
95:	learn: 0.0646426	total: 1.38s	remaining: 7.05s
96:	learn: 0.0646420	total: 1.39s	remaining: 7.02s
97:	learn: 0.0646415	total: 1.4s	remaining: 7s
98:	learn: 0.0646410	total: 1.41s	remaining: 6.97s
99:	learn: 0.0646406	total: 1.43s	remaining: 6.94s
100:	learn: 0.0646401	total: 1.44s	remaining: 6.92s
101:	learn: 0.0646398	total: 1.45s	remaining: 6.88s
102:	learn: 0.0646395	total: 1.46s	remaining: 6.85s
103:	learn: 0.0646393	total: 1.47s	remaining: 6.82s
104:	learn: 0.0646390	total: 1.48s	remaining: 6.79s
105:	learn: 0.0646389	total: 1.49s	remaining: 6.75s
106:	learn: 0.0646387	total: 1.5s	remaining: 6.72s
107:	learn: 0.0646385	total: 1.51s	remaining: 6.69s
108:	learn: 0.0646384	total: 1.52s	remaining: 6.66s
109:	learn: 0.0646383	total: 1.53s	remaining: 6.64s
110:	learn: 0.0646381	total: 1.54s	remaining: 6.62s
111:	learn: 0.0646381	total: 1.55s	remaining: 6.6s
112:	learn: 0.0646380	total: 1.57s	remaining: 6.57s
113:	learn: 0.0646380	total: 1.58s	remaining: 6.55s
114:	learn: 0.0646380	total: 1.59s	remaining: 6.52s
115:	learn: 0.0646380	total: 1.6s	remaining: 6.5s
116:	learn: 0.0646379	total: 1.61s	remaining: 6.48s
117:	learn: 0.0646377	total: 1.63s	remaining: 6.46s
118:	learn: 0.0646376	total: 1.64s	remaining: 6.44s
119:	learn: 0.0646376	total: 1.65s	remaining: 6.42s
120:	learn: 0.0646377	total: 1.66s	remaining: 6.39s
121:	learn: 0.0646376	total: 1.67s	remaining: 6.36s
122:	learn: 0.0646375	total: 1.68s	remaining: 6.34s
123:	learn: 0.0646374	total: 1.69s	remaining: 6.31s
124:	learn: 0.0646375	total: 1.7s	remaining: 6.28s
125:	learn: 0.0646375	total: 1.71s	remaining: 6.25s
126:	learn: 0.0646373	total: 1.72s	remaining: 6.23s
127:	learn: 0.0646374	total: 1.73s	remaining: 6.2s
128:	learn: 0.0646374	total: 1.74s	remaining: 6.18s
129:	learn: 0.0646373	total: 1.75s	remaining: 6.17s
130:	learn: 0.0646372	total: 1.77s	remaining: 6.15s
131:	learn: 0.0646371	total: 1.78s	remaining: 6.13s
132:	learn: 0.0646371	total: 1.79s	remaining: 6.11s
133:	learn: 0.0646371	total: 1.8s	remaining: 6.09s
134:	learn: 0.0646162	total: 1.81s	remaining: 6.07s
135:	learn: 0.0646162	total: 1.82s	remaining: 6.05s
136:	learn: 0.0645420	total: 1.84s	remaining: 6.03s
137:	learn: 0.0645420	total: 1.85s	remaining: 6.01s
138:	learn: 0.0645420	total: 1.86s	remaining: 5.99s
139:	learn: 0.0645420	total: 1.87s	remaining: 5.97s
140:	learn: 0.0645193	total: 1.88s	remaining: 5.95s
141:	learn: 0.0645192	total: 1.89s	remaining: 5.92s
142:	learn: 0.0645192	total: 1.9s	remaining: 5.9s
143:	learn: 0.0645192	total: 1.91s	remaining: 5.88s
144:	learn: 0.0645192	total: 1.92s	remaining: 5.86s
145:	learn: 0.0645191	total: 1.93s	remaining: 5.84s
146:	learn: 0.0645003	total: 1.94s	remaining: 5.81s
147:	learn: 0.0644998	total: 1.95s	remaining: 5.79s
148:	learn: 0.0644996	total: 1.96s	remaining: 5.77s
149:	learn: 0.0644994	total: 1.98s	remaining: 5.76s
150:	learn: 0.0644515	total: 1.99s	remaining: 5.75s
151:	learn: 0.0644135	total: 2s	remaining: 5.74s
152:	learn: 0.0644134	total: 2.02s	remaining: 5.72s
153:	learn: 0.0644134	total: 2.03s	remaining: 5.7s
154:	learn: 0.0644132	total: 2.04s	remaining: 5.68s
155:	learn: 0.0643608	total: 2.05s	remaining: 5.67s
156:	learn: 0.0643092	total: 2.06s	remaining: 5.66s
157:	learn: 0.0643091	total: 2.08s	remaining: 5.64s
158:	learn: 0.0643090	total: 2.09s	remaining: 5.62s
159:	learn: 0.0642031	total: 2.1s	remaining: 5.6s
160:	learn: 0.0642030	total: 2.11s	remaining: 5.58s
161:	learn: 0.0642029	total: 2.12s	remaining: 5.55s
162:	learn: 0.0642028	total: 2.13s	remaining: 5.53s
163:	learn: 0.0642028	total: 2.14s	remaining: 5.51s
164:	learn: 0.0642027	total: 2.15s	remaining: 5.49s
165:	learn: 0.0642027	total: 2.16s	remaining: 5.48s
166:	learn: 0.0641608	total: 2.17s	remaining: 5.47s
167:	learn: 0.0641322	total: 2.19s	remaining: 5.45s
168:	learn: 0.0641322	total: 2.2s	remaining: 5.44s
169:	learn: 0.0641321	total: 2.21s	remaining: 5.42s
170:	learn: 0.0641320	total: 2.22s	remaining: 5.4s
171:	learn: 0.0641320	total: 2.23s	remaining: 5.39s
172:	learn: 0.0641319	total: 2.25s	remaining: 5.38s
173:	learn: 0.0640947	total: 2.26s	remaining: 5.36s
174:	learn: 0.0640947	total: 2.27s	remaining: 5.34s
175:	learn: 0.0640946	total: 2.28s	remaining: 5.33s
176:	learn: 0.0640459	total: 2.29s	remaining: 5.31s
177:	learn: 0.0639811	total: 2.31s	remaining: 5.3s
178:	learn: 0.0639811	total: 2.31s	remaining: 5.28s
179:	learn: 0.0639806	total: 2.32s	remaining: 5.26s
180:	learn: 0.0639168	total: 2.34s	remaining: 5.24s
181:	learn: 0.0638724	total: 2.35s	remaining: 5.23s
182:	learn: 0.0638260	total: 2.36s	remaining: 5.22s
183:	learn: 0.0637897	total: 2.38s	remaining: 5.21s
184:	learn: 0.0637439	total: 2.39s	remaining: 5.2s
185:	learn: 0.0637121	total: 2.4s	remaining: 5.18s
186:	learn: 0.0637116	total: 2.42s	remaining: 5.17s
187:	learn: 0.0637112	total: 2.43s	remaining: 5.15s
188:	learn: 0.0636849	total: 2.44s	remaining: 5.14s
189:	learn: 0.0636844	total: 2.45s	remaining: 5.12s
190:	learn: 0.0636840	total: 2.46s	remaining: 5.11s
191:	learn: 0.0636836	total: 2.48s	remaining: 5.09s
192:	learn: 0.0636382	total: 2.49s	remaining: 5.08s
193:	learn: 0.0635798	total: 2.5s	remaining: 5.06s
194:	learn: 0.0635333	total: 2.51s	remaining: 5.05s
195:	learn: 0.0634908	total: 2.52s	remaining: 5.03s
196:	learn: 0.0634904	total: 2.53s	remaining: 5.01s
197:	learn: 0.0634899	total: 2.54s	remaining: 5s
198:	learn: 0.0634606	total: 2.55s	remaining: 4.98s
199:	learn: 0.0634591	total: 2.56s	remaining: 4.96s
200:	learn: 0.0634230	total: 2.58s	remaining: 4.95s
201:	learn: 0.0633962	total: 2.59s	remaining: 4.93s
202:	learn: 0.0633950	total: 2.6s	remaining: 4.92s
203:	learn: 0.0633939	total: 2.61s	remaining: 4.91s
204:	learn: 0.0633930	total: 2.63s	remaining: 4.89s
205:	learn: 0.0633547	total: 2.64s	remaining: 4.88s
206:	learn: 0.0633152	total: 2.65s	remaining: 4.86s
207:	learn: 0.0633005	total: 2.66s	remaining: 4.85s
208:	learn: 0.0632996	total: 2.67s	remaining: 4.83s
209:	learn: 0.0632989	total: 2.69s	remaining: 4.82s
210:	learn: 0.0632724	total: 2.7s	remaining: 4.81s
211:	learn: 0.0632492	total: 2.71s	remaining: 4.79s
212:	learn: 0.0632260	total: 2.72s	remaining: 4.78s
213:	learn: 0.0632027	total: 2.73s	remaining: 4.76s
214:	learn: 0.0632020	total: 2.74s	remaining: 4.74s
215:	learn: 0.0632015	total: 2.75s	remaining: 4.72s
216:	learn: 0.0632008	total: 2.76s	remaining: 4.71s
217:	learn: 0.0632004	total: 2.77s	remaining: 4.69s
218:	learn: 0.0631767	total: 2.78s	remaining: 4.68s
219:	learn: 0.0631425	total: 2.8s	remaining: 4.66s
220:	learn: 0.0631150	total: 2.81s	remaining: 4.65s
221:	learn: 0.0631149	total: 2.82s	remaining: 4.63s
222:	learn: 0.0630842	total: 2.83s	remaining: 4.62s
223:	learn: 0.0630650	total: 2.84s	remaining: 4.61s
224:	learn: 0.0630402	total: 2.86s	remaining: 4.59s
225:	learn: 0.0630076	total: 2.87s	remaining: 4.58s
226:	learn: 0.0629902	total: 2.88s	remaining: 4.57s
227:	learn: 0.0629902	total: 2.89s	remaining: 4.55s
228:	learn: 0.0629509	total: 2.9s	remaining: 4.54s
229:	learn: 0.0629509	total: 2.92s	remaining: 4.53s
230:	learn: 0.0629507	total: 2.93s	remaining: 4.51s
231:	learn: 0.0629507	total: 2.94s	remaining: 4.49s
232:	learn: 0.0629507	total: 2.95s	remaining: 4.48s
233:	learn: 0.0629265	total: 2.96s	remaining: 4.46s
234:	learn: 0.0628879	total: 2.97s	remaining: 4.45s
235:	learn: 0.0628878	total: 2.98s	remaining: 4.43s
236:	learn: 0.0628877	total: 2.99s	remaining: 4.41s
237:	learn: 0.0628877	total: 3s	remaining: 4.39s
238:	learn: 0.0628877	total: 3.01s	remaining: 4.38s
239:	learn: 0.0628564	total: 3.02s	remaining: 4.37s
240:	learn: 0.0628563	total: 3.03s	remaining: 4.36s
241:	learn: 0.0628563	total: 3.04s	remaining: 4.34s
242:	learn: 0.0628309	total: 3.06s	remaining: 4.33s
243:	learn: 0.0628308	total: 3.07s	remaining: 4.31s
244:	learn: 0.0628308	total: 3.08s	remaining: 4.3s
245:	learn: 0.0628308	total: 3.09s	remaining: 4.28s
246:	learn: 0.0627979	total: 3.1s	remaining: 4.27s
247:	learn: 0.0627747	total: 3.12s	remaining: 4.26s
248:	learn: 0.0627747	total: 3.13s	remaining: 4.24s
249:	learn: 0.0627540	total: 3.14s	remaining: 4.23s
250:	learn: 0.0627388	total: 3.15s	remaining: 4.22s
251:	learn: 0.0627039	total: 3.16s	remaining: 4.21s
252:	learn: 0.0626709	total: 3.18s	remaining: 4.19s
253:	learn: 0.0626261	total: 3.19s	remaining: 4.18s
254:	learn: 0.0625872	total: 3.2s	remaining: 4.17s
255:	learn: 0.0625510	total: 3.21s	remaining: 4.15s
256:	learn: 0.0625355	total: 3.23s	remaining: 4.14s
257:	learn: 0.0625355	total: 3.24s	remaining: 4.13s
258:	learn: 0.0625355	total: 3.25s	remaining: 4.12s
259:	learn: 0.0624782	total: 3.26s	remaining: 4.11s
260:	learn: 0.0624627	total: 3.28s	remaining: 4.09s
261:	learn: 0.0624196	total: 3.29s	remaining: 4.08s
262:	learn: 0.0624195	total: 3.3s	remaining: 4.07s
263:	learn: 0.0623769	total: 3.31s	remaining: 4.05s
264:	learn: 0.0623769	total: 3.33s	remaining: 4.04s
265:	learn: 0.0623769	total: 3.34s	remaining: 4.03s
266:	learn: 0.0623401	total: 3.35s	remaining: 4.02s
267:	learn: 0.0623401	total: 3.36s	remaining: 4s
268:	learn: 0.0623002	total: 3.38s	remaining: 3.99s
269:	learn: 0.0623002	total: 3.39s	remaining: 3.98s
270:	learn: 0.0623002	total: 3.4s	remaining: 3.96s
271:	learn: 0.0622763	total: 3.41s	remaining: 3.95s
272:	learn: 0.0622763	total: 3.42s	remaining: 3.93s
273:	learn: 0.0622763	total: 3.43s	remaining: 3.92s
274:	learn: 0.0622438	total: 3.44s	remaining: 3.9s
275:	learn: 0.0622438	total: 3.46s	remaining: 3.89s
276:	learn: 0.0622438	total: 3.47s	remaining: 3.88s
277:	learn: 0.0622437	total: 3.48s	remaining: 3.87s
278:	learn: 0.0622436	total: 3.49s	remaining: 3.85s
279:	learn: 0.0622436	total: 3.5s	remaining: 3.84s
280:	learn: 0.0621970	total: 3.52s	remaining: 3.83s
281:	learn: 0.0621970	total: 3.53s	remaining: 3.82s
282:	learn: 0.0621970	total: 3.54s	remaining: 3.8s
283:	learn: 0.0621970	total: 3.55s	remaining: 3.79s
284:	learn: 0.0621970	total: 3.56s	remaining: 3.78s
285:	learn: 0.0621851	total: 3.58s	remaining: 3.77s
286:	learn: 0.0621654	total: 3.59s	remaining: 3.75s
287:	learn: 0.0621374	total: 3.6s	remaining: 3.74s
288:	learn: 0.0621005	total: 3.61s	remaining: 3.73s
289:	learn: 0.0621004	total: 3.63s	remaining: 3.71s
290:	learn: 0.0621004	total: 3.64s	remaining: 3.7s
291:	learn: 0.0620706	total: 3.65s	remaining: 3.69s
292:	learn: 0.0620280	total: 3.67s	remaining: 3.68s
293:	learn: 0.0620280	total: 3.68s	remaining: 3.67s
294:	learn: 0.0620177	total: 3.69s	remaining: 3.65s
295:	learn: 0.0619979	total: 3.71s	remaining: 3.64s
296:	learn: 0.0619789	total: 3.72s	remaining: 3.63s
297:	learn: 0.0619528	total: 3.73s	remaining: 3.62s
298:	learn: 0.0619528	total: 3.74s	remaining: 3.61s
299:	learn: 0.0619529	total: 3.75s	remaining: 3.59s
300:	learn: 0.0619425	total: 3.77s	remaining: 3.58s
301:	learn: 0.0619425	total: 3.78s	remaining: 3.57s
302:	learn: 0.0619425	total: 3.79s	remaining: 3.55s
303:	learn: 0.0619425	total: 3.8s	remaining: 3.54s
304:	learn: 0.0619424	total: 3.81s	remaining: 3.52s
305:	learn: 0.0619027	total: 3.82s	remaining: 3.51s
306:	learn: 0.0619027	total: 3.83s	remaining: 3.5s
307:	learn: 0.0619026	total: 3.84s	remaining: 3.48s
308:	learn: 0.0618653	total: 3.85s	remaining: 3.47s
309:	learn: 0.0618035	total: 3.87s	remaining: 3.45s
310:	learn: 0.0618035	total: 3.88s	remaining: 3.44s
311:	learn: 0.0617733	total: 3.89s	remaining: 3.43s
312:	learn: 0.0617733	total: 3.9s	remaining: 3.42s
313:	learn: 0.0617425	total: 3.92s	remaining: 3.41s
314:	learn: 0.0617425	total: 3.93s	remaining: 3.4s
315:	learn: 0.0617199	total: 3.94s	remaining: 3.38s
316:	learn: 0.0617048	total: 3.96s	remaining: 3.37s
317:	learn: 0.0617048	total: 3.97s	remaining: 3.36s
318:	learn: 0.0616718	total: 3.98s	remaining: 3.35s
319:	learn: 0.0616718	total: 3.99s	remaining: 3.33s
320:	learn: 0.0616718	total: 4s	remaining: 3.32s
321:	learn: 0.0616718	total: 4.02s	remaining: 3.31s
322:	learn: 0.0616416	total: 4.03s	remaining: 3.29s
323:	learn: 0.0616416	total: 4.04s	remaining: 3.28s
324:	learn: 0.0616416	total: 4.05s	remaining: 3.26s
325:	learn: 0.0616416	total: 4.06s	remaining: 3.25s
326:	learn: 0.0616416	total: 4.07s	remaining: 3.24s
327:	learn: 0.0616307	total: 4.08s	remaining: 3.22s
328:	learn: 0.0615749	total: 4.09s	remaining: 3.21s
329:	learn: 0.0615399	total: 4.11s	remaining: 3.2s
330:	learn: 0.0615400	total: 4.12s	remaining: 3.19s
331:	learn: 0.0615400	total: 4.13s	remaining: 3.17s
332:	learn: 0.0615399	total: 4.14s	remaining: 3.16s
333:	learn: 0.0615399	total: 4.16s	remaining: 3.15s
334:	learn: 0.0615150	total: 4.17s	remaining: 3.14s
335:	learn: 0.0615149	total: 4.18s	remaining: 3.12s
336:	learn: 0.0615149	total: 4.19s	remaining: 3.11s
337:	learn: 0.0615149	total: 4.21s	remaining: 3.1s
338:	learn: 0.0615149	total: 4.22s	remaining: 3.08s
339:	learn: 0.0615149	total: 4.22s	remaining: 3.07s
340:	learn: 0.0615149	total: 4.24s	remaining: 3.06s
341:	learn: 0.0615148	total: 4.25s	remaining: 3.04s
342:	learn: 0.0614863	total: 4.26s	remaining: 3.03s
343:	learn: 0.0614641	total: 4.27s	remaining: 3.02s
344:	learn: 0.0614641	total: 4.28s	remaining: 3s
345:	learn: 0.0614641	total: 4.29s	remaining: 2.99s
346:	learn: 0.0614268	total: 4.3s	remaining: 2.98s
347:	learn: 0.0614268	total: 4.32s	remaining: 2.96s
348:	learn: 0.0614268	total: 4.33s	remaining: 2.95s
349:	learn: 0.0614043	total: 4.34s	remaining: 2.94s
350:	learn: 0.0613953	total: 4.35s	remaining: 2.93s
351:	learn: 0.0613758	total: 4.37s	remaining: 2.92s
352:	learn: 0.0613758	total: 4.38s	remaining: 2.9s
353:	learn: 0.0613758	total: 4.39s	remaining: 2.89s
354:	learn: 0.0613758	total: 4.4s	remaining: 2.88s
355:	learn: 0.0613758	total: 4.41s	remaining: 2.86s
356:	learn: 0.0613459	total: 4.42s	remaining: 2.85s
357:	learn: 0.0613180	total: 4.44s	remaining: 2.84s
358:	learn: 0.0612907	total: 4.45s	remaining: 2.83s
359:	learn: 0.0612907	total: 4.46s	remaining: 2.81s
360:	learn: 0.0612566	total: 4.47s	remaining: 2.8s
361:	learn: 0.0612166	total: 4.49s	remaining: 2.79s
362:	learn: 0.0612082	total: 4.5s	remaining: 2.78s
363:	learn: 0.0612082	total: 4.51s	remaining: 2.76s
364:	learn: 0.0611865	total: 4.52s	remaining: 2.75s
365:	learn: 0.0611694	total: 4.54s	remaining: 2.74s
366:	learn: 0.0611353	total: 4.55s	remaining: 2.73s
367:	learn: 0.0610989	total: 4.56s	remaining: 2.72s
368:	learn: 0.0610875	total: 4.58s	remaining: 2.7s
369:	learn: 0.0610656	total: 4.59s	remaining: 2.69s
370:	learn: 0.0610590	total: 4.61s	remaining: 2.68s
371:	learn: 0.0610581	total: 4.62s	remaining: 2.67s
372:	learn: 0.0610581	total: 4.63s	remaining: 2.65s
373:	learn: 0.0610581	total: 4.64s	remaining: 2.64s
374:	learn: 0.0610574	total: 4.65s	remaining: 2.63s
375:	learn: 0.0610568	total: 4.66s	remaining: 2.62s
376:	learn: 0.0610568	total: 4.67s	remaining: 2.6s
377:	learn: 0.0610568	total: 4.68s	remaining: 2.59s
378:	learn: 0.0610568	total: 4.69s	remaining: 2.58s
379:	learn: 0.0610563	total: 4.71s	remaining: 2.56s
380:	learn: 0.0610563	total: 4.72s	remaining: 2.55s
381:	learn: 0.0610562	total: 4.73s	remaining: 2.54s
382:	learn: 0.0610558	total: 4.74s	remaining: 2.52s
383:	learn: 0.0610554	total: 4.75s	remaining: 2.51s
384:	learn: 0.0610485	total: 4.76s	remaining: 2.5s
385:	learn: 0.0610482	total: 4.78s	remaining: 2.49s
386:	learn: 0.0610478	total: 4.79s	remaining: 2.48s
387:	learn: 0.0610475	total: 4.8s	remaining: 2.46s

[I 2026-04-16 17:38:05,311] Trial 3 finished with value: 0.9591528912984809 and parameters: {'iterations': 587, 'learning_rate': 0.07983556916867832, 'l2_leaf_reg': 3.8726669656276553, 'bootstrap_type': 'Bernoulli', 'max_depth': 7}. Best is trial 3 with value: 0.9591528912984809.

0:	learn: 1.0191591	total: 24.9ms	remaining: 16.5s
1:	learn: 0.9524917	total: 48.8ms	remaining: 16.2s
2:	learn: 0.8953178	total: 72ms	remaining: 15.9s
3:	learn: 0.8088802	total: 97.7ms	remaining: 16.2s
4:	learn: 0.7353051	total: 124ms	remaining: 16.4s
5:	learn: 0.6717737	total: 148ms	remaining: 16.3s
6:	learn: 0.6163055	total: 172ms	remaining: 16.2s
7:	learn: 0.5674488	total: 198ms	remaining: 16.3s
8:	learn: 0.5241089	total: 223ms	remaining: 16.3s
9:	learn: 0.4854343	total: 247ms	remaining: 16.2s
10:	learn: 0.4507135	total: 271ms	remaining: 16.1s
11:	learn: 0.4194702	total: 296ms	remaining: 16.1s
12:	learn: 0.3911937	total: 320ms	remaining: 16.1s
13:	learn: 0.3655554	total: 345ms	remaining: 16.1s
14:	learn: 0.3422634	total: 366ms	remaining: 15.9s
15:	learn: 0.3210083	total: 386ms	remaining: 15.7s
16:	learn: 0.3016166	total: 412ms	remaining: 15.7s
17:	learn: 0.2838432	total: 437ms	remaining: 15.7s
18:	learn: 0.2675525	total: 460ms	remaining: 15.6s
19:	learn: 0.2526158	total: 481ms	remaining: 15.5s
20:	learn: 0.2388622	total: 503ms	remaining: 15.5s
21:	learn: 0.2262250	total: 545ms	remaining: 16s
22:	learn: 0.2146058	total: 567ms	remaining: 15.8s
23:	learn: 0.2038390	total: 587ms	remaining: 15.7s
24:	learn: 0.1939177	total: 607ms	remaining: 15.6s
25:	learn: 0.1847439	total: 635ms	remaining: 15.6s
26:	learn: 0.1762638	total: 657ms	remaining: 15.6s
27:	learn: 0.1683960	total: 680ms	remaining: 15.5s
28:	learn: 0.1611266	total: 701ms	remaining: 15.4s
29:	learn: 0.1543900	total: 722ms	remaining: 15.3s
30:	learn: 0.1481249	total: 744ms	remaining: 15.2s
31:	learn: 0.1423543	total: 764ms	remaining: 15.1s
32:	learn: 0.1369742	total: 785ms	remaining: 15.1s
33:	learn: 0.1319782	total: 804ms	remaining: 15s
34:	learn: 0.1273697	total: 828ms	remaining: 14.9s
35:	learn: 0.1230792	total: 852ms	remaining: 14.9s
36:	learn: 0.1190475	total: 872ms	remaining: 14.8s
37:	learn: 0.1153675	total: 892ms	remaining: 14.7s
38:	learn: 0.1118919	total: 912ms	remaining: 14.7s
39:	learn: 0.1086823	total: 935ms	remaining: 14.6s
40:	learn: 0.1056887	total: 956ms	remaining: 14.6s
41:	learn: 0.1029087	total: 976ms	remaining: 14.5s
42:	learn: 0.1003061	total: 998ms	remaining: 14.5s
43:	learn: 0.0979145	total: 1.02s	remaining: 14.4s
44:	learn: 0.0956566	total: 1.04s	remaining: 14.4s
45:	learn: 0.0935493	total: 1.06s	remaining: 14.3s
46:	learn: 0.0915829	total: 1.09s	remaining: 14.3s
47:	learn: 0.0897844	total: 1.11s	remaining: 14.3s
48:	learn: 0.0880737	total: 1.13s	remaining: 14.2s
49:	learn: 0.0865104	total: 1.15s	remaining: 14.2s
50:	learn: 0.0850463	total: 1.18s	remaining: 14.2s
51:	learn: 0.0836771	total: 1.2s	remaining: 14.2s
52:	learn: 0.0823918	total: 1.22s	remaining: 14.1s
53:	learn: 0.0811820	total: 1.24s	remaining: 14.1s
54:	learn: 0.0800970	total: 1.27s	remaining: 14.1s
55:	learn: 0.0790332	total: 1.29s	remaining: 14.1s
56:	learn: 0.0780453	total: 1.32s	remaining: 14.1s
57:	learn: 0.0771475	total: 1.34s	remaining: 14.1s
58:	learn: 0.0762810	total: 1.36s	remaining: 14s
59:	learn: 0.0754905	total: 1.38s	remaining: 14s
60:	learn: 0.0747575	total: 1.41s	remaining: 13.9s
61:	learn: 0.0740379	total: 1.42s	remaining: 13.9s
62:	learn: 0.0733835	total: 1.44s	remaining: 13.8s
63:	learn: 0.0727791	total: 1.47s	remaining: 13.9s
64:	learn: 0.0722229	total: 1.5s	remaining: 13.8s
65:	learn: 0.0716837	total: 1.52s	remaining: 13.8s
66:	learn: 0.0711890	total: 1.54s	remaining: 13.8s
67:	learn: 0.0707664	total: 1.57s	remaining: 13.8s
68:	learn: 0.0703703	total: 1.59s	remaining: 13.7s
69:	learn: 0.0699354	total: 1.61s	remaining: 13.7s
70:	learn: 0.0696107	total: 1.63s	remaining: 13.6s
71:	learn: 0.0692274	total: 1.65s	remaining: 13.6s
72:	learn: 0.0688919	total: 1.68s	remaining: 13.6s
73:	learn: 0.0686245	total: 1.7s	remaining: 13.6s
74:	learn: 0.0683132	total: 1.72s	remaining: 13.6s
75:	learn: 0.0680735	total: 1.74s	remaining: 13.5s
76:	learn: 0.0678553	total: 1.76s	remaining: 13.5s
77:	learn: 0.0676161	total: 1.79s	remaining: 13.5s
78:	learn: 0.0674343	total: 1.81s	remaining: 13.4s
79:	learn: 0.0672002	total: 1.83s	remaining: 13.4s
80:	learn: 0.0670174	total: 1.85s	remaining: 13.4s
81:	learn: 0.0668282	total: 1.87s	remaining: 13.3s
82:	learn: 0.0666481	total: 1.89s	remaining: 13.3s
83:	learn: 0.0664659	total: 1.91s	remaining: 13.2s
84:	learn: 0.0663076	total: 1.94s	remaining: 13.2s
85:	learn: 0.0661756	total: 1.96s	remaining: 13.2s
86:	learn: 0.0660332	total: 1.98s	remaining: 13.1s
87:	learn: 0.0658944	total: 1.99s	remaining: 13.1s
88:	learn: 0.0657082	total: 2.01s	remaining: 13.1s
89:	learn: 0.0655598	total: 2.03s	remaining: 13s
90:	learn: 0.0654104	total: 2.05s	remaining: 13s
91:	learn: 0.0653279	total: 2.07s	remaining: 12.9s
92:	learn: 0.0652290	total: 2.1s	remaining: 12.9s
93:	learn: 0.0651295	total: 2.12s	remaining: 12.9s
94:	learn: 0.0650432	total: 2.13s	remaining: 12.8s
95:	learn: 0.0649206	total: 2.16s	remaining: 12.8s
96:	learn: 0.0648586	total: 2.17s	remaining: 12.8s
97:	learn: 0.0647802	total: 2.19s	remaining: 12.7s
98:	learn: 0.0646763	total: 2.21s	remaining: 12.7s
99:	learn: 0.0646154	total: 2.23s	remaining: 12.6s
100:	learn: 0.0645079	total: 2.25s	remaining: 12.6s
101:	learn: 0.0644584	total: 2.27s	remaining: 12.5s
102:	learn: 0.0643581	total: 2.29s	remaining: 12.5s
103:	learn: 0.0642964	total: 2.3s	remaining: 12.4s
104:	learn: 0.0642319	total: 2.32s	remaining: 12.4s
105:	learn: 0.0641493	total: 2.33s	remaining: 12.3s
106:	learn: 0.0640840	total: 2.35s	remaining: 12.3s
107:	learn: 0.0640302	total: 2.36s	remaining: 12.2s
108:	learn: 0.0639980	total: 2.38s	remaining: 12.2s
109:	learn: 0.0639529	total: 2.39s	remaining: 12.1s
110:	learn: 0.0638965	total: 2.42s	remaining: 12.1s
111:	learn: 0.0638791	total: 2.43s	remaining: 12s
112:	learn: 0.0638778	total: 2.44s	remaining: 12s
113:	learn: 0.0638766	total: 2.46s	remaining: 11.9s
114:	learn: 0.0638756	total: 2.48s	remaining: 11.9s
115:	learn: 0.0638748	total: 2.49s	remaining: 11.8s
116:	learn: 0.0638106	total: 2.51s	remaining: 11.8s
117:	learn: 0.0637442	total: 2.52s	remaining: 11.7s
118:	learn: 0.0636938	total: 2.54s	remaining: 11.7s
119:	learn: 0.0636932	total: 2.55s	remaining: 11.6s
120:	learn: 0.0636926	total: 2.56s	remaining: 11.5s
121:	learn: 0.0636922	total: 2.57s	remaining: 11.5s
122:	learn: 0.0636917	total: 2.59s	remaining: 11.4s
123:	learn: 0.0636912	total: 2.6s	remaining: 11.4s
124:	learn: 0.0636908	total: 2.62s	remaining: 11.3s
125:	learn: 0.0636904	total: 2.63s	remaining: 11.3s
126:	learn: 0.0636900	total: 2.65s	remaining: 11.2s
127:	learn: 0.0636898	total: 2.66s	remaining: 11.2s
128:	learn: 0.0636041	total: 2.68s	remaining: 11.2s
129:	learn: 0.0636038	total: 2.69s	remaining: 11.1s
130:	learn: 0.0636035	total: 2.71s	remaining: 11.1s
131:	learn: 0.0636032	total: 2.72s	remaining: 11s
132:	learn: 0.0636029	total: 2.74s	remaining: 11s
133:	learn: 0.0636027	total: 2.75s	remaining: 10.9s
134:	learn: 0.0636026	total: 2.76s	remaining: 10.9s
135:	learn: 0.0636024	total: 2.78s	remaining: 10.8s
136:	learn: 0.0636021	total: 2.79s	remaining: 10.8s
137:	learn: 0.0636022	total: 2.8s	remaining: 10.7s
138:	learn: 0.0636020	total: 2.81s	remaining: 10.7s
139:	learn: 0.0636020	total: 2.83s	remaining: 10.6s
140:	learn: 0.0636019	total: 2.84s	remaining: 10.6s
141:	learn: 0.0636018	total: 2.86s	remaining: 10.5s
142:	learn: 0.0636017	total: 2.87s	remaining: 10.5s
143:	learn: 0.0636017	total: 2.89s	remaining: 10.5s
144:	learn: 0.0636016	total: 2.9s	remaining: 10.4s
145:	learn: 0.0636015	total: 2.91s	remaining: 10.4s
146:	learn: 0.0636013	total: 2.93s	remaining: 10.3s
147:	learn: 0.0636012	total: 2.94s	remaining: 10.3s
148:	learn: 0.0636012	total: 2.96s	remaining: 10.3s
149:	learn: 0.0636011	total: 2.97s	remaining: 10.2s
150:	learn: 0.0636010	total: 2.98s	remaining: 10.2s
151:	learn: 0.0636009	total: 2.99s	remaining: 10.1s
152:	learn: 0.0636007	total: 3s	remaining: 10.1s
153:	learn: 0.0636006	total: 3.02s	remaining: 10s
154:	learn: 0.0636006	total: 3.03s	remaining: 10s
155:	learn: 0.0635489	total: 3.06s	remaining: 9.99s
156:	learn: 0.0635488	total: 3.07s	remaining: 9.95s
157:	learn: 0.0634628	total: 3.09s	remaining: 9.92s
158:	learn: 0.0634627	total: 3.1s	remaining: 9.89s
159:	learn: 0.0634626	total: 3.12s	remaining: 9.86s
160:	learn: 0.0634626	total: 3.13s	remaining: 9.82s
161:	learn: 0.0634312	total: 3.15s	remaining: 9.8s
162:	learn: 0.0634312	total: 3.16s	remaining: 9.76s
163:	learn: 0.0634310	total: 3.18s	remaining: 9.73s
164:	learn: 0.0634310	total: 3.19s	remaining: 9.7s
165:	learn: 0.0633583	total: 3.21s	remaining: 9.67s
166:	learn: 0.0633136	total: 3.23s	remaining: 9.65s
167:	learn: 0.0633135	total: 3.24s	remaining: 9.62s
168:	learn: 0.0632473	total: 3.26s	remaining: 9.6s
169:	learn: 0.0631660	total: 3.28s	remaining: 9.58s
170:	learn: 0.0631193	total: 3.3s	remaining: 9.56s
171:	learn: 0.0631193	total: 3.32s	remaining: 9.53s
172:	learn: 0.0631192	total: 3.33s	remaining: 9.5s
173:	learn: 0.0630658	total: 3.35s	remaining: 9.48s
174:	learn: 0.0630658	total: 3.37s	remaining: 9.45s
175:	learn: 0.0630658	total: 3.38s	remaining: 9.42s
176:	learn: 0.0630204	total: 3.4s	remaining: 9.4s
177:	learn: 0.0629934	total: 3.42s	remaining: 9.37s
178:	learn: 0.0629392	total: 3.44s	remaining: 9.35s
179:	learn: 0.0629391	total: 3.45s	remaining: 9.32s
180:	learn: 0.0629050	total: 3.47s	remaining: 9.29s
181:	learn: 0.0628449	total: 3.49s	remaining: 9.28s
182:	learn: 0.0627885	total: 3.51s	remaining: 9.27s
183:	learn: 0.0627486	total: 3.53s	remaining: 9.25s
184:	learn: 0.0627294	total: 3.55s	remaining: 9.22s
185:	learn: 0.0627294	total: 3.56s	remaining: 9.19s
186:	learn: 0.0627293	total: 3.57s	remaining: 9.15s
187:	learn: 0.0627292	total: 3.58s	remaining: 9.12s
188:	learn: 0.0626877	total: 3.6s	remaining: 9.09s
189:	learn: 0.0626877	total: 3.61s	remaining: 9.05s
190:	learn: 0.0626666	total: 3.63s	remaining: 9.02s
191:	learn: 0.0626666	total: 3.64s	remaining: 8.98s
192:	learn: 0.0626666	total: 3.65s	remaining: 8.95s
193:	learn: 0.0626206	total: 3.67s	remaining: 8.93s
194:	learn: 0.0625963	total: 3.69s	remaining: 8.9s
195:	learn: 0.0625600	total: 3.7s	remaining: 8.88s
196:	learn: 0.0625599	total: 3.71s	remaining: 8.84s
197:	learn: 0.0625599	total: 3.73s	remaining: 8.81s
198:	learn: 0.0625598	total: 3.74s	remaining: 8.78s
199:	learn: 0.0625378	total: 3.75s	remaining: 8.75s
200:	learn: 0.0625377	total: 3.77s	remaining: 8.72s
201:	learn: 0.0625377	total: 3.78s	remaining: 8.69s
202:	learn: 0.0625071	total: 3.8s	remaining: 8.66s
203:	learn: 0.0625059	total: 3.81s	remaining: 8.63s
204:	learn: 0.0625048	total: 3.83s	remaining: 8.6s
205:	learn: 0.0625047	total: 3.84s	remaining: 8.57s
206:	learn: 0.0625047	total: 3.85s	remaining: 8.54s
207:	learn: 0.0625047	total: 3.86s	remaining: 8.5s
208:	learn: 0.0625037	total: 3.88s	remaining: 8.47s
209:	learn: 0.0625027	total: 3.89s	remaining: 8.45s
210:	learn: 0.0625027	total: 3.9s	remaining: 8.42s
211:	learn: 0.0625026	total: 3.92s	remaining: 8.39s
212:	learn: 0.0625025	total: 3.93s	remaining: 8.36s
213:	learn: 0.0625026	total: 3.94s	remaining: 8.33s
214:	learn: 0.0625018	total: 3.96s	remaining: 8.3s
215:	learn: 0.0625015	total: 3.97s	remaining: 8.27s
216:	learn: 0.0625012	total: 3.98s	remaining: 8.24s
217:	learn: 0.0625011	total: 4s	remaining: 8.22s
218:	learn: 0.0625010	total: 4.01s	remaining: 8.19s
219:	learn: 0.0625009	total: 4.03s	remaining: 8.16s
220:	learn: 0.0625009	total: 4.04s	remaining: 8.13s
221:	learn: 0.0625007	total: 4.05s	remaining: 8.11s
222:	learn: 0.0625006	total: 4.07s	remaining: 8.08s
223:	learn: 0.0624635	total: 4.08s	remaining: 8.06s
224:	learn: 0.0624634	total: 4.1s	remaining: 8.03s
225:	learn: 0.0624635	total: 4.11s	remaining: 8.01s
226:	learn: 0.0624634	total: 4.13s	remaining: 7.98s
227:	learn: 0.0624632	total: 4.14s	remaining: 7.95s
228:	learn: 0.0624632	total: 4.15s	remaining: 7.92s
229:	learn: 0.0624630	total: 4.17s	remaining: 7.9s
230:	learn: 0.0624630	total: 4.18s	remaining: 7.87s
231:	learn: 0.0624627	total: 4.19s	remaining: 7.85s
232:	learn: 0.0624626	total: 4.21s	remaining: 7.82s
233:	learn: 0.0624354	total: 4.22s	remaining: 7.79s
234:	learn: 0.0623863	total: 4.24s	remaining: 7.77s
235:	learn: 0.0623862	total: 4.25s	remaining: 7.74s
236:	learn: 0.0623861	total: 4.26s	remaining: 7.71s
237:	learn: 0.0623860	total: 4.28s	remaining: 7.69s
238:	learn: 0.0623858	total: 4.29s	remaining: 7.66s
239:	learn: 0.0623633	total: 4.31s	remaining: 7.65s
240:	learn: 0.0623631	total: 4.32s	remaining: 7.62s
241:	learn: 0.0623631	total: 4.34s	remaining: 7.6s
242:	learn: 0.0623434	total: 4.35s	remaining: 7.58s
243:	learn: 0.0623433	total: 4.37s	remaining: 7.55s
244:	learn: 0.0623432	total: 4.38s	remaining: 7.53s
245:	learn: 0.0623431	total: 4.39s	remaining: 7.5s
246:	learn: 0.0623119	total: 4.41s	remaining: 7.48s
247:	learn: 0.0622783	total: 4.43s	remaining: 7.46s
248:	learn: 0.0622782	total: 4.44s	remaining: 7.44s
249:	learn: 0.0622419	total: 4.46s	remaining: 7.41s
250:	learn: 0.0622198	total: 4.47s	remaining: 7.39s
251:	learn: 0.0621938	total: 4.49s	remaining: 7.37s
252:	learn: 0.0621565	total: 4.5s	remaining: 7.35s
253:	learn: 0.0621192	total: 4.52s	remaining: 7.33s
254:	learn: 0.0620957	total: 4.54s	remaining: 7.31s
255:	learn: 0.0620615	total: 4.55s	remaining: 7.29s
256:	learn: 0.0620436	total: 4.57s	remaining: 7.27s
257:	learn: 0.0620435	total: 4.58s	remaining: 7.25s
258:	learn: 0.0620434	total: 4.6s	remaining: 7.22s
259:	learn: 0.0620063	total: 4.61s	remaining: 7.21s
260:	learn: 0.0619921	total: 4.63s	remaining: 7.18s
261:	learn: 0.0619610	total: 4.65s	remaining: 7.16s
262:	learn: 0.0619609	total: 4.66s	remaining: 7.14s
263:	learn: 0.0619266	total: 4.67s	remaining: 7.12s
264:	learn: 0.0619266	total: 4.69s	remaining: 7.09s
265:	learn: 0.0619266	total: 4.7s	remaining: 7.07s
266:	learn: 0.0619044	total: 4.71s	remaining: 7.04s
267:	learn: 0.0619043	total: 4.73s	remaining: 7.02s
268:	learn: 0.0618829	total: 4.74s	remaining: 7s
269:	learn: 0.0618829	total: 4.76s	remaining: 6.98s
270:	learn: 0.0618828	total: 4.77s	remaining: 6.96s
271:	learn: 0.0618517	total: 4.79s	remaining: 6.94s
272:	learn: 0.0618516	total: 4.8s	remaining: 6.91s
273:	learn: 0.0618515	total: 4.82s	remaining: 6.89s
274:	learn: 0.0618259	total: 4.83s	remaining: 6.87s
275:	learn: 0.0618258	total: 4.84s	remaining: 6.84s
276:	learn: 0.0618258	total: 4.86s	remaining: 6.82s
277:	learn: 0.0618258	total: 4.87s	remaining: 6.79s
278:	learn: 0.0618257	total: 4.88s	remaining: 6.77s
279:	learn: 0.0618257	total: 4.89s	remaining: 6.74s
280:	learn: 0.0618030	total: 4.91s	remaining: 6.72s
281:	learn: 0.0618029	total: 4.92s	remaining: 6.7s
282:	learn: 0.0618028	total: 4.93s	remaining: 6.68s
283:	learn: 0.0618028	total: 4.95s	remaining: 6.66s
284:	learn: 0.0618028	total: 4.96s	remaining: 6.64s
285:	learn: 0.0617700	total: 4.98s	remaining: 6.62s
286:	learn: 0.0617502	total: 5s	remaining: 6.6s
287:	learn: 0.0617288	total: 5.01s	remaining: 6.58s
288:	learn: 0.0617087	total: 5.03s	remaining: 6.56s
289:	learn: 0.0617086	total: 5.04s	remaining: 6.54s
290:	learn: 0.0617086	total: 5.06s	remaining: 6.52s
291:	learn: 0.0616559	total: 5.07s	remaining: 6.5s
292:	learn: 0.0616280	total: 5.09s	remaining: 6.48s
293:	learn: 0.0616280	total: 5.1s	remaining: 6.46s
294:	learn: 0.0615901	total: 5.12s	remaining: 6.43s
295:	learn: 0.0615678	total: 5.13s	remaining: 6.41s
296:	learn: 0.0615381	total: 5.14s	remaining: 6.39s
297:	learn: 0.0615097	total: 5.16s	remaining: 6.37s
298:	learn: 0.0615097	total: 5.18s	remaining: 6.35s
299:	learn: 0.0615097	total: 5.19s	remaining: 6.33s
300:	learn: 0.0614857	total: 5.21s	remaining: 6.31s
301:	learn: 0.0614857	total: 5.22s	remaining: 6.29s
302:	learn: 0.0614856	total: 5.23s	remaining: 6.27s
303:	learn: 0.0614856	total: 5.25s	remaining: 6.25s
304:	learn: 0.0614856	total: 5.26s	remaining: 6.23s
305:	learn: 0.0614621	total: 5.28s	remaining: 6.21s
306:	learn: 0.0614620	total: 5.29s	remaining: 6.19s
307:	learn: 0.0614620	total: 5.31s	remaining: 6.17s
308:	learn: 0.0614295	total: 5.32s	remaining: 6.15s
309:	learn: 0.0613760	total: 5.34s	remaining: 6.13s
310:	learn: 0.0613760	total: 5.35s	remaining: 6.11s
311:	learn: 0.0613422	total: 5.37s	remaining: 6.09s
312:	learn: 0.0613423	total: 5.38s	remaining: 6.07s
313:	learn: 0.0613124	total: 5.4s	remaining: 6.05s
314:	learn: 0.0613124	total: 5.41s	remaining: 6.03s
315:	learn: 0.0612869	total: 5.43s	remaining: 6.01s
316:	learn: 0.0612662	total: 5.45s	remaining: 6s
317:	learn: 0.0612661	total: 5.46s	remaining: 5.97s
318:	learn: 0.0612439	total: 5.48s	remaining: 5.96s
319:	learn: 0.0612439	total: 5.49s	remaining: 5.93s
320:	learn: 0.0612438	total: 5.5s	remaining: 5.91s
321:	learn: 0.0612437	total: 5.51s	remaining: 5.89s
322:	learn: 0.0612170	total: 5.53s	remaining: 5.88s
323:	learn: 0.0612169	total: 5.55s	remaining: 5.86s
324:	learn: 0.0612169	total: 5.56s	remaining: 5.84s
325:	learn: 0.0612169	total: 5.58s	remaining: 5.82s
326:	learn: 0.0612169	total: 5.59s	remaining: 5.79s
327:	learn: 0.0612030	total: 5.61s	remaining: 5.78s
328:	learn: 0.0611803	total: 5.62s	remaining: 5.76s
329:	learn: 0.0611405	total: 5.64s	remaining: 5.74s
330:	learn: 0.0611405	total: 5.66s	remaining: 5.72s
331:	learn: 0.0611405	total: 5.67s	remaining: 5.7s
332:	learn: 0.0611404	total: 5.68s	remaining: 5.68s
333:	learn: 0.0611404	total: 5.7s	remaining: 5.66s
334:	learn: 0.0611166	total: 5.71s	remaining: 5.64s
335:	learn: 0.0611165	total: 5.73s	remaining: 5.62s
336:	learn: 0.0611164	total: 5.79s	remaining: 5.65s
337:	learn: 0.0611164	total: 5.81s	remaining: 5.64s
338:	learn: 0.0611162	total: 5.83s	remaining: 5.62s
339:	learn: 0.0611161	total: 5.84s	remaining: 5.6s
340:	learn: 0.0611162	total: 5.86s	remaining: 5.58s
341:	learn: 0.0611161	total: 5.88s	remaining: 5.57s
342:	learn: 0.0611032	total: 5.89s	remaining: 5.55s
343:	learn: 0.0610791	total: 5.91s	remaining: 5.53s
344:	learn: 0.0610791	total: 5.92s	remaining: 5.51s
345:	learn: 0.0610790	total: 5.94s	remaining: 5.49s
346:	learn: 0.0610585	total: 5.96s	remaining: 5.48s
347:	learn: 0.0610584	total: 6.01s	remaining: 5.49s
348:	learn: 0.0610584	total: 6.03s	remaining: 5.47s
349:	learn: 0.0610221	total: 6.04s	remaining: 5.46s
350:	learn: 0.0609838	total: 6.06s	remaining: 5.44s
351:	learn: 0.0609480	total: 6.08s	remaining: 5.42s
352:	learn: 0.0609480	total: 6.09s	remaining: 5.4s
353:	learn: 0.0609479	total: 6.11s	remaining: 5.39s
354:	learn: 0.0609478	total: 6.13s	remaining: 5.37s
355:	learn: 0.0609478	total: 6.14s	remaining: 5.35s
356:	learn: 0.0609050	total: 6.16s	remaining: 5.33s
357:	learn: 0.0608810	total: 6.19s	remaining: 5.33s
358:	learn: 0.0608450	total: 6.25s	remaining: 5.34s
359:	learn: 0.0608449	total: 6.26s	remaining: 5.32s
360:	learn: 0.0608010	total: 6.28s	remaining: 5.31s
361:	learn: 0.0607877	total: 6.3s	remaining: 5.29s
362:	learn: 0.0607488	total: 6.32s	remaining: 5.27s
363:	learn: 0.0607488	total: 6.33s	remaining: 5.25s
364:	learn: 0.0607366	total: 6.35s	remaining: 5.24s
365:	learn: 0.0607249	total: 6.36s	remaining: 5.22s
366:	learn: 0.0606971	total: 6.38s	remaining: 5.2s
367:	learn: 0.0606436	total: 6.42s	remaining: 5.2s
368:	learn: 0.0606100	total: 6.44s	remaining: 5.18s
369:	learn: 0.0605765	total: 6.46s	remaining: 5.17s
370:	learn: 0.0605487	total: 6.49s	remaining: 5.16s
371:	learn: 0.0605148	total: 6.5s	remaining: 5.14s
372:	learn: 0.0605147	total: 6.52s	remaining: 5.12s
373:	learn: 0.0605147	total: 6.54s	remaining: 5.11s
374:	learn: 0.0604897	total: 6.56s	remaining: 5.09s
375:	learn: 0.0604620	total: 6.58s	remaining: 5.07s
376:	learn: 0.0604235	total: 6.59s	remaining: 5.05s
377:	learn: 0.0603861	total: 6.61s	remaining: 5.04s
378:	learn: 0.0603861	total: 6.63s	remaining: 5.02s
379:	learn: 0.0603561	total: 6.7s	remaining: 5.04s
380:	learn: 0.0603561	total: 6.71s	remaining: 5.02s
381:	learn: 0.0603560	total: 6.73s	remaining: 5s
382:	learn: 0.0603435	total: 6.74s	remaining: 4.98s
383:	learn: 0.0603408	total: 6.76s	remaining: 4.96s
384:	learn: 0.0603408	total: 6.78s	remaining: 4.95s
385:	learn: 0.0603300	total: 6.79s	remaining: 4.92s
386:	learn: 0.0603265	total: 6.8s	remaining: 4.9s
387:	learn: 0.0603141	total: 6.82s	remaining: 4.88s

[I 2026-04-16 17:38:27,232] Trial 4 finished with value: 0.9598352447950292 and parameters: {'iterations': 666, 'learning_rate': 0.06501407166933859, 'l2_leaf_reg': 3.3708479680987855, 'bootstrap_type': 'Bernoulli', 'max_depth': 8}. Best is trial 4 with value: 0.9598352447950292.

In [11]:
best_cb = CatBoostClassifier(
    random_seed=SEED,
    task_type="GPU",
    cat_features=cat_indices,
    **study.best_params
)

best_cb.fit(X_train, y_train)
y_preds = best_cb.predict(X_test)

balanced_accuracy_score(y_test, y_preds)

0:	learn: 1.0191591	total: 21.8ms	remaining: 14.5s
1:	learn: 0.9524918	total: 42.1ms	remaining: 14s
2:	learn: 0.8953177	total: 61.1ms	remaining: 13.5s
3:	learn: 0.8088801	total: 81.3ms	remaining: 13.5s
4:	learn: 0.7353051	total: 106ms	remaining: 14s
5:	learn: 0.6717737	total: 133ms	remaining: 14.6s
6:	learn: 0.6163055	total: 159ms	remaining: 15s
7:	learn: 0.5674489	total: 184ms	remaining: 15.1s
8:	learn: 0.5241088	total: 208ms	remaining: 15.2s
9:	learn: 0.4854344	total: 236ms	remaining: 15.4s
10:	learn: 0.4507135	total: 261ms	remaining: 15.5s
11:	learn: 0.4194702	total: 284ms	remaining: 15.5s
12:	learn: 0.3911937	total: 302ms	remaining: 15.2s
13:	learn: 0.3655553	total: 326ms	remaining: 15.2s
14:	learn: 0.3422633	total: 345ms	remaining: 15s
15:	learn: 0.3210083	total: 365ms	remaining: 14.8s
16:	learn: 0.3016166	total: 383ms	remaining: 14.6s
17:	learn: 0.2838432	total: 403ms	remaining: 14.5s
18:	learn: 0.2675525	total: 420ms	remaining: 14.3s
19:	learn: 0.2526157	total: 438ms	remaining: 14.2s
20:	learn: 0.2388622	total: 457ms	remaining: 14s
21:	learn: 0.2262250	total: 481ms	remaining: 14.1s
22:	learn: 0.2146058	total: 499ms	remaining: 14s
23:	learn: 0.2038390	total: 519ms	remaining: 13.9s
24:	learn: 0.1939177	total: 538ms	remaining: 13.8s
25:	learn: 0.1847439	total: 557ms	remaining: 13.7s
26:	learn: 0.1762639	total: 575ms	remaining: 13.6s
27:	learn: 0.1683960	total: 593ms	remaining: 13.5s
28:	learn: 0.1611266	total: 610ms	remaining: 13.4s
29:	learn: 0.1543899	total: 628ms	remaining: 13.3s
30:	learn: 0.1481249	total: 647ms	remaining: 13.3s
31:	learn: 0.1423542	total: 667ms	remaining: 13.2s
32:	learn: 0.1369742	total: 687ms	remaining: 13.2s
33:	learn: 0.1319782	total: 708ms	remaining: 13.2s
34:	learn: 0.1273697	total: 727ms	remaining: 13.1s
35:	learn: 0.1230792	total: 747ms	remaining: 13.1s
36:	learn: 0.1190474	total: 765ms	remaining: 13s
37:	learn: 0.1153675	total: 784ms	remaining: 13s
38:	learn: 0.1118919	total: 802ms	remaining: 12.9s
39:	learn: 0.1086823	total: 821ms	remaining: 12.8s
40:	learn: 0.1056887	total: 838ms	remaining: 12.8s
41:	learn: 0.1029087	total: 855ms	remaining: 12.7s
42:	learn: 0.1003061	total: 874ms	remaining: 12.7s
43:	learn: 0.0979145	total: 894ms	remaining: 12.6s
44:	learn: 0.0956566	total: 913ms	remaining: 12.6s
45:	learn: 0.0935493	total: 934ms	remaining: 12.6s
46:	learn: 0.0915830	total: 953ms	remaining: 12.6s
47:	learn: 0.0897843	total: 972ms	remaining: 12.5s
48:	learn: 0.0880736	total: 992ms	remaining: 12.5s
49:	learn: 0.0865104	total: 1.01s	remaining: 12.5s
50:	learn: 0.0850463	total: 1.03s	remaining: 12.4s
51:	learn: 0.0836772	total: 1.05s	remaining: 12.4s
52:	learn: 0.0823918	total: 1.07s	remaining: 12.4s
53:	learn: 0.0811820	total: 1.09s	remaining: 12.3s
54:	learn: 0.0800970	total: 1.11s	remaining: 12.3s
55:	learn: 0.0790332	total: 1.13s	remaining: 12.3s
56:	learn: 0.0780453	total: 1.15s	remaining: 12.3s
57:	learn: 0.0771475	total: 1.17s	remaining: 12.2s
58:	learn: 0.0762810	total: 1.19s	remaining: 12.2s
59:	learn: 0.0754905	total: 1.2s	remaining: 12.2s
60:	learn: 0.0747575	total: 1.22s	remaining: 12.1s
61:	learn: 0.0740379	total: 1.24s	remaining: 12.1s
62:	learn: 0.0733835	total: 1.26s	remaining: 12s
63:	learn: 0.0727791	total: 1.27s	remaining: 12s
64:	learn: 0.0722229	total: 1.29s	remaining: 12s
65:	learn: 0.0716837	total: 1.31s	remaining: 11.9s
66:	learn: 0.0711890	total: 1.33s	remaining: 11.9s
67:	learn: 0.0707664	total: 1.35s	remaining: 11.9s
68:	learn: 0.0703703	total: 1.37s	remaining: 11.9s
69:	learn: 0.0699354	total: 1.39s	remaining: 11.8s
70:	learn: 0.0696107	total: 1.4s	remaining: 11.8s
71:	learn: 0.0692274	total: 1.42s	remaining: 11.7s
72:	learn: 0.0688919	total: 1.44s	remaining: 11.7s
73:	learn: 0.0686244	total: 1.46s	remaining: 11.7s
74:	learn: 0.0683132	total: 1.47s	remaining: 11.6s
75:	learn: 0.0680735	total: 1.49s	remaining: 11.6s
76:	learn: 0.0678553	total: 1.51s	remaining: 11.5s
77:	learn: 0.0676161	total: 1.52s	remaining: 11.5s
78:	learn: 0.0674343	total: 1.54s	remaining: 11.5s
79:	learn: 0.0672002	total: 1.56s	remaining: 11.4s
80:	learn: 0.0670174	total: 1.58s	remaining: 11.4s
81:	learn: 0.0668282	total: 1.59s	remaining: 11.4s
82:	learn: 0.0666481	total: 1.61s	remaining: 11.3s
83:	learn: 0.0664659	total: 1.63s	remaining: 11.3s
84:	learn: 0.0663076	total: 1.64s	remaining: 11.2s
85:	learn: 0.0661756	total: 1.66s	remaining: 11.2s
86:	learn: 0.0660332	total: 1.67s	remaining: 11.1s
87:	learn: 0.0658944	total: 1.69s	remaining: 11.1s
88:	learn: 0.0657082	total: 1.71s	remaining: 11.1s
89:	learn: 0.0655598	total: 1.73s	remaining: 11.1s
90:	learn: 0.0654104	total: 1.75s	remaining: 11s
91:	learn: 0.0653279	total: 1.76s	remaining: 11s
92:	learn: 0.0652290	total: 1.78s	remaining: 11s
93:	learn: 0.0651295	total: 1.8s	remaining: 10.9s
94:	learn: 0.0650432	total: 1.81s	remaining: 10.9s
95:	learn: 0.0649206	total: 1.83s	remaining: 10.9s
96:	learn: 0.0648586	total: 1.85s	remaining: 10.9s
97:	learn: 0.0647802	total: 1.87s	remaining: 10.8s
98:	learn: 0.0646763	total: 1.88s	remaining: 10.8s
99:	learn: 0.0646154	total: 1.9s	remaining: 10.7s
100:	learn: 0.0645079	total: 1.92s	remaining: 10.8s
101:	learn: 0.0644584	total: 1.94s	remaining: 10.7s
102:	learn: 0.0643581	total: 1.96s	remaining: 10.7s
103:	learn: 0.0642964	total: 1.97s	remaining: 10.7s
104:	learn: 0.0642319	total: 1.99s	remaining: 10.6s
105:	learn: 0.0641493	total: 2s	remaining: 10.6s
106:	learn: 0.0640840	total: 2.02s	remaining: 10.5s
107:	learn: 0.0640302	total: 2.03s	remaining: 10.5s
108:	learn: 0.0639980	total: 2.05s	remaining: 10.5s
109:	learn: 0.0639530	total: 2.06s	remaining: 10.4s
110:	learn: 0.0638965	total: 2.08s	remaining: 10.4s
111:	learn: 0.0638791	total: 2.09s	remaining: 10.3s
112:	learn: 0.0638778	total: 2.1s	remaining: 10.3s
113:	learn: 0.0638766	total: 2.12s	remaining: 10.3s
114:	learn: 0.0638756	total: 2.13s	remaining: 10.2s
115:	learn: 0.0638748	total: 2.15s	remaining: 10.2s
116:	learn: 0.0638106	total: 2.16s	remaining: 10.1s
117:	learn: 0.0637442	total: 2.18s	remaining: 10.1s
118:	learn: 0.0636938	total: 2.19s	remaining: 10.1s
119:	learn: 0.0636932	total: 2.21s	remaining: 10.1s
120:	learn: 0.0636926	total: 2.22s	remaining: 10s
121:	learn: 0.0636922	total: 2.24s	remaining: 9.97s
122:	learn: 0.0636917	total: 2.25s	remaining: 9.94s
123:	learn: 0.0636912	total: 2.26s	remaining: 9.9s
124:	learn: 0.0636908	total: 2.28s	remaining: 9.86s
125:	learn: 0.0636904	total: 2.29s	remaining: 9.81s
126:	learn: 0.0636900	total: 2.3s	remaining: 9.77s
127:	learn: 0.0636898	total: 2.31s	remaining: 9.72s
128:	learn: 0.0636041	total: 2.33s	remaining: 9.69s
129:	learn: 0.0636038	total: 2.34s	remaining: 9.65s
130:	learn: 0.0636035	total: 2.35s	remaining: 9.61s
131:	learn: 0.0636032	total: 2.37s	remaining: 9.58s
132:	learn: 0.0636029	total: 2.38s	remaining: 9.55s
133:	learn: 0.0636026	total: 2.4s	remaining: 9.52s
134:	learn: 0.0636026	total: 2.41s	remaining: 9.48s
135:	learn: 0.0636024	total: 2.42s	remaining: 9.45s
136:	learn: 0.0636021	total: 2.44s	remaining: 9.41s
137:	learn: 0.0636021	total: 2.45s	remaining: 9.38s
138:	learn: 0.0636020	total: 2.46s	remaining: 9.35s
139:	learn: 0.0636020	total: 2.48s	remaining: 9.31s
140:	learn: 0.0636019	total: 2.49s	remaining: 9.27s
141:	learn: 0.0636018	total: 2.5s	remaining: 9.23s
142:	learn: 0.0636017	total: 2.51s	remaining: 9.19s
143:	learn: 0.0636017	total: 2.52s	remaining: 9.16s
144:	learn: 0.0636016	total: 2.54s	remaining: 9.12s
145:	learn: 0.0636015	total: 2.55s	remaining: 9.08s
146:	learn: 0.0636013	total: 2.56s	remaining: 9.04s
147:	learn: 0.0636012	total: 2.57s	remaining: 9.01s
148:	learn: 0.0636012	total: 2.59s	remaining: 8.98s
149:	learn: 0.0636011	total: 2.6s	remaining: 8.96s
150:	learn: 0.0636010	total: 2.62s	remaining: 8.93s
151:	learn: 0.0636009	total: 2.63s	remaining: 8.9s
152:	learn: 0.0636007	total: 2.64s	remaining: 8.86s
153:	learn: 0.0636006	total: 2.66s	remaining: 8.83s
154:	learn: 0.0636006	total: 2.67s	remaining: 8.8s
155:	learn: 0.0635489	total: 2.69s	remaining: 8.78s
156:	learn: 0.0635488	total: 2.7s	remaining: 8.75s
157:	learn: 0.0634628	total: 2.71s	remaining: 8.73s
158:	learn: 0.0634627	total: 2.73s	remaining: 8.69s
159:	learn: 0.0634626	total: 2.74s	remaining: 8.66s
160:	learn: 0.0634626	total: 2.75s	remaining: 8.63s
161:	learn: 0.0634312	total: 2.77s	remaining: 8.61s
162:	learn: 0.0634312	total: 2.78s	remaining: 8.57s
163:	learn: 0.0634310	total: 2.79s	remaining: 8.54s
164:	learn: 0.0634310	total: 2.81s	remaining: 8.52s
165:	learn: 0.0633583	total: 2.82s	remaining: 8.5s
166:	learn: 0.0633136	total: 2.84s	remaining: 8.48s
167:	learn: 0.0633135	total: 2.85s	remaining: 8.46s
168:	learn: 0.0632473	total: 2.87s	remaining: 8.44s
169:	learn: 0.0631660	total: 2.89s	remaining: 8.43s
170:	learn: 0.0631193	total: 2.9s	remaining: 8.41s
171:	learn: 0.0631193	total: 2.92s	remaining: 8.38s
172:	learn: 0.0631192	total: 2.93s	remaining: 8.35s
173:	learn: 0.0630658	total: 2.94s	remaining: 8.33s
174:	learn: 0.0630658	total: 2.96s	remaining: 8.3s
175:	learn: 0.0630658	total: 2.97s	remaining: 8.27s
176:	learn: 0.0630204	total: 2.99s	remaining: 8.26s
177:	learn: 0.0629934	total: 3s	remaining: 8.24s
178:	learn: 0.0629392	total: 3.02s	remaining: 8.22s
179:	learn: 0.0629391	total: 3.03s	remaining: 8.19s
180:	learn: 0.0629050	total: 3.05s	remaining: 8.18s
181:	learn: 0.0628449	total: 3.07s	remaining: 8.17s
182:	learn: 0.0627885	total: 3.09s	remaining: 8.15s
183:	learn: 0.0627486	total: 3.11s	remaining: 8.14s
184:	learn: 0.0627294	total: 3.12s	remaining: 8.12s
185:	learn: 0.0627294	total: 3.13s	remaining: 8.09s
186:	learn: 0.0627293	total: 3.15s	remaining: 8.07s
187:	learn: 0.0627292	total: 3.16s	remaining: 8.04s
188:	learn: 0.0626877	total: 3.18s	remaining: 8.02s
189:	learn: 0.0626877	total: 3.19s	remaining: 8s
190:	learn: 0.0626666	total: 3.21s	remaining: 7.97s
191:	learn: 0.0626666	total: 3.22s	remaining: 7.95s
192:	learn: 0.0626666	total: 3.23s	remaining: 7.92s
193:	learn: 0.0626205	total: 3.25s	remaining: 7.91s
194:	learn: 0.0625963	total: 3.27s	remaining: 7.89s
195:	learn: 0.0625600	total: 3.28s	remaining: 7.87s
196:	learn: 0.0625599	total: 3.3s	remaining: 7.85s
197:	learn: 0.0625599	total: 3.31s	remaining: 7.82s
198:	learn: 0.0625598	total: 3.32s	remaining: 7.8s
199:	learn: 0.0625378	total: 3.34s	remaining: 7.78s
200:	learn: 0.0625377	total: 3.35s	remaining: 7.75s
201:	learn: 0.0625377	total: 3.37s	remaining: 7.73s
202:	learn: 0.0625071	total: 3.38s	remaining: 7.71s
203:	learn: 0.0625059	total: 3.4s	remaining: 7.69s
204:	learn: 0.0625048	total: 3.41s	remaining: 7.67s
205:	learn: 0.0625047	total: 3.42s	remaining: 7.64s
206:	learn: 0.0625047	total: 3.43s	remaining: 7.62s
207:	learn: 0.0625047	total: 3.45s	remaining: 7.59s
208:	learn: 0.0625037	total: 3.46s	remaining: 7.57s
209:	learn: 0.0625027	total: 3.48s	remaining: 7.55s
210:	learn: 0.0625027	total: 3.49s	remaining: 7.52s
211:	learn: 0.0625026	total: 3.5s	remaining: 7.5s
212:	learn: 0.0625025	total: 3.51s	remaining: 7.47s
213:	learn: 0.0625026	total: 3.53s	remaining: 7.45s
214:	learn: 0.0625018	total: 3.54s	remaining: 7.43s
215:	learn: 0.0625015	total: 3.55s	remaining: 7.4s
216:	learn: 0.0625012	total: 3.56s	remaining: 7.38s
217:	learn: 0.0625011	total: 3.58s	remaining: 7.35s
218:	learn: 0.0625010	total: 3.59s	remaining: 7.33s
219:	learn: 0.0625009	total: 3.6s	remaining: 7.3s
220:	learn: 0.0625009	total: 3.62s	remaining: 7.28s
221:	learn: 0.0625007	total: 3.63s	remaining: 7.26s
222:	learn: 0.0625006	total: 3.64s	remaining: 7.24s
223:	learn: 0.0624635	total: 3.66s	remaining: 7.22s
224:	learn: 0.0624634	total: 3.67s	remaining: 7.19s
225:	learn: 0.0624634	total: 3.68s	remaining: 7.17s
226:	learn: 0.0624634	total: 3.7s	remaining: 7.15s
227:	learn: 0.0624633	total: 3.71s	remaining: 7.13s
228:	learn: 0.0624632	total: 3.72s	remaining: 7.11s
229:	learn: 0.0624630	total: 3.74s	remaining: 7.08s
230:	learn: 0.0624630	total: 3.75s	remaining: 7.06s
231:	learn: 0.0624627	total: 3.76s	remaining: 7.04s
232:	learn: 0.0624626	total: 3.77s	remaining: 7.02s
233:	learn: 0.0624354	total: 3.79s	remaining: 7s
234:	learn: 0.0623863	total: 3.8s	remaining: 6.97s
235:	learn: 0.0623862	total: 3.82s	remaining: 6.95s
236:	learn: 0.0623861	total: 3.83s	remaining: 6.93s
237:	learn: 0.0623860	total: 3.84s	remaining: 6.91s
238:	learn: 0.0623858	total: 3.85s	remaining: 6.89s
239:	learn: 0.0623633	total: 3.87s	remaining: 6.87s
240:	learn: 0.0623631	total: 3.88s	remaining: 6.85s
241:	learn: 0.0623631	total: 3.9s	remaining: 6.83s
242:	learn: 0.0623434	total: 3.91s	remaining: 6.81s
243:	learn: 0.0623433	total: 3.93s	remaining: 6.79s
244:	learn: 0.0623433	total: 3.94s	remaining: 6.77s
245:	learn: 0.0623431	total: 3.95s	remaining: 6.75s
246:	learn: 0.0623120	total: 3.97s	remaining: 6.73s
247:	learn: 0.0622783	total: 3.98s	remaining: 6.71s
248:	learn: 0.0622782	total: 4s	remaining: 6.69s
249:	learn: 0.0622419	total: 4.01s	remaining: 6.67s
250:	learn: 0.0622198	total: 4.02s	remaining: 6.65s
251:	learn: 0.0621938	total: 4.04s	remaining: 6.63s
252:	learn: 0.0621566	total: 4.05s	remaining: 6.62s
253:	learn: 0.0621192	total: 4.07s	remaining: 6.6s
254:	learn: 0.0620957	total: 4.08s	remaining: 6.58s
255:	learn: 0.0620615	total: 4.1s	remaining: 6.56s
256:	learn: 0.0620436	total: 4.12s	remaining: 6.55s
257:	learn: 0.0620435	total: 4.13s	remaining: 6.53s
258:	learn: 0.0620434	total: 4.14s	remaining: 6.51s
259:	learn: 0.0620063	total: 4.16s	remaining: 6.5s
260:	learn: 0.0619921	total: 4.17s	remaining: 6.48s
261:	learn: 0.0619610	total: 4.19s	remaining: 6.46s
262:	learn: 0.0619609	total: 4.2s	remaining: 6.44s
263:	learn: 0.0619267	total: 4.21s	remaining: 6.42s
264:	learn: 0.0619266	total: 4.23s	remaining: 6.4s
265:	learn: 0.0619266	total: 4.24s	remaining: 6.38s
266:	learn: 0.0619044	total: 4.25s	remaining: 6.36s
267:	learn: 0.0619043	total: 4.27s	remaining: 6.34s
268:	learn: 0.0618829	total: 4.28s	remaining: 6.32s
269:	learn: 0.0618829	total: 4.29s	remaining: 6.3s
270:	learn: 0.0618828	total: 4.31s	remaining: 6.28s
271:	learn: 0.0618517	total: 4.33s	remaining: 6.27s
272:	learn: 0.0618516	total: 4.34s	remaining: 6.25s
273:	learn: 0.0618515	total: 4.35s	remaining: 6.23s
274:	learn: 0.0618259	total: 4.37s	remaining: 6.21s
275:	learn: 0.0618258	total: 4.38s	remaining: 6.19s
276:	learn: 0.0618258	total: 4.39s	remaining: 6.17s
277:	learn: 0.0618258	total: 4.4s	remaining: 6.15s
278:	learn: 0.0618258	total: 4.42s	remaining: 6.13s
279:	learn: 0.0618257	total: 4.43s	remaining: 6.11s
280:	learn: 0.0618030	total: 4.44s	remaining: 6.09s
281:	learn: 0.0618029	total: 4.45s	remaining: 6.07s
282:	learn: 0.0618028	total: 4.47s	remaining: 6.05s
283:	learn: 0.0618028	total: 4.49s	remaining: 6.03s
284:	learn: 0.0618028	total: 4.5s	remaining: 6.01s
285:	learn: 0.0617700	total: 4.51s	remaining: 6s
286:	learn: 0.0617502	total: 4.53s	remaining: 5.98s
287:	learn: 0.0617288	total: 4.54s	remaining: 5.96s
288:	learn: 0.0617086	total: 4.56s	remaining: 5.95s
289:	learn: 0.0617086	total: 4.57s	remaining: 5.93s
290:	learn: 0.0617086	total: 4.58s	remaining: 5.91s
291:	learn: 0.0616559	total: 4.6s	remaining: 5.89s
292:	learn: 0.0616280	total: 4.62s	remaining: 5.88s
293:	learn: 0.0616280	total: 4.63s	remaining: 5.86s
294:	learn: 0.0615901	total: 4.65s	remaining: 5.85s
295:	learn: 0.0615678	total: 4.66s	remaining: 5.83s
296:	learn: 0.0615381	total: 4.68s	remaining: 5.82s
297:	learn: 0.0615097	total: 4.7s	remaining: 5.8s
298:	learn: 0.0615097	total: 4.71s	remaining: 5.78s
299:	learn: 0.0615097	total: 4.72s	remaining: 5.76s
300:	learn: 0.0614857	total: 4.74s	remaining: 5.75s
301:	learn: 0.0614857	total: 4.75s	remaining: 5.73s
302:	learn: 0.0614856	total: 4.77s	remaining: 5.71s
303:	learn: 0.0614856	total: 4.78s	remaining: 5.69s
304:	learn: 0.0614856	total: 4.79s	remaining: 5.67s
305:	learn: 0.0614621	total: 4.81s	remaining: 5.66s
306:	learn: 0.0614620	total: 4.82s	remaining: 5.64s
307:	learn: 0.0614620	total: 4.83s	remaining: 5.62s
308:	learn: 0.0614295	total: 4.85s	remaining: 5.6s
309:	learn: 0.0613760	total: 4.87s	remaining: 5.59s
310:	learn: 0.0613760	total: 4.88s	remaining: 5.57s
311:	learn: 0.0613422	total: 4.9s	remaining: 5.55s
312:	learn: 0.0613423	total: 4.91s	remaining: 5.54s
313:	learn: 0.0613124	total: 4.92s	remaining: 5.52s
314:	learn: 0.0613124	total: 4.94s	remaining: 5.5s
315:	learn: 0.0612869	total: 4.96s	remaining: 5.49s
316:	learn: 0.0612662	total: 4.97s	remaining: 5.47s
317:	learn: 0.0612661	total: 4.98s	remaining: 5.45s
318:	learn: 0.0612439	total: 5s	remaining: 5.44s
319:	learn: 0.0612439	total: 5.01s	remaining: 5.42s
320:	learn: 0.0612438	total: 5.03s	remaining: 5.4s
321:	learn: 0.0612438	total: 5.04s	remaining: 5.38s
322:	learn: 0.0612170	total: 5.05s	remaining: 5.37s
323:	learn: 0.0612169	total: 5.07s	remaining: 5.35s
324:	learn: 0.0612169	total: 5.08s	remaining: 5.33s
325:	learn: 0.0612169	total: 5.1s	remaining: 5.32s
326:	learn: 0.0612169	total: 5.11s	remaining: 5.3s
327:	learn: 0.0612030	total: 5.13s	remaining: 5.28s
328:	learn: 0.0611803	total: 5.14s	remaining: 5.27s
329:	learn: 0.0611405	total: 5.16s	remaining: 5.25s
330:	learn: 0.0611405	total: 5.18s	remaining: 5.24s
331:	learn: 0.0611405	total: 5.19s	remaining: 5.22s
332:	learn: 0.0611404	total: 5.2s	remaining: 5.2s
333:	learn: 0.0611404	total: 5.21s	remaining: 5.18s
334:	learn: 0.0611166	total: 5.23s	remaining: 5.17s
335:	learn: 0.0611165	total: 5.25s	remaining: 5.15s
336:	learn: 0.0611164	total: 5.26s	remaining: 5.13s
337:	learn: 0.0611164	total: 5.27s	remaining: 5.12s
338:	learn: 0.0611162	total: 5.28s	remaining: 5.1s
339:	learn: 0.0611161	total: 5.3s	remaining: 5.08s
340:	learn: 0.0611162	total: 5.31s	remaining: 5.06s
341:	learn: 0.0611161	total: 5.33s	remaining: 5.05s
342:	learn: 0.0611032	total: 5.34s	remaining: 5.03s
343:	learn: 0.0610791	total: 5.36s	remaining: 5.01s
344:	learn: 0.0610791	total: 5.37s	remaining: 5s
345:	learn: 0.0610790	total: 5.39s	remaining: 4.98s
346:	learn: 0.0610585	total: 5.4s	remaining: 4.97s
347:	learn: 0.0610584	total: 5.42s	remaining: 4.95s
348:	learn: 0.0610584	total: 5.43s	remaining: 4.93s
349:	learn: 0.0610221	total: 5.44s	remaining: 4.91s
350:	learn: 0.0609838	total: 5.46s	remaining: 4.89s
351:	learn: 0.0609480	total: 5.47s	remaining: 4.88s
352:	learn: 0.0609480	total: 5.48s	remaining: 4.86s
353:	learn: 0.0609479	total: 5.5s	remaining: 4.85s
354:	learn: 0.0609478	total: 5.51s	remaining: 4.83s
355:	learn: 0.0609478	total: 5.53s	remaining: 4.81s
356:	learn: 0.0609050	total: 5.54s	remaining: 4.8s
357:	learn: 0.0608810	total: 5.56s	remaining: 4.79s
358:	learn: 0.0608450	total: 5.58s	remaining: 4.77s
359:	learn: 0.0608449	total: 5.59s	remaining: 4.75s
360:	learn: 0.0608010	total: 5.61s	remaining: 4.74s
361:	learn: 0.0607877	total: 5.63s	remaining: 4.72s
362:	learn: 0.0607488	total: 5.64s	remaining: 4.71s
363:	learn: 0.0607488	total: 5.65s	remaining: 4.69s
364:	learn: 0.0607366	total: 5.67s	remaining: 4.67s
365:	learn: 0.0607249	total: 5.68s	remaining: 4.66s
366:	learn: 0.0606970	total: 5.7s	remaining: 4.64s
367:	learn: 0.0606436	total: 5.72s	remaining: 4.63s
368:	learn: 0.0606100	total: 5.73s	remaining: 4.61s
369:	learn: 0.0605765	total: 5.75s	remaining: 4.6s
370:	learn: 0.0605487	total: 5.77s	remaining: 4.59s
371:	learn: 0.0605148	total: 5.79s	remaining: 4.57s
372:	learn: 0.0605147	total: 5.8s	remaining: 4.56s
373:	learn: 0.0605147	total: 5.81s	remaining: 4.54s
374:	learn: 0.0604897	total: 5.83s	remaining: 4.52s
375:	learn: 0.0604620	total: 5.85s	remaining: 4.51s
376:	learn: 0.0604235	total: 5.87s	remaining: 4.5s
377:	learn: 0.0603861	total: 5.88s	remaining: 4.48s
378:	learn: 0.0603861	total: 5.9s	remaining: 4.47s
379:	learn: 0.0603561	total: 5.91s	remaining: 4.45s
380:	learn: 0.0603561	total: 5.93s	remaining: 4.43s
381:	learn: 0.0603560	total: 5.94s	remaining: 4.42s
382:	learn: 0.0603435	total: 5.96s	remaining: 4.4s
383:	learn: 0.0603408	total: 5.97s	remaining: 4.38s
384:	learn: 0.0603408	total: 5.98s	remaining: 4.37s
385:	learn: 0.0603300	total: 5.99s	remaining: 4.35s
386:	learn: 0.0603265	total: 6.01s	remaining: 4.33s
387:	learn: 0.0603141	total: 6.02s	remaining: 4.31s

0.9596613957773411

## submission

In [12]:
test = pd.read_csv(DATA_DIR / "test.csv", index_col="id")
test.head()

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region
id,,,,,,,,,,,,,,,,,,,
630000,Silt,6.36,26.19,0.59,2.81,17.83,30.24,1533.38,5.40,3.00,Maize,Sowing,Rabi,Canal,River,13.59,Yes,47.48,West
630001,Clay,5.87,9.88,1.18,3.26,21.18,78.07,576.05,7.22,15.88,Cotton,Sowing,Rabi,Drip,Reservoir,6.12,Yes,56.43,South
630002,Sandy,6.22,26.55,0.96,0.85,26.87,60.35,545.30,9.43,2.63,Wheat,Sowing,Kharif,Sprinkler,Reservoir,3.11,Yes,20.00,East
630003,Clay,7.68,53.58,0.83,0.55,41.74,36.05,1211.03,6.69,1.86,Maize,Harvest,Rabi,Canal,Groundwater,2.27,No,102.99,North
630004,Loamy,5.23,59.02,0.54,2.11,41.08,52.47,1321.91,4.11,5.71,Cotton,Sowing,Kharif,Canal,Groundwater,12.39,Yes,13.33,Central

In [15]:
final_preds = pd.DataFrame({"Irrigation_Need": le.inverse_transform(best_cb.predict(test))}, index=test.index)
final_preds.index.name = "id"

final_preds

C:\miniforge3\envs\machine-learning\Lib\site-packages\sklearn\preprocessing\_label.py:161: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

       Irrigation_Need
id
630000             Low
630001             Low
630002             Low
630003             Low
630004             Low
...                ...
899995          Medium
899996             Low
899997          Medium
899998             Low
899999          Medium

[270000 rows x 1 columns]

In [16]:
final_preds.to_csv(DATA_DIR / "boosting_preds.csv")